<ul>
	<li><a name="zongl.info"></a><a href="/">®onglérùv slabikáø</a>
	<ul>
	<li><a href="/aczslovnicek.html">Anglicko-èeský ¾onglérský slovníèek</a></li>
	<li><a href="/changelog.html">Zmìny v ¾onglérovì slabikáøi</a></li>
	<li><a href="/cirkusove-discipliny.html">Cirkusové disciplíny</a></li>
	<li><a href="/druhy-zonglovani.html">Druhy ¾onglování</a></li>
	<li><a href="/faq.html">Èasto kladené otázky</a></li>
	<li><a href="/jak-odkazovat.html">Jak odkazovat na ¾onglérùv slabikáø</a></li>
	<li><a href="/kontakt.html">Kontakt</a></li>
	<li><a href="/literatura.html">Literatura</a></li>
	<li><a href="/myty-omyly.html">Mýty a omyly</a></li>
	<li><a href="/nacini.html">®onglérské náèiní</a></li>
	<li><a href="/odkazy.html">®onglování na síti</a></li>
	<li><a href="/ostatni.html">Dal¹í informace o ¾onglování</a></li>
	<li><a href="/podporte-zongleruv-slabikar.html">Podpoøte ¾onglérùv slabikáø</a></li>
	<li><a href="/proc-a-jak.html">Proè a jak vznikl ¾ognlérùv slabikáø</a></li>
	<li><a href="/rss.html">RSS kanály</a></li>
	<li><a href="/siteswap.html">Siteswap</a></li>
	<li><a href="/software.html">Simulátory ¾onglování</a></li>
	<li><a href="/trenink.html">Trénink</a></li>
	<li><a href="/zakladni-pojmy.html">®onglování - základní pojmy</a></li>
		<li><a name="chudy"></a><a href="/chudy/">Chùdy</a>
		
		</li>
		<li><a name="diskuse"></a>diskuse/
		
		</li>
		<li><a name="horoskop"></a>horoskop/
		<ul>
		<li><a href="/horoskop/beran.html">Horoskop ¾onglování - Beran</a></li>
		<li><a href="/horoskop/blizenci.html">Horoskop ¾onglování - Blí¾enci</a></li>
		<li><a href="/horoskop/byk.html">Horoskop ¾onglování - Býk</a></li>
		<li><a href="/horoskop/kozoroh.html">Horoskop ¾onglování - Kozoroh</a></li>
		<li><a href="/horoskop/lev.html">Horoskop ¾onglování - Lev</a></li>
		<li><a href="/horoskop/panna.html">Horoskop ¾onglování - Panna</a></li>
		<li><a href="/horoskop/popis.html">Jak vzniká horoskop ¾onglování</a></li>
		<li><a href="/horoskop/rak.html">Horoskop ¾onglování - Rak</a></li>
		<li><a href="/horoskop/ryby.html">Horoskop ¾onglování - Ryby</a></li>
		<li><a href="/horoskop/stir.html">Horoskop ¾onglování - ©tír</a></li>
		<li><a href="/horoskop/strelec.html">Horoskop ¾onglování - Støelec</a></li>
		<li><a href="/horoskop/vahy.html">Horoskop ¾onglování - Váhy</a></li>
		<li><a href="/horoskop/vodnar.html">Horoskop ¾onglování - Vodnáø</a></li>
			<li><a name="zitra"></a>horoskop/zitra/
			<ul>
			<li><a href="/horoskop/zitra/beran.html">Horoskop ¾onglování na zítra - Beran</a></li>
			<li><a href="/horoskop/zitra/blizenci.html">Horoskop ¾onglování na zítra - Blí¾enci</a></li>
			<li><a href="/horoskop/zitra/byk.html">Horoskop ¾onglování na zítra - Býk</a></li>
			<li><a href="/horoskop/zitra/kozoroh.html">Horoskop ¾onglování na zítra - Kozoroh</a></li>
			<li><a href="/horoskop/zitra/lev.html">Horoskop ¾onglování na zítra - Lev</a></li>
			<li><a href="/horoskop/zitra/panna.html">Horoskop ¾onglování na zítra - Panna</a></li>
			<li><a href="/horoskop/zitra/rak.html">Horoskop ¾onglování na zítra - Rak</a></li>
			<li><a href="/horoskop/zitra/ryby.html">Horoskop ¾onglování na zítra - Ryby</a></li>
			<li><a href="/horoskop/zitra/stir.html">Horoskop ¾onglování na zítra - ©tír</a></li>
			<li><a href="/horoskop/zitra/strelec.html">Horoskop ¾onglování na zítra - Støelec</a></li>
			<li><a href="/horoskop/zitra/vahy.html">Horoskop ¾onglování na zítra - Váhy</a></li>
			<li><a href="/horoskop/zitra/vodnar.html">Horoskop ¾onglování na zítra - Vodnáø</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="kalendar"></a><a href="/kalendar/">Kalendáø ¾onglérských akcí</a>
		
		</li>
		<li><a name="kruhy"></a><a href="/kruhy/">®onglování s kruhy</a>
		<ul>
		<li><a href="/kruhy/jak-zacit.html">Jak zaèít ¾onglovat s kruhy</a></li>
		<li><a href="/kruhy/legenda.html">Vysvìtlivky k obrázkùm - kruhy</a></li>
		<li><a href="/kruhy/vyroba.html">Výroba kruhù</a></li>
			<li><a name="2"></a>kruhy/2/
			<ul>
			<li><a href="/kruhy/2/2v1.html">®onglování se dvìma kruhy - 2 v 1</a></li>
			</ul>
			</li>
			<li><a name="3"></a>kruhy/3/
			<ul>
			<li><a href="/kruhy/3/kaskada.html">®onglování se tøemi kruhy - Kaskáda</a></li>
			<li><a href="/kruhy/3/noha.html">®onglování se tøemi kruhy - Prohození kruhu pod nohou</a></li>
			<li><a href="/kruhy/3/sloupy.html">®onglování se tøemi kruhy - Sloupy</a></li>
			</ul>
			</li>
			<li><a name="4"></a>kruhy/4/
			<ul>
			<li><a href="/kruhy/4/fontana.html">®onglování se ètyømi kruhy - Fontána</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="kuzely"></a><a href="/kuzely/">®onglování s ku¾ely</a>
		<ul>
		<li><a href="/kuzely/balanc.html">Balancování ku¾elu</a></li>
		<li><a href="/kuzely/grip.html">Dva ku¾ely v jedné ruce</a></li>
		<li><a href="/kuzely/headroll.html">Pøekulení ku¾elky pøes hlavu</a></li>
		<li><a href="/kuzely/jak-zacit.html">®onglování s ku¾ely</a></li>
		<li><a href="/kuzely/kickup.html">Zvednutí ku¾elu nohou</a></li>
		<li><a href="/kuzely/konstrukce.html">Konstrukce ku¾elu</a></li>
		<li><a href="/kuzely/legenda.html">Vysvìtlivky k obrázkùm - ku¾ely</a></li>
		<li><a href="/kuzely/ohen.html">Ohnivé ku¾ely</a></li>
		<li><a href="/kuzely/rotace.html">Rotace ku¾elu</a></li>
		<li><a href="/kuzely/toceni-okolo-palce.html">Otáèení ku¾elky okolo palce</a></li>
		<li><a href="/kuzely/vyroba.html">Výroba ku¾elù</a></li>
			<li><a name="3"></a><a href="/kuzely/3/">®onglování tøemi ku¾ely</a>
			<ul>
			<li><a href="/kuzely/3/423.html">®onglování tøemi ku¾ely - 423</a></li>
			<li><a href="/kuzely/3/brada.html">®onglování tøemi ku¾ely - Odkládání ku¾elky na bradu</a></li>
			<li><a href="/kuzely/3/hazenihorem.html">®onglování tøemi ku¾ely - Házení horem</a></li>
			<li><a href="/kuzely/3/helikoptera.html">®onglování tøemi ku¾ely - Helikoptéra</a></li>
			<li><a href="/kuzely/3/jeden-a-pul-otocky.html">®onglování tøemi ku¾ely - Jeden a pùl otoèky</a></li>
			<li><a href="/kuzely/3/kaskada.html">®onglování tøemi ku¾ely - Kaskáda</a></li>
			<li><a href="/kuzely/3/nuzky.html">®onglování tøemi ku¾ely - Nù¾ky</a></li>
			<li><a href="/kuzely/3/podnohou.html">®onglování tøemi ku¾ely - Hození ku¾elu pod nohou</a></li>
			<li><a href="/kuzely/3/pul-otocky.html">®onglování tøemi ku¾ely - Pùl otoèky</a></li>
			<li><a href="/kuzely/3/rybicky.html">®onglování tøemi ku¾ely - Rybièky</a></li>
			<li><a href="/kuzely/3/sekani.html">®onglování tøemi ku¾ely - Sekání (chops)</a></li>
			<li><a href="/kuzely/3/sloupy.html">®onglování tøemi ku¾ely - Sloupy</a></li>
			<li><a href="/kuzely/3/zazady.html">®onglování tøemi ku¾ely - Hození za zády</a></li>
			</ul>
			</li>
			<li><a name="passing"></a><a href="/kuzely/passing/">Passing</a>
			<ul>
			<li><a href="/kuzely/passing/1count.html">Passing - 1 count</a></li>
			<li><a href="/kuzely/passing/2count.html">Passing - 2 count</a></li>
			<li><a href="/kuzely/passing/3count.html">Passing - 3 count</a></li>
			<li><a href="/kuzely/passing/4count.html">Passing - 4 count</a></li>
			<li><a href="/kuzely/passing/7clubs.html">Passing - 7 ku¾elù</a></li>
			<li><a href="/kuzely/passing/all-hands.html">Passing - Passování do v¹echn rukou</a></li>
			<li><a href="/kuzely/passing/around.html">Passing - ®onglování okolo èlovìka</a></li>
			<li><a href="/kuzely/passing/australsky-trik.html">Passing - Australský trik</a></li>
			<li><a href="/kuzely/passing/bostoncircle.html">Passing - Boston circle</a></li>
			<li><a href="/kuzely/passing/box.html">Passing - Ètverec</a></li>
			<li><a href="/kuzely/passing/feeds.html">Passing - Nabíjení</a></li>
			<li><a href="/kuzely/passing/hody.html">Passing - Druhy hodù pøi passování</a></li>
			<li><a href="/kuzely/passing/lichobeznik.html">Passing - Lichobì¾ník</a></li>
			<li><a href="/kuzely/passing/line.html">Passing - Øada</a></li>
			<li><a href="/kuzely/passing/pickup.html">Passing - Zvednutí spadlého ku¾elu</a></li>
			<li><a href="/kuzely/passing/pivo.html">Passing - Passování s pivem</a></li>
			<li><a href="/kuzely/passing/podani-kuzelky.html">Passing - Podání ku¾elky</a></li>
			<li><a href="/kuzely/passing/podnohou.html">Passing - Pass pod nohou</a></li>
			<li><a href="/kuzely/passing/pomala-otocka.html">Passing - Pomalá otoèka</a></li>
			<li><a href="/kuzely/passing/pps.html">Passing - PPS - pass pass self</a></li>
			<li><a href="/kuzely/passing/pravidla.html">Passing - Pravidla passování</a></li>
			<li><a href="/kuzely/passing/prebihani4z11k.html">Passing - Pøebíhání - 11 ku¾elù 4 ¾ongléøi</a></li>
			<li><a href="/kuzely/passing/prebihani5z14k.html">Passing - Pøebíhání - 14 ku¾elù 5 ¾ongléøù</a></li>
			<li><a href="/kuzely/passing/ps.html">Passing - PS - pass self</a></li>
			<li><a href="/kuzely/passing/psspspps.html">Passing - Pass self self pass self pass pass self</a></li>
			<li><a href="/kuzely/passing/rotor.html">Passing - Rotor</a></li>
			<li><a href="/kuzely/passing/runarounds.html">Passing - Obíhání</a></li>
			<li><a href="/kuzely/passing/rychla-otocka.html">Passing - Rychlá otoèka</a></li>
			<li><a href="/kuzely/passing/rypsilon.html">Passing - Rotující Y</a></li>
			<li><a href="/kuzely/passing/sloupy.html">Passing - Sloupy ve dvou</a></li>
			<li><a href="/kuzely/passing/squares.html">Passing - Rotující ètverce</a></li>
			<li><a href="/kuzely/passing/star.html">Passing - Hvìzda</a></li>
			<li><a href="/kuzely/passing/stridavy-lichobeznik.html">Passing - Støídavý lichobì¾ník</a></li>
			<li><a href="/kuzely/passing/synchronizace.html">Passing - Synchronizace</a></li>
			<li><a href="/kuzely/passing/trojuhelnik.html">Passing - Trojúhelník</a></li>
			<li><a href="/kuzely/passing/vymeny.html">Passing - Výmìny ve ètvercích</a></li>
			<li><a href="/kuzely/passing/ypsilon.html">Passing - Ypsilon</a></li>
			<li><a href="/kuzely/passing/zip.html">Passing - Zip</a></li>
			<li><a href="/kuzely/passing/zpozdena-dvojka.html">Passing - Zpo¾dìná dvojka</a></li>
			<li><a href="/kuzely/passing/zrychlena-dvojka.html">Passing - Zrychlená dvojka</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="lide"></a><a href="/lide/">U¾ivatelské úèty</a>
		<ul>
		<li><a href="/lide/pravidla.php">Pravidla pro vytvoøení úètu</a></li>
		<li><a href="/lide/prihlaseni.php">Pøihlá¹ení</a></li>
		<li><a href="/lide/zapomenute-heslo.php">Zapomenuté heslo</a></li>
		</ul>
		</li>
		<li><a name="micky"></a><a href="/micky/">®onglování s míèky</a>
		<ul>
		<li><a href="/micky/balancovani.html">Balancování míèku</a></li>
		<li><a href="/micky/drop.html">Míèky na zemi</a></li>
		<li><a href="/micky/druhy.html">®onglérské míèky</a></li>
		<li><a href="/micky/jak-zacit.html">Jak zaèít ¾onglovat s míèky</a></li>
		<li><a href="/micky/kick-up.html">Zvednutí míèku nohou</a></li>
		<li><a href="/micky/legenda.html">Vysvìtlivky k obrázkùm - míèky</a></li>
		<li><a href="/micky/passing-mm.html">Passing s míèky - mills&#039; mess</a></li>
		<li><a href="/micky/pirueta.html">Pirueta</a></li>
		<li><a href="/micky/poslepu.html">®onglování poslepu</a></li>
		<li><a href="/micky/rady5.html">Jak na ¾onglování s pìti míèky</a></li>
		<li><a href="/micky/sbirani.html">Sbírání spadlých míèkù</a></li>
		<li><a href="/micky/vajicka.html">®onglování s vajíèky</a></li>
		<li><a href="/micky/vyroba.html">Výroba míèkù na ¾onglování</a></li>
			<li><a name="2"></a><a href="/micky/2/">®onglování se dvìma míèky</a>
			<ul>
			<li><a href="/micky/2/2v1.html">®onglování se dvìma míèky - 2 v 1</a></li>
			<li><a href="/micky/2/40303.html">®onglování se dvìma míèky - 40303</a></li>
			<li><a href="/micky/2/501.html">®onglování se dvìma míèky - 501</a></li>
			<li><a href="/micky/2/noha.html">®onglování se dvìma míèky - Prohození míèku pod nohou</a></li>
			<li><a href="/micky/2/zada.html">®onglování se dvìma míèky - Prohození míèku za zády</a></li>
			</ul>
			</li>
			<li><a name="3"></a><a href="/micky/3/">®onglování se tøemi míèky</a>
			<ul>
			<li><a href="/micky/3/1mezi2.html">®onglování se tøemi míèky - Jeden mezi dvìma</a></li>
			<li><a href="/micky/3/1nad2.html">®onglování se tøemi míèky - Jeden nad dvìma</a></li>
			<li><a href="/micky/3/1okolo2.html">®onglování se tøemi míèky - Jeden okolo dvou</a></li>
			<li><a href="/micky/3/3v1.html">®onglování se tøemi míèky - 3 v 1</a></li>
			<li><a href="/micky/3/441.html">®onglování se tøemi míèky - 441</a></li>
			<li><a href="/micky/3/blesk.html">®onglování se tøemi míèky - Blesk</a></li>
			<li><a href="/micky/3/boston-mess.html">®onglování se tøemi míèky - Boston mess</a></li>
			<li><a href="/micky/3/cap.html">®onglování se tøemi míèky - Èáp</a></li>
			<li><a href="/micky/3/celo.html">®onglování se tøemi míèky - Odra¾ení míèku èelem</a></li>
			<li><a href="/micky/3/dvojita-krabice.html">®onglování se tøemi míèky - Dvojitá krabice</a></li>
			<li><a href="/micky/3/dvojite-jojo.html">®onglování se tøemi míèky - Dvojité jo-jo</a></li>
			<li><a href="/micky/3/had.html">®onglování se tøemi míèky - Had</a></li>
			<li><a href="/micky/3/hodiny.html">®onglování se tøemi míèky - Hodiny</a></li>
			<li><a href="/micky/3/jablko.html">®onglování se tøemi míèky - Jezení jablka</a></li>
			<li><a href="/micky/3/jojo.html">®onglování se tøemi míèky - Jo - jo</a></li>
			<li><a href="/micky/3/kaskada-reverzni-siroka.html">®onglování se tøemi míèky - Reverzní kaskáda ¹iroká</a></li>
			<li><a href="/micky/3/kaskada-reverzni.html">®onglování se tøemi míèky - Reverzní kaskáda</a></li>
			<li><a href="/micky/3/kaskada.html">®onglování se tøemi míèky - Kaskáda</a></li>
			<li><a href="/micky/3/klokan.html">®onglování se tøemi míèky - Klokan</a></li>
			<li><a href="/micky/3/koleno.html">®onglování se tøemi míèky - Odra¾ení míèku kolenem</a></li>
			<li><a href="/micky/3/kometa.html">®onglování se tøemi míèky - Kometa</a></li>
			<li><a href="/micky/3/krk.html">®onglování se tøemi míèky - Zachycení míèku za krk</a></li>
			<li><a href="/micky/3/mlyn.html">®onglování se tøemi míèky - Vìtrný mlýn</a></li>
			<li><a href="/micky/3/mm-falesne.html">®onglování se tøemi míèky - Fale¹né mills&#039; mess</a></li>
			<li><a href="/micky/3/mm.html">®onglování se tøemi míèky - Mills&#039; mess</a></li>
			<li><a href="/micky/3/multiplex.html">®onglování se tøemi míèky - Multiplex</a></li>
			<li><a href="/micky/3/nadhlavou.html">®onglování se tøemi míèky - Nad hlavou</a></li>
			<li><a href="/micky/3/neobvykly-zacatek.html">®onglování se tøemi míèky - Neobvyklý zaèátek kaskády</a></li>
			<li><a href="/micky/3/neviditelny.html">®onglování se tøemi míèky - Neviditelný míèek</a></li>
			<li><a href="/micky/3/noha.html">®onglování se tøemi míèky - Prohození míèku pod nohou</a></li>
			<li><a href="/micky/3/oblouky.html">®onglování se tøemi míèky - Oblouèky</a></li>
			<li><a href="/micky/3/ojoj.html">®onglování se tøemi míèky - Oj - oj</a></li>
			<li><a href="/micky/3/okno.html">®onglování se tøemi míèky - Chrámové okno</a></li>
			<li><a href="/micky/3/orangutan.html">®onglování se tøemi míèky - Orangutan</a></li>
			<li><a href="/micky/3/orbit.html">®onglování se tøemi míèky - Orbit</a></li>
			<li><a href="/micky/3/orbit2.html">®onglování se tøemi míèky - Orbit II</a></li>
			<li><a href="/micky/3/osmicka.html">®onglování se tøemi míèky - Osmièka</a></li>
			<li><a href="/micky/3/robot.html">®onglování se tøemi míèky - Robot</a></li>
			<li><a href="/micky/3/seesaw.html">®onglování se tøemi míèky - See saw</a></li>
			<li><a href="/micky/3/sloupy-falesne.html">®onglování se tøemi míèky - Fale¹né sloupy</a></li>
			<li><a href="/micky/3/sloupy.html">®onglování se tøemi míèky - Sloupy</a></li>
			<li><a href="/micky/3/socha.html">®onglování se tøemi míèky - Socha svobody</a></li>
			<li><a href="/micky/3/sprcha-polovicni.html">®onglování se tøemi míèky - Polovièní sprcha</a></li>
			<li><a href="/micky/3/sprcha.html">®onglování se tøemi míèky - Sprcha</a></li>
			<li><a href="/micky/3/tenis-2v1.html">®onglování se tøemi míèky - 2 v 1 tenis</a></li>
			<li><a href="/micky/3/tenis.html">®onglování se tøemi míèky - Tenis</a></li>
			<li><a href="/micky/3/zada.html">®onglování se tøemi míèky - Prohození míèku za zády</a></li>
			<li><a href="/micky/3/zirafa.html">®onglování se tøemi míèky - ®irafa</a></li>
			<li><a href="/micky/3/zkrizene-ruce.html">®onglování se tøemi míèky - Zkøí¾ené ruce</a></li>
			</ul>
			</li>
			<li><a name="4"></a><a href="/micky/4/">®onglování se ètyømi míèky</a>
			<ul>
			<li><a href="/micky/4/55550.html">®onglování se ètyømi míèky - 55550</a></li>
			<li><a href="/micky/4/destnik.html">®onglování se ètyømi míèky - De¹tník</a></li>
			<li><a href="/micky/4/fontana-synchronni.html">®onglování se ètyømi míèky - Synchronní fontána</a></li>
			<li><a href="/micky/4/fontana.html">®onglování se ètyømi míèky - Fontána</a></li>
			<li><a href="/micky/4/krabice.html">®onglování se ètyømi míèky - Krabice</a></li>
			<li><a href="/micky/4/kriz.html">®onglování se ètyømi míèky - Køí¾</a></li>
			<li><a href="/micky/4/sloupy-ii.html">®onglování se ètyømi míèky - Sloupy II</a></li>
			<li><a href="/micky/4/sloupy.html">®onglování se ètyømi míèky - Sloupy</a></li>
			<li><a href="/micky/4/sprcha-polovicni.html">®onglování se ètyømi míèky - Polovièní sprcha</a></li>
			<li><a href="/micky/4/sprcha.html">®onglování se ètyømi míèky - Sprcha</a></li>
			<li><a href="/micky/4/tenis.html">®onglování se ètyømi míèky - Tenis</a></li>
			</ul>
			</li>
			<li><a name="5"></a><a href="/micky/5/">®onglování s pìti míèky</a>
			<ul>
			<li><a href="/micky/5/64.html">®onglování s pìti míèky - 3 + 2</a></li>
			<li><a href="/micky/5/kaskada-multiplex.html">®onglování s pìti míèky - Kaskáda (multiplex)</a></li>
			<li><a href="/micky/5/kaskada-reverzni.html">®onglování s pìti míèky - Reverzní kaskáda</a></li>
			<li><a href="/micky/5/kaskada.html">®onglování s pìti míèky - Kaskáda</a></li>
			<li><a href="/micky/5/sprcha-polovicni.html">®onglování s pìti míèky - Polovièní sprcha</a></li>
			</ul>
			</li>
			<li><a name="6"></a><a href="/micky/6/">®onglování se ¹esti míèky</a>
			
			</li>
		</ul>
		</li>
		<li><a name="obrazky"></a><a href="/obrazky/">Obrázky ¾onglování</a>
		<ul>
		<li><a href="/obrazky/carodejnice-klamovka-2008.html">Èarodìjnice na Klamovce 2008 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/dejvice-20090425.html">Dejvice 25. 4. 2009 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/festival-zonglovani-2007.html">Festival ¾onglování Praha 2007 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/klamovka-20080422.html">Klamovka 22. 4. 2008 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/klamovka-20081105.html">Klamovka 5. 11. 2008 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/klamovka-20091007.html">Klamovka 7. 10. 2009 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/lhotka-20080601.html">Vlakem do Lhotky 2008 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/predvanocni-vystoupeni-klamovka-20081211.html">Pøedvánoèní vystoupení na Klamovce 2008 - obrázky ¾onglování</a></li>
		<li><a href="/obrazky/zidovske-pece-20090404.html">®idovské pece 4. 4. 2009 - obrázky ¾onglování</a></li>
		</ul>
		</li>
		<li><a name="ulita"></a><a href="/ulita/">®onglování v Ulitì</a>
		
		</li>
		<li><a name="video"></a><a href="/video/">®onglérská videa</a>
		<ul>
		<li><a href="/video/4000000-extreme-juggling.html">4,000,000% Extreme Juggling</a></li>
		<li><a href="/video/addicted.html">Addicted</a></li>
		<li><a href="/video/alan-thom-3.html">Alan &amp; Thom #3</a></li>
		<li><a href="/video/all-day-baby.html">All Day Baby!</a></li>
		<li><a href="/video/ball-club-scissors.html">Míèek - ku¾el - nù¾ky</a></li>
		<li><a href="/video/giraffe-theory.html">Giraffe Theory Juggling Glow Clubs</a></li>
		<li><a href="/video/guava-winter-07-08.html">Guava over winter break 07-08</a></li>
		<li><a href="/video/hocus-pocus.html">Hocus Pocus</a></li>
		<li><a href="/video/jen-slaw.html">Jen Slaw Juggling Promo</a></li>
		<li><a href="/video/jeremy-perkins-jeremy-fein.html">Jeremy Perkins and Jeremy Fein Promo 2008</a></li>
		<li><a href="/video/joe-hague.html">Joe Hague Fatboy Slim Juggling Video</a></li>
		<li><a href="/video/jonglage-macabre.html">Jonglage Macabre</a></li>
		<li><a href="/video/juggle-a-saurus.html">Alan &amp; Thom the Fourth</a></li>
		<li><a href="/video/juggling-extravaganza.html">Juggling Extravaganza</a></li>
		<li><a href="/video/laurent-phil.html">Laurent et Phil, juggling passing demo</a></li>
		<li><a href="/video/les-bebes.html">Les Bébés</a></li>
		<li><a href="/video/liquid-crystal-live.html">Matt Hennem - Liquid Crystal live</a></li>
		<li><a href="/video/lost-tapes-minneapolis.html">The Lost Tapes of Minneapolis</a></li>
		<li><a href="/video/more-or-less.html">More or less juggling</a></li>
		<li><a href="/video/prechac-weaves.html">Prechac Weaves</a></li>
		<li><a href="/video/stepz.html">Stepz</a></li>
		<li><a href="/video/take-it-out-3.html">Take It Out 3#</a></li>
		<li><a href="/video/what-the-beepbeep-do-we-know.html">What the (beepbeep) do we know?</a></li>
		<li><a href="/video/yesterday-didnt-happen.html">Yesterday didn&#039;t happen</a></li>
		</ul>
		</li>
		<li><a name="vyhledavani"></a><a href="/vyhledavani/">®onglérùv slabikáø - vyhledávání</a>
		
		</li>
	</ul>
	</li>

</ul>
