<ul>
	<li><a name="top"></a><a href="/">Žonglérův slabikář - žonglování s míčky, kruhy a kužely</a>
	<ul>
	<li><a href="/aczslovnicek.html">Anglicko-český žonglérský slovníček</a></li>
	<li><a href="/changelog.html">Změny v žonglérově slabikáři</a></li>
	<li><a href="/cirkusove-discipliny.html">Cirkusové disciplíny</a></li>
	<li><a href="/doplnky-prohlizece.html">Doplňky do prohlížeče</a></li>
	<li><a href="/druhy-zonglovani.html">Druhy žonglování</a></li>
	<li><a href="/exkurze.html">Náhled do žonglérova slabikáře</a></li>
	<li><a href="/faq.html">Často kladené otázky</a></li>
	<li><a href="/jak-odkazovat.html">Jak odkazovat na žonglérův slabikář</a></li>
	<li><a href="/juggling-tv.html">juggling.tv</a></li>
	<li><a href="/kontakt.html">Kontakt</a></li>
	<li><a href="/literatura.html">Literatura o žonglování</a></li>
	<li><a href="/mobil.html">Žonglérův slabikář v mobilu</a></li>
	<li><a href="/myty-omyly.html">Mýty a omyly</a></li>
	<li><a href="/nacini.html">Žonglérské náčiní</a></li>
	<li><a href="/odkazy.html">Žonglování na síti</a></li>
	<li><a href="/ostatni.html">Další informace o žonglování</a></li>
	<li><a href="/pf-2010.html">PF 2010</a></li>
	<li><a href="/pf-2011.html">PF 2011</a></li>
	<li><a href="/pf-2012.html">PF 2012</a></li>
	<li><a href="/podporte-zongleruv-slabikar.html">Podpořte žonglérův slabikář</a></li>
	<li><a href="/proc-a-jak.html">Proč a jak vznikl žonglérův slabikář</a></li>
	<li><a href="/rec-juggling.html">rec.juggling</a></li>
	<li><a href="/rss.html">RSS kanály</a></li>
	<li><a href="/siteswap.html">Siteswap - popis žonglování pomocí čísel</a></li>
	<li><a href="/software.html">Simulátory žonglování</a></li>
	<li><a href="/sponzori.html">Sponzoři</a></li>
	<li><a href="/statistiky.html">Statistiky</a></li>
	<li><a href="/testovani.html">Automatizované testy</a></li>
	<li><a href="/trenink.html">Trénink</a></li>
	<li><a href="/twitter.html">Twitter - žonglování</a></li>
	<li><a href="/vanoce-2009.html">Veselé Vánoce 2009</a></li>
	<li><a href="/vanoce-2010.html">Veselé Vánoce 2010</a></li>
	<li><a href="/vanoce-2011.html">Veselé Vánoce 2011</a></li>
	<li><a href="/zakladni-pojmy.html">Žonglování - základní pojmy</a></li>
		<li><a name="animace"></a><a href="/animace/">Animace žonglování</a>
		<ul>
			<li><a name="en"></a><a href="/animace/en/">Animace žonglování - anglické názvy</a>
			
			</li>
			<li><a name="siteswap"></a><a href="/animace/siteswap/">Siteswap</a>
			
			</li>
		</ul>
		</li>
		<li><a name="chudy"></a><a href="/chudy/">Chůdy</a>
		
		</li>
		<li><a name="css"></a><a href="/css/">Kaskádové styly</a>
		
		</li>
		<li><a name="diskuse"></a><a href="/diskuse/">Diskuse a komentáře</a>
		
		</li>
		<li><a name="download"></a><a href="/download/">Soubory ke stažení</a>
		<ul>
		<li><a href="/download/epub.html">Soubory ke stažení - epub</a></li>
		<li><a href="/download/exe.html">Soubory ke stažení - exe</a></li>
		<li><a href="/download/licence.html">Licence</a></li>
		<li><a href="/download/mobi.html">Soubory ke stažení - mobi</a></li>
		<li><a href="/download/msi.html">Soubory ke stažení - msi</a></li>
		<li><a href="/download/pdf.html">Soubory ke stažení - pdf</a></li>
		<li><a href="/download/tar.bz2.html">Soubory ke stažení - tar.bz2</a></li>
		</ul>
		</li>
		<li><a name="horoskop"></a><a href="/horoskop/">Horoskop žonglování</a>
		<ul>
			<li><a name="zitra"></a><a href="/horoskop/zitra/">Horoskop žonglování na zítra</a>
			
			</li>
		</ul>
		</li>
		<li><a name="kalendar"></a><a href="/kalendar/">Kalendář žonglování</a>
		
		</li>
		<li><a name="kruhy"></a><a href="/kruhy/">Žonglování s kruhy</a>
		<ul>
		<li><a href="/kruhy/jak-zacit.html">Jak začít žonglovat s kruhy</a></li>
		<li><a href="/kruhy/legenda.html">Vysvětlivky k obrázkům - kruhy</a></li>
		<li><a href="/kruhy/vyroba.html">Výroba kruhů</a></li>
			<li><a name="2"></a>kruhy/2/
			<ul>
			<li><a href="/kruhy/2/2v1.html">Žonglování se dvěma kruhy - 2 v 1</a></li>
			</ul>
			</li>
			<li><a name="3"></a>kruhy/3/
			<ul>
			<li><a href="/kruhy/3/kaskada.html">Žonglování se třemi kruhy - Kaskáda</a></li>
			<li><a href="/kruhy/3/noha.html">Žonglování se třemi kruhy - Prohození kruhu pod nohou</a></li>
			<li><a href="/kruhy/3/sloupy.html">Žonglování se třemi kruhy - Sloupy</a></li>
			</ul>
			</li>
			<li><a name="4"></a><a href="/kruhy/4/">Žonglování s kruhy</a>
			<ul>
			<li><a href="/kruhy/4/fontana.html">Žonglování se čtyřmi kruhy - Fontána</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="kuzely"></a><a href="/kuzely/">Žonglování s kužely</a>
		<ul>
		<li><a href="/kuzely/balanc.html">Balancování kuželu</a></li>
		<li><a href="/kuzely/druhy.html">Druhy kuželů</a></li>
		<li><a href="/kuzely/grip.html">Dva kužely v jedné ruce</a></li>
		<li><a href="/kuzely/headroll.html">Překulení kuželky přes hlavu</a></li>
		<li><a href="/kuzely/jak-zacit.html">Jak začít žonglovat s kužely</a></li>
		<li><a href="/kuzely/kickup.html">Zvednutí kuželu nohou</a></li>
		<li><a href="/kuzely/konstrukce.html">Konstrukce kuželu</a></li>
		<li><a href="/kuzely/legenda.html">Vysvětlivky k obrázkům - kužely</a></li>
		<li><a href="/kuzely/ohen.html">Ohnivé kužely</a></li>
		<li><a href="/kuzely/rotace.html">Rotace kuželu</a></li>
		<li><a href="/kuzely/toceni-okolo-palce.html">Otáčení kuželky okolo palce</a></li>
		<li><a href="/kuzely/vyroba.html">Výroba kuželů</a></li>
			<li><a name="3"></a><a href="/kuzely/3/">Žonglování se třemi kužely</a>
			<ul>
			<li><a href="/kuzely/3/423.html">Žonglování se třemi kužely - 423</a></li>
			<li><a href="/kuzely/3/brada.html">Žonglování se třemi kužely - Odkládání kuželky na bradu</a></li>
			<li><a href="/kuzely/3/hazenihorem.html">Žonglování se třemi kužely - Házení horem</a></li>
			<li><a href="/kuzely/3/helikoptera.html">Žonglování se třemi kužely - Helikoptéra</a></li>
			<li><a href="/kuzely/3/jeden-a-pul-otocky.html">Žonglování se třemi kužely - Jeden a půl otočky</a></li>
			<li><a href="/kuzely/3/kaskada.html">Žonglování se třemi kužely - Kaskáda</a></li>
			<li><a href="/kuzely/3/nuzky.html">Žonglování se třemi kužely - Nůžky</a></li>
			<li><a href="/kuzely/3/podnohou.html">Žonglování se třemi kužely - Hození kuželu pod nohou</a></li>
			<li><a href="/kuzely/3/pul-otocky.html">Žonglování se třemi kužely - Půl otočky</a></li>
			<li><a href="/kuzely/3/rybicky.html">Žonglování se třemi kužely - Rybičky</a></li>
			<li><a href="/kuzely/3/sekani.html">Žonglování se třemi kužely - Sekání (chops)</a></li>
			<li><a href="/kuzely/3/sloupy.html">Žonglování se třemi kužely - Sloupy</a></li>
			<li><a href="/kuzely/3/zazady.html">Žonglování se třemi kužely - Hození za zády</a></li>
			</ul>
			</li>
			<li><a name="passing"></a><a href="/kuzely/passing/">Passing</a>
			<ul>
			<li><a href="/kuzely/passing/1count.html">Passing - 1 count</a></li>
			<li><a href="/kuzely/passing/2count.html">Passing - 2 count</a></li>
			<li><a href="/kuzely/passing/3count.html">Passing - 3 count</a></li>
			<li><a href="/kuzely/passing/4count.html">Passing - 4 count</a></li>
			<li><a href="/kuzely/passing/7clubs.html">Passing - 7 kuželů</a></li>
			<li><a href="/kuzely/passing/all-hands.html">Passing - Passování do všech rukou</a></li>
			<li><a href="/kuzely/passing/around.html">Passing - Žonglování okolo člověka</a></li>
			<li><a href="/kuzely/passing/australsky-trik.html">Passing - Australský trik</a></li>
			<li><a href="/kuzely/passing/bostoncircle.html">Passing - Boston circle</a></li>
			<li><a href="/kuzely/passing/box.html">Passing - Čtverec</a></li>
			<li><a href="/kuzely/passing/feeds.html">Passing - Nabíjení</a></li>
			<li><a href="/kuzely/passing/hody.html">Passing - Druhy hodů při passování</a></li>
			<li><a href="/kuzely/passing/lichobeznik.html">Passing - Lichoběžník</a></li>
			<li><a href="/kuzely/passing/line.html">Passing - Řada</a></li>
			<li><a href="/kuzely/passing/pickup.html">Passing - Zvednutí spadlého kuželu</a></li>
			<li><a href="/kuzely/passing/pivo.html">Passing - Passování s pivem</a></li>
			<li><a href="/kuzely/passing/podani-kuzelky.html">Passing - Podání kuželky</a></li>
			<li><a href="/kuzely/passing/podnohou.html">Passing - Pass pod nohou</a></li>
			<li><a href="/kuzely/passing/pomala-otocka.html">Passing - Pomalá otočka</a></li>
			<li><a href="/kuzely/passing/pps.html">Passing - PPS - pass pass self</a></li>
			<li><a href="/kuzely/passing/pravidla.html">Passing - Pravidla passování</a></li>
			<li><a href="/kuzely/passing/prebihani4z11k.html">Passing - Přebíhání - 11 kuželů 4 žongléři</a></li>
			<li><a href="/kuzely/passing/prebihani5z14k.html">Passing - Přebíhání - 14 kuželů 5 žonglérů</a></li>
			<li><a href="/kuzely/passing/ps.html">Passing - PS - pass self</a></li>
			<li><a href="/kuzely/passing/psspspps.html">Passing - Pass self self pass self pass pass self</a></li>
			<li><a href="/kuzely/passing/rotor.html">Passing - Rotor</a></li>
			<li><a href="/kuzely/passing/runarounds.html">Passing - Obíhání</a></li>
			<li><a href="/kuzely/passing/rychla-otocka.html">Passing - Rychlá otočka</a></li>
			<li><a href="/kuzely/passing/rypsilon.html">Passing - Rotující Y</a></li>
			<li><a href="/kuzely/passing/sloupy.html">Passing - Sloupy ve dvou</a></li>
			<li><a href="/kuzely/passing/squares.html">Passing - Rotující čtverce</a></li>
			<li><a href="/kuzely/passing/star.html">Passing - Hvězda</a></li>
			<li><a href="/kuzely/passing/stridavy-lichobeznik.html">Passing - Střídavý lichoběžník</a></li>
			<li><a href="/kuzely/passing/synchronizace.html">Passing - Synchronizace</a></li>
			<li><a href="/kuzely/passing/trojuhelnik.html">Passing - Trojúhelník</a></li>
			<li><a href="/kuzely/passing/vymeny.html">Passing - Výměny ve čtvercích</a></li>
			<li><a href="/kuzely/passing/ypsilon.html">Passing - Ypsilon</a></li>
			<li><a href="/kuzely/passing/zip.html">Passing - Zip</a></li>
			<li><a href="/kuzely/passing/zpozdena-dvojka.html">Passing - Zpožděná dvojka</a></li>
			<li><a href="/kuzely/passing/zrychlena-dvojka.html">Passing - Zrychlená dvojka</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="lide"></a><a href="/lide/">Seznam žonglérů</a>
		<ul>
		<li><a href="/lide/novy-ucet.php">Založit účet</a></li>
		<li><a href="/lide/pravidla.php">Založit účet</a></li>
			<li><a name="dovednost"></a><a href="/lide/dovednost/">Žongléři podle dovedností</a>
			
			</li>
			<li><a name="misto"></a><a href="/lide/misto/">Žongléři podle místa působení</a>
			
			</li>
			<li><a name="nastaveni"></a><a href="/lide/nastaveni/">Přihlášení</a>
			
			</li>
		</ul>
		</li>
		<li><a name="mapa"></a><a href="/mapa/">Žonglérská mapa</a>
		<ul>
		<li><a href="/mapa/cr.html">Žonglérská mapa - ČR</a></li>
		<li><a href="/mapa/sk.html">Žonglérská mapa - SR</a></li>
		</ul>
		</li>
		<li><a name="micky"></a><a href="/micky/">Žonglování s míčky</a>
		<ul>
		<li><a href="/micky/balancovani.html">Balancování míčku</a></li>
		<li><a href="/micky/drop.html">Míčky na zemi</a></li>
		<li><a href="/micky/druhy.html">Žonglérské míčky</a></li>
		<li><a href="/micky/jak-zacit.html">Jak začít žonglovat s míčky</a></li>
		<li><a href="/micky/kick-up.html">Zvednutí míčku nohou</a></li>
		<li><a href="/micky/legenda.html">Vysvětlivky k obrázkům - míčky</a></li>
		<li><a href="/micky/nohy.html">Použij nohy</a></li>
		<li><a href="/micky/passing-mm.html">Passing s míčky - mills&#039; mess</a></li>
		<li><a href="/micky/pirueta.html">Pirueta</a></li>
		<li><a href="/micky/poslepu.html">Žonglování poslepu</a></li>
		<li><a href="/micky/rady5.html">Jak na žonglování s pěti míčky</a></li>
		<li><a href="/micky/sbirani.html">Sbírání spadlých míčků</a></li>
		<li><a href="/micky/vajicka.html">Žonglování s vajíčky</a></li>
		<li><a href="/micky/vyroba-balonky.html">Míček z balónků</a></li>
		<li><a href="/micky/vyroba-tenisak.html">Míček z tenisáku</a></li>
		<li><a href="/micky/vyroba.html">Výroba míčků na žonglování</a></li>
			<li><a name="2"></a><a href="/micky/2/">Žonglování se dvěma míčky</a>
			<ul>
			<li><a href="/micky/2/2v1.html">Žonglování se dvěma míčky - 2 v 1</a></li>
			<li><a href="/micky/2/40303.html">Žonglování se dvěma míčky - 40303</a></li>
			<li><a href="/micky/2/501.html">Žonglování se dvěma míčky - 501</a></li>
			<li><a href="/micky/2/noha.html">Žonglování se dvěma míčky - Prohození míčku pod nohou</a></li>
			<li><a href="/micky/2/zada.html">Žonglování se dvěma míčky - Prohození míčku za zády</a></li>
			</ul>
			</li>
			<li><a name="3"></a><a href="/micky/3/">Žonglování se třemi míčky</a>
			<ul>
			<li><a href="/micky/3/1mezi2.html">Žonglování se třemi míčky - Jeden mezi dvěma</a></li>
			<li><a href="/micky/3/1nad2.html">Žonglování se třemi míčky - Jeden nad dvěma</a></li>
			<li><a href="/micky/3/1okolo2.html">Žonglování se třemi míčky - Jeden okolo dvou</a></li>
			<li><a href="/micky/3/3v1.html">Žonglování se třemi míčky - 3 v 1</a></li>
			<li><a href="/micky/3/441.html">Žonglování se třemi míčky - 441</a></li>
			<li><a href="/micky/3/blesk.html">Žonglování se třemi míčky - Blesk</a></li>
			<li><a href="/micky/3/boston-mess.html">Žonglování se třemi míčky - Boston mess</a></li>
			<li><a href="/micky/3/cap.html">Žonglování se třemi míčky - Čáp</a></li>
			<li><a href="/micky/3/celo.html">Žonglování se třemi míčky - Odražení míčku čelem</a></li>
			<li><a href="/micky/3/dvojita-krabice.html">Žonglování se třemi míčky - Dvojitá krabice</a></li>
			<li><a href="/micky/3/dvojite-jojo.html">Žonglování se třemi míčky - Dvojité jo-jo</a></li>
			<li><a href="/micky/3/had.html">Žonglování se třemi míčky - Had</a></li>
			<li><a href="/micky/3/hodiny.html">Žonglování se třemi míčky - Hodiny</a></li>
			<li><a href="/micky/3/jablko.html">Žonglování se třemi míčky - Jedení jablka</a></li>
			<li><a href="/micky/3/jojo.html">Žonglování se třemi míčky - Jo - jo</a></li>
			<li><a href="/micky/3/kaskada-reverzni-siroka.html">Žonglování se třemi míčky - Reverzní kaskáda široká</a></li>
			<li><a href="/micky/3/kaskada-reverzni.html">Žonglování se třemi míčky - Reverzní kaskáda</a></li>
			<li><a href="/micky/3/kaskada.html">Žonglování se třemi míčky - Kaskáda</a></li>
			<li><a href="/micky/3/klokan.html">Žonglování se třemi míčky - Klokan</a></li>
			<li><a href="/micky/3/koleno.html">Žonglování se třemi míčky - Odražení míčku kolenem</a></li>
			<li><a href="/micky/3/kometa.html">Žonglování se třemi míčky - Kometa</a></li>
			<li><a href="/micky/3/krk.html">Žonglování se třemi míčky - Zachycení míčku za krk</a></li>
			<li><a href="/micky/3/mlyn.html">Žonglování se třemi míčky - Větrný mlýn</a></li>
			<li><a href="/micky/3/mm-falesne.html">Žonglování se třemi míčky - Falešné Mills&#039; mess</a></li>
			<li><a href="/micky/3/mm.html">Žonglování se třemi míčky - Mills&#039; mess</a></li>
			<li><a href="/micky/3/multiplex.html">Žonglování se třemi míčky - Multiplex</a></li>
			<li><a href="/micky/3/nadhlavou.html">Žonglování se třemi míčky - Nad hlavou</a></li>
			<li><a href="/micky/3/neobvykly-zacatek.html">Žonglování se třemi míčky - Neobvyklý začátek kaskády</a></li>
			<li><a href="/micky/3/neviditelny.html">Žonglování se třemi míčky - Neviditelný míček</a></li>
			<li><a href="/micky/3/noha.html">Žonglování se třemi míčky - Prohození míčku pod nohou</a></li>
			<li><a href="/micky/3/oblouky.html">Žonglování se třemi míčky - Obloučky</a></li>
			<li><a href="/micky/3/ojoj.html">Žonglování se třemi míčky - Oj - oj</a></li>
			<li><a href="/micky/3/okno.html">Žonglování se třemi míčky - Chrámové okno</a></li>
			<li><a href="/micky/3/orangutan.html">Žonglování se třemi míčky - Orangutan</a></li>
			<li><a href="/micky/3/orbit.html">Žonglování se třemi míčky - Orbit</a></li>
			<li><a href="/micky/3/orbit2.html">Žonglování se třemi míčky - Orbit II</a></li>
			<li><a href="/micky/3/osmicka.html">Žonglování se třemi míčky - Osmička</a></li>
			<li><a href="/micky/3/robot.html">Žonglování se třemi míčky - Robot</a></li>
			<li><a href="/micky/3/seesaw.html">Žonglování se třemi míčky - See saw</a></li>
			<li><a href="/micky/3/sloupy-falesne.html">Žonglování se třemi míčky - Falešné sloupy</a></li>
			<li><a href="/micky/3/sloupy.html">Žonglování se třemi míčky - Sloupy</a></li>
			<li><a href="/micky/3/socha.html">Žonglování se třemi míčky - Socha svobody</a></li>
			<li><a href="/micky/3/sprcha-polovicni.html">Žonglování se třemi míčky - Poloviční sprcha</a></li>
			<li><a href="/micky/3/sprcha.html">Žonglování se třemi míčky - Sprcha</a></li>
			<li><a href="/micky/3/tenis-2v1.html">Žonglování se třemi míčky - 2 v 1 tenis</a></li>
			<li><a href="/micky/3/tenis.html">Žonglování se třemi míčky - Tenis</a></li>
			<li><a href="/micky/3/zada.html">Žonglování se třemi míčky - Prohození míčku za zády</a></li>
			<li><a href="/micky/3/zirafa.html">Žonglování se třemi míčky - Žirafa</a></li>
			<li><a href="/micky/3/zkrizene-ruce.html">Žonglování se třemi míčky - Zkřížené ruce</a></li>
			</ul>
			</li>
			<li><a name="4"></a><a href="/micky/4/">Žonglování se čtyřmi míčky</a>
			<ul>
			<li><a href="/micky/4/55550.html">Žonglování se čtyřmi míčky - 55550</a></li>
			<li><a href="/micky/4/destnik.html">Žonglování se čtyřmi míčky - Deštník</a></li>
			<li><a href="/micky/4/fontana-synchronni.html">Žonglování se čtyřmi míčky - Synchronní fontána</a></li>
			<li><a href="/micky/4/fontana.html">Žonglování se čtyřmi míčky - Fontána</a></li>
			<li><a href="/micky/4/krabice.html">Žonglování se čtyřmi míčky - Krabice</a></li>
			<li><a href="/micky/4/kriz.html">Žonglování se čtyřmi míčky - Kříž</a></li>
			<li><a href="/micky/4/sloupy-ii.html">Žonglování se čtyřmi míčky - Sloupy II</a></li>
			<li><a href="/micky/4/sloupy.html">Žonglování se čtyřmi míčky - Sloupy</a></li>
			<li><a href="/micky/4/sprcha-polovicni.html">Žonglování se čtyřmi míčky - Poloviční sprcha</a></li>
			<li><a href="/micky/4/sprcha.html">Žonglování se čtyřmi míčky - Sprcha</a></li>
			<li><a href="/micky/4/tenis.html">Žonglování se čtyřmi míčky - Tenis</a></li>
			</ul>
			</li>
			<li><a name="5"></a><a href="/micky/5/">Žonglování s pěti míčky</a>
			<ul>
			<li><a href="/micky/5/64.html">Žonglování s pěti míčky - 3 + 2</a></li>
			<li><a href="/micky/5/kaskada-multiplex.html">Žonglování s pěti míčky - Kaskáda (multiplex)</a></li>
			<li><a href="/micky/5/kaskada-reverzni.html">Žonglování s pěti míčky - Reverzní kaskáda</a></li>
			<li><a href="/micky/5/kaskada.html">Žonglování s pěti míčky - Kaskáda</a></li>
			<li><a href="/micky/5/sprcha-polovicni.html">Žonglování s pěti míčky - Poloviční sprcha</a></li>
			</ul>
			</li>
			<li><a name="6"></a><a href="/micky/6/">Žonglování se šesti míčky</a>
			
			</li>
		</ul>
		</li>
		<li><a name="navody"></a><a href="/navody/">Návody na žonglování</a>
		
		</li>
		<li><a name="novinky"></a><a href="/novinky/">Novinky</a>
		
		</li>
		<li><a name="obrazky"></a><a href="/obrazky/">Obrázky žonglování</a>
		<ul>
			<li><a name="berlin-juggling-convention-20110625"></a><a href="/obrazky/berlin-juggling-convention-20110625/">Berlin Juggling Convention 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="bigoudn-jongle-20110714"></a><a href="/obrazky/bigoudn-jongle-20110714/">Bigoud’n Jongle 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="carodejnice-klamovka-20080422"></a><a href="/obrazky/carodejnice-klamovka-20080422/">Čarodějnice na Klamovce 2008 - obrázky žonglování</a>
			
			</li>
			<li><a name="dejvice-20090425"></a><a href="/obrazky/dejvice-20090425/">Dejvice 25. 4. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="den-zonglovani-ujc-rosice-u-brna-20090606"></a><a href="/obrazky/den-zonglovani-ujc-rosice-u-brna-20090606/">Den žonglování s Ultimate Juggling Squad - obrázky žonglování</a>
			
			</li>
			<li><a name="den-zonglovani-ujs-ii-20100904"></a><a href="/obrazky/den-zonglovani-ujs-ii-20100904/">Den žonglování s UJS vol. 2 - obrázky žonglování</a>
			
			</li>
			<li><a name="drazdany-20110312"></a><a href="/obrazky/drazdany-20110312/">Dresdner Jonglierfest 12. 3. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="drazdany-20110313"></a><a href="/obrazky/drazdany-20110313/">Dresdner Jonglierfest 13. 3. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc-20100801"></a><a href="/obrazky/ejc-20100801/">EJC 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc11-20110806"></a><a href="/obrazky/ejc11-20110806/">EJC 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc11-galashow-20110812"></a><a href="/obrazky/ejc11-galashow-20110812/">EJC galashow 12. 8. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc11-program-20110805"></a><a href="/obrazky/ejc11-program-20110805/">EJC 2011 - program - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc11-shake-that-20110811"></a><a href="/obrazky/ejc11-shake-that-20110811/">Shake That 14. 8. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ejc11-tiskoviny-20110805"></a><a href="/obrazky/ejc11-tiskoviny-20110805/">EJC 2011 - tiskoviny - obrázky žonglování</a>
			
			</li>
			<li><a name="festival-zonglovani-20070713"></a><a href="/obrazky/festival-zonglovani-20070713/">Festival žonglování Praha 2007 - obrázky žonglování</a>
			
			</li>
			<li><a name="klamovka-20080422"></a><a href="/obrazky/klamovka-20080422/">Klamovka 22. 4. 2008 - obrázky žonglování</a>
			
			</li>
			<li><a name="klamovka-20081105"></a><a href="/obrazky/klamovka-20081105/">Klamovka 5. 11. 2008 - obrázky žonglování</a>
			
			</li>
			<li><a name="klamovka-20091007"></a><a href="/obrazky/klamovka-20091007/">Klamovka 7. 10. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ledce-rozmaryna-20100612"></a><a href="/obrazky/ledce-rozmaryna-20100612/">Ledce voní Rozmarýnou 12. 6. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="lhotka-20080601"></a><a href="/obrazky/lhotka-20080601/">Vlakem do Lhotky 2008 - obrázky žonglování</a>
			
			</li>
			<li><a name="oslavy-dne-evropy-zamek-rosice-20080510"></a><a href="/obrazky/oslavy-dne-evropy-zamek-rosice-20080510/">Oslavy dne evropy - zámek Rosice - obrázky žonglování</a>
			
			</li>
			<li><a name="prazsky-zonglersky-marathon-2-20101113"></a><a href="/obrazky/prazsky-zonglersky-marathon-2-20101113/">Pražský žonglérský marathon 2 - obrázky žonglování</a>
			
			</li>
			<li><a name="prazsky-zonglersky-marathon-2-honzuv-vyber-20101113"></a><a href="/obrazky/prazsky-zonglersky-marathon-2-honzuv-vyber-20101113/">Pražský žonglérský marathon 2 - Honzův výběr - obrázky žonglování</a>
			
			</li>
			<li><a name="prazsky-zonglersky-marathon-2-souteze-a-vystoupeni-20101113"></a><a href="/obrazky/prazsky-zonglersky-marathon-2-souteze-a-vystoupeni-20101113/">Pražsky žonglérský marathon 2 - soutěže a vystoupení - obrázky žonglování</a>
			
			</li>
			<li><a name="prazsky-zonglersky-marathon-20091128"></a><a href="/obrazky/prazsky-zonglersky-marathon-20091128/">Pražský žonglérský marathon 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="predvanocni-vystoupeni-klamovka-20081211"></a><a href="/obrazky/predvanocni-vystoupeni-klamovka-20081211/">Předvánoční vystoupení na Klamovce 2008 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20091018"></a><a href="/obrazky/ulita-20091018/">Ulita 18. 10. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20091101"></a><a href="/obrazky/ulita-20091101/">Ulita 1. 11. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20091115"></a><a href="/obrazky/ulita-20091115/">Ulita 15. 11. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20091129"></a><a href="/obrazky/ulita-20091129/">Ulita 29. 11. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20091213"></a><a href="/obrazky/ulita-20091213/">Ulita 13. 12. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100110"></a><a href="/obrazky/ulita-20100110/">Ulita 10. 1. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100124"></a><a href="/obrazky/ulita-20100124/">Ulita 24. 1. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100207"></a><a href="/obrazky/ulita-20100207/">Ulita 7. 2. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100221"></a><a href="/obrazky/ulita-20100221/">Ulita 21. 2. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100307"></a><a href="/obrazky/ulita-20100307/">Ulita 7. 3. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100321"></a><a href="/obrazky/ulita-20100321/">Ulita 21. 3. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20100411"></a><a href="/obrazky/ulita-20100411/">Ulita 11. 4. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20101003"></a><a href="/obrazky/ulita-20101003/">Ulita 3. 10. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20101017"></a><a href="/obrazky/ulita-20101017/">Ulita 17. 10. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20101031"></a><a href="/obrazky/ulita-20101031/">Ulita 31. 10. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20101114"></a><a href="/obrazky/ulita-20101114/">Ulita 14. 11. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20101121"></a><a href="/obrazky/ulita-20101121/">Ulita 21. 11. 2010 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20110116"></a><a href="/obrazky/ulita-20110116/">Ulita 16. 1. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20110213"></a><a href="/obrazky/ulita-20110213/">Ulita 13. 2. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20110227"></a><a href="/obrazky/ulita-20110227/">Ulita 27. 2. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20110306"></a><a href="/obrazky/ulita-20110306/">Ulita 6. 3. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20110320"></a><a href="/obrazky/ulita-20110320/">Ulita 20. 3. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20111009"></a><a href="/obrazky/ulita-20111009/">Ulita 9. 10. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20111030"></a><a href="/obrazky/ulita-20111030/">Ulita 30. 10. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20111113"></a><a href="/obrazky/ulita-20111113/">Ulita 13. 11. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20111204"></a><a href="/obrazky/ulita-20111204/">Ulita 4. 12. 2011 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20120115"></a><a href="/obrazky/ulita-20120115/">Ulita 15. 1. 2012 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-20120205"></a><a href="/obrazky/ulita-20120205/">Ulita 5. 2. 2012 - obrázky žonglování</a>
			
			</li>
			<li><a name="ulita-zbynkuv-vyber-20100312"></a><a href="/obrazky/ulita-zbynkuv-vyber-20100312/">Ulita - Zbyňkův výběr - obrázky žonglování</a>
			
			</li>
			<li><a name="vsezonglersky-slet-20120129"></a><a href="/obrazky/vsezonglersky-slet-20120129/">Všežonglérský slet 29. 1. 2012 - obrázky žonglování</a>
			
			</li>
			<li><a name="zidovske-pece-20090404"></a><a href="/obrazky/zidovske-pece-20090404/">Židovské pece 4. 4. 2009 - obrázky žonglování</a>
			
			</li>
			<li><a name="zongleruv-slabikar-na-papire-20111218"></a><a href="/obrazky/zongleruv-slabikar-na-papire-20111218/">Žonglérův slabikář na papíře - obrázky žonglování</a>
			
			</li>
			<li><a name="zonglparty-20110528"></a><a href="/obrazky/zonglparty-20110528/">Žonglpárty 28. 5. 2011 - obrázky žonglování</a>
			
			</li>
		</ul>
		</li>
		<li><a name="obrazky-na-plochu"></a><a href="/obrazky-na-plochu/">Obrázky na plochu</a>
		
		</li>
		<li><a name="rss"></a><a href="/rss/">Novinky</a>
		
		</li>
		<li><a name="scripts"></a><a href="/scripts/">Skripty</a>
		
		</li>
		<li><a name="tip"></a><a href="/tip/">Žonglérský tip týdne</a>
		
		</li>
		<li><a name="ulita"></a><a href="/ulita/">Žonglování v Ulitě</a>
		<ul>
		<li><a href="/ulita/cesta.html">Jak se dostat do Ulity</a></li>
		<li><a href="/ulita/en.html">Juggling at Ulita</a></li>
		</ul>
		</li>
		<li><a name="video"></a><a href="/video/">Žonglérská videa</a>
		<ul>
		<li><a href="/video/3-play-in-prague.html">3 play in Prague</a></li>
		<li><a href="/video/4000000-extreme-juggling.html">4,000,000% Extreme Juggling</a></li>
		<li><a href="/video/a-new-ratio.html">A New Ratio</a></li>
		<li><a href="/video/addicted.html">Addicted</a></li>
		<li><a href="/video/alan-thom-3.html">Alan &amp; Thom #3</a></li>
		<li><a href="/video/all-day-baby.html">All Day Baby!</a></li>
		<li><a href="/video/balance-tricks-2.html">Balancování kuželů</a></li>
		<li><a href="/video/ball-club-scissors.html">Míček - kužel - nůžky</a></li>
		<li><a href="/video/bratri-v-tricku-2.html">Bratři v tricku 2</a></li>
		<li><a href="/video/bratri-v-tricku-training-day.html">Bratři v tricku - trénink</a></li>
		<li><a href="/video/bratri-v-tricku.html">Bratři v tricku</a></li>
		<li><a href="/video/c2laballe-0707.html">C2laballe 0707</a></li>
		<li><a href="/video/club2ring.html">Bláznivá žehlička</a></li>
		<li><a href="/video/don-texas.html">Don Texas</a></li>
		<li><a href="/video/giraffe-theory.html">Giraffe Theory Juggling Glow Clubs</a></li>
		<li><a href="/video/guava-winter-07-08.html">Guava over winter break 07-08</a></li>
		<li><a href="/video/heroes.html">Heroes</a></li>
		<li><a href="/video/hocus-pocus.html">Hocus Pocus</a></li>
		<li><a href="/video/interrobang.html">Interrobang</a></li>
		<li><a href="/video/ivy-and-gold.html">Ivy and Gold</a></li>
		<li><a href="/video/jade-dussault.html">Hula Hoop - Jade Dussault</a></li>
		<li><a href="/video/jeff-wes.html">Jeff Lutkus &amp; Wes Peden</a></li>
		<li><a href="/video/jen-slaw.html">Jen Slaw Juggling Promo</a></li>
		<li><a href="/video/jeremy-perkins-jeremy-fein.html">Jeremy Perkins and Jeremy Fein Promo 2008</a></li>
		<li><a href="/video/joe-hague.html">Joe Hague Fatboy Slim Juggling Video</a></li>
		<li><a href="/video/jonglage-macabre.html">Jonglage Macabre</a></li>
		<li><a href="/video/juggle-a-saurus.html">Alan &amp; Thom the Fourth</a></li>
		<li><a href="/video/juggling-extravaganza.html">Juggling Extravaganza</a></li>
		<li><a href="/video/klamovka.html">Žongléři z Klamovky</a></li>
		<li><a href="/video/kopie.html">копия</a></li>
		<li><a href="/video/laurent-phil.html">Laurent et Phil, juggling passing demo</a></li>
		<li><a href="/video/les-bebes.html">Les Bébés</a></li>
		<li><a href="/video/liquid-crystal-live.html">Matt Hennem - Liquid Crystal live</a></li>
		<li><a href="/video/lost-tapes-minneapolis.html">The Lost Tapes of Minneapolis</a></li>
		<li><a href="/video/minimal-juggling.html">Minimal juggling</a></li>
		<li><a href="/video/more-or-less.html">More or less juggling</a></li>
		<li><a href="/video/neta-oren.html">Neta Oren</a></li>
		<li><a href="/video/passing-zone.html">The Passing Zone</a></li>
		<li><a href="/video/prechac-juggling-in-berlin.html">Prechac Juggling in Berlin</a></li>
		<li><a href="/video/prechac-weaves.html">Prechac Weaves</a></li>
		<li><a href="/video/readingroundabouts.html">Reading Roundabouts</a></li>
		<li><a href="/video/roucoulette-sauce-poisson.html">Roucoulette sauce poisson</a></li>
		<li><a href="/video/shake-that.html">Shake That</a></li>
		<li><a href="/video/stepz.html">Stepz</a></li>
		<li><a href="/video/sun.html">Sluníčko</a></li>
		<li><a href="/video/take-it-out-3.html">Take It Out 3#</a></li>
		<li><a href="/video/the-day-after-yesterday.html">The day after yesterday</a></li>
		<li><a href="/video/triangles.html">Triangles</a></li>
		<li><a href="/video/trouble.html">Trouble</a></li>
		<li><a href="/video/what-the-beepbeep-do-we-know.html">What the (beepbeep) do we know?</a></li>
		<li><a href="/video/whirlcool.html">Whirlcool</a></li>
		<li><a href="/video/white-balance.html">White Balance</a></li>
		<li><a href="/video/yesterday-didnt-happen.html">Yesterday didn&#039;t happen</a></li>
			<li><a name="metlili"></a><a href="/video/metlili/">Metlili</a>
			<ul>
			<li><a href="/video/metlili/conctabong.html">Conctabong</a></li>
			<li><a href="/video/metlili/facundo-sacramento.html">Facundo Sacramento</a></li>
			<li><a href="/video/metlili/fantasmatico.html">Fantasmatico</a></li>
			<li><a href="/video/metlili/h2o-flavor.html">H2O Flavor</a></li>
			<li><a href="/video/metlili/latin-objects-3-1.html">Latin objects 3.1</a></li>
			<li><a href="/video/metlili/latin-objects-4.html">Latin objects 4</a></li>
			<li><a href="/video/metlili/latin-objects-5-1.html">Latin objects 5.1</a></li>
			<li><a href="/video/metlili/latin-objects-6.html">Latin objects 6</a></li>
			<li><a href="/video/metlili/mantega-variation.html">Mantega Variation</a></li>
			<li><a href="/video/metlili/semaforo-compilacion-2.html">Semaforo compilacion 2</a></li>
			<li><a href="/video/metlili/smodje1.html">Smodje 1</a></li>
			</ul>
			</li>
			<li><a name="navod"></a><a href="/video/navod/">Triky ze žonglérova slabikáře</a>
			<ul>
			<li><a href="/video/navod/info.html">Video návody</a></li>
			<li><a href="/video/navod/kuzely-3-423-palec.html">423 – točení okolo palce</a></li>
			<li><a href="/video/navod/kuzely-3-423-pretoceni.html">423 – přetočení kuželu</a></li>
			<li><a href="/video/navod/kuzely-3-423.html">423</a></li>
			<li><a href="/video/navod/kuzely-3-brada.html">Kužel na bradě</a></li>
			<li><a href="/video/navod/kuzely-3-hazeni-horem.html">Házení horem</a></li>
			<li><a href="/video/navod/kuzely-3-helikoptera.html">Helikoptéra</a></li>
			<li><a href="/video/navod/kuzely-3-jeden-a-pul-otocky.html">Jeden a půl otočky</a></li>
			<li><a href="/video/navod/kuzely-3-kaskada-navod.html">Kaskáda s kužely</a></li>
			<li><a href="/video/navod/kuzely-3-nuzky.html">Nůžky</a></li>
			<li><a href="/video/navod/kuzely-3-pod-nohou.html">Kužel pod nohou</a></li>
			<li><a href="/video/navod/kuzely-3-prekuleni-kuzelky-pres-hlavu.html">Kuželka přes hlavu</a></li>
			<li><a href="/video/navod/kuzely-3-pul-otocky-pretaceni.html">Přetáčení půl otočky</a></li>
			<li><a href="/video/navod/kuzely-3-pul-otocky.html">Půl otočky</a></li>
			<li><a href="/video/navod/kuzely-3-reverzni-sekani.html">Reverzní sekání</a></li>
			<li><a href="/video/navod/kuzely-3-rybicky.html">Rybičky</a></li>
			<li><a href="/video/navod/kuzely-3-sekani.html">Sekání</a></li>
			<li><a href="/video/navod/kuzely-3-sloupy.html">Sloupy s kužely</a></li>
			<li><a href="/video/navod/kuzely-3-zvednuti-kuzelu-nohou.html">Zvednutí kuželu</a></li>
			<li><a href="/video/navod/kuzely-dve-otocky.html">Dvě otočky</a></li>
			<li><a href="/video/navod/kuzely-jedna-otocka.html">Jedna otočka</a></li>
			<li><a href="/video/navod/kuzely-passing-2count.html">2 count</a></li>
			<li><a href="/video/navod/kuzely-passing-3count.html">3 count</a></li>
			<li><a href="/video/navod/kuzely-passing-4count.html">4 count</a></li>
			<li><a href="/video/navod/kuzely-passing-australsky-trik.html">Australský trik</a></li>
			<li><a href="/video/navod/kuzely-passing-okolo-cloveka.html">Passing okolo člověka</a></li>
			<li><a href="/video/navod/kuzely-passing-pps.html">Pass pass self</a></li>
			<li><a href="/video/navod/kuzely-toceni-okolo-palce.html">Okolo palce</a></li>
			<li><a href="/video/navod/kuzely-tri-otocky.html">Tři otočky</a></li>
			<li><a href="/video/navod/micky-1-prehazovani.html">Jeden míček</a></li>
			<li><a href="/video/navod/micky-2-2v1.html">Dva v jedné</a></li>
			<li><a href="/video/navod/micky-2-40303.html">40303</a></li>
			<li><a href="/video/navod/micky-2-501.html">501</a></li>
			<li><a href="/video/navod/micky-2-noha.html">Pod nohou</a></li>
			<li><a href="/video/navod/micky-2-prehazovani.html">Dva míčky</a></li>
			<li><a href="/video/navod/micky-2-zada.html">Za zády</a></li>
			<li><a href="/video/navod/micky-3-3v1.html">Tři míčky v jedné ruce</a></li>
			<li><a href="/video/navod/micky-3-441.html">441</a></li>
			<li><a href="/video/navod/micky-3-balancovani-micku-na-hlave.html">Balancování míčku</a></li>
			<li><a href="/video/navod/micky-3-blesk.html">Blesk</a></li>
			<li><a href="/video/navod/micky-3-boston-mess.html">Boston mess</a></li>
			<li><a href="/video/navod/micky-3-cap.html">Čáp</a></li>
			<li><a href="/video/navod/micky-3-celo.html">Odrážení čelem</a></li>
			<li><a href="/video/navod/micky-3-chramove-okno.html">Chrámové okno</a></li>
			<li><a href="/video/navod/micky-3-dva-okolo-jednoho.html">Dva okolo jednoho</a></li>
			<li><a href="/video/navod/micky-3-dvojita-krabice.html">Dvojitá krabice</a></li>
			<li><a href="/video/navod/micky-3-dvojite-jojo.html">Dvojité jo-jo</a></li>
			<li><a href="/video/navod/micky-3-falesne-sloupy.html">Falešné sloupy</a></li>
			<li><a href="/video/navod/micky-3-had.html">Had</a></li>
			<li><a href="/video/navod/micky-3-jablko.html">Jedení jablka</a></li>
			<li><a href="/video/navod/micky-3-jeden-mezi-dvema.html">Jeden míček mezi dvěma</a></li>
			<li><a href="/video/navod/micky-3-jeden-nad-dvema.html">Jeden míček nad dvěma</a></li>
			<li><a href="/video/navod/micky-3-jeden-okolo-dvou.html">Míček okolo dvou</a></li>
			<li><a href="/video/navod/micky-3-jeden-okolo-dvou2.html">Jeden míček okolo dvou</a></li>
			<li><a href="/video/navod/micky-3-jojo.html">Jo-jo</a></li>
			<li><a href="/video/navod/micky-3-kaskada-reverzni.html">Reverzní kaskáda</a></li>
			<li><a href="/video/navod/micky-3-kaskada.html">Kaskáda</a></li>
			<li><a href="/video/navod/micky-3-kick-up.html">Kickup – míček</a></li>
			<li><a href="/video/navod/micky-3-klokan.html">Klokan</a></li>
			<li><a href="/video/navod/micky-3-koleno.html">Koleno</a></li>
			<li><a href="/video/navod/micky-3-krabice.html">Krabice</a></li>
			<li><a href="/video/navod/micky-3-mlyn.html">Větrný mlýn</a></li>
			<li><a href="/video/navod/micky-3-mm-falesne.html">Falešné mills&#039; mess</a></li>
			<li><a href="/video/navod/micky-3-mm.html">Mills&#039; mess</a></li>
			<li><a href="/video/navod/micky-3-multiplex.html">Multiplex</a></li>
			<li><a href="/video/navod/micky-3-na-hlave.html">Míček na hlavě</a></li>
			<li><a href="/video/navod/micky-3-nad-hlavou.html">Nad hlavou</a></li>
			<li><a href="/video/navod/micky-3-obloucky.html">Obloučky</a></li>
			<li><a href="/video/navod/micky-3-orangutan.html">Orangutan</a></li>
			<li><a href="/video/navod/micky-3-osmicka.html">Osmička</a></li>
			<li><a href="/video/navod/micky-3-pod-nohou.html">Pod nohou</a></li>
			<li><a href="/video/navod/micky-3-polovicni-sprcha.html">Poloviční sprcha</a></li>
			<li><a href="/video/navod/micky-3-poslepu.html">Poslepu</a></li>
			<li><a href="/video/navod/micky-3-reverzni-kaskada-siroka.html">Široká reverzní kaskáda</a></li>
			<li><a href="/video/navod/micky-3-robot.html">Robot</a></li>
			<li><a href="/video/navod/micky-3-sloupy.html">Sloupy</a></li>
			<li><a href="/video/navod/micky-3-sprcha.html">Sprcha</a></li>
			<li><a href="/video/navod/micky-3-tenis-2v1.html">Tenis 2v1</a></li>
			<li><a href="/video/navod/micky-3-tenis.html">Tenis</a></li>
			<li><a href="/video/navod/micky-3-vajicka.html">Žonglování s vajíčky</a></li>
			<li><a href="/video/navod/micky-3-za-krk.html">Krk</a></li>
			<li><a href="/video/navod/micky-3-za-zady.html">Za zády</a></li>
			<li><a href="/video/navod/micky-3-zacatek1.html">Začátek kaskády 1</a></li>
			<li><a href="/video/navod/micky-3-zacatek2.html">Začátek kaskády 2</a></li>
			<li><a href="/video/navod/micky-3-zacatek3.html">Začátek kaskády 3</a></li>
			<li><a href="/video/navod/micky-3-zacatek4.html">Začátek kaskády 4</a></li>
			<li><a href="/video/navod/micky-3-zacatek5.html">Začátek kaskády 5</a></li>
			<li><a href="/video/navod/micky-3-zirafa.html">Žirafa</a></li>
			<li><a href="/video/navod/micky-3-zkrizene-ruce-prechod.html">Zkřížené ruce - přechod</a></li>
			<li><a href="/video/navod/micky-3-zkrizene-ruce.html">Zkřížené ruce</a></li>
			<li><a href="/video/navod/micky-3-zvednuti-spadleho-micku.html">Zvednutí spadlého míčku</a></li>
			<li><a href="/video/navod/micky-4-55550.html">55550</a></li>
			<li><a href="/video/navod/micky-4-destnik.html">Deštník</a></li>
			<li><a href="/video/navod/micky-4-fontana-s.html">Synchronní fontána</a></li>
			<li><a href="/video/navod/micky-4-fontana.html">Fontána</a></li>
			<li><a href="/video/navod/micky-4-krabice.html">Krabice - 4 míčky</a></li>
			<li><a href="/video/navod/micky-4-kriz.html">Kříž</a></li>
			<li><a href="/video/navod/micky-4-polovicni-sprcha.html">Poloviční sprcha - 4 míčky</a></li>
			<li><a href="/video/navod/micky-4-sebrani.html">Sbírání míčků</a></li>
			<li><a href="/video/navod/micky-4-sloupy.html">Sloupy se čtyřmi míčky</a></li>
			<li><a href="/video/navod/micky-4-splits.html">Sloupy - splits</a></li>
			<li><a href="/video/navod/micky-4-sprcha.html">Sprcha - 4 míčky</a></li>
			<li><a href="/video/navod/micky-4-tenis.html">Tenis se čtyřmi míčky</a></li>
			<li><a href="/video/navod/micky-5-kaskada-r.html">Reverzní kaskáda</a></li>
			<li><a href="/video/navod/micky-5-kaskada.html">Kaskáda s pěti míčky</a></li>
			<li><a href="/video/navod/micky-5-multiplex.html">Kaskáda (multiplex) s pěti míčky</a></li>
			<li><a href="/video/navod/micky-5-polovicni-sprcha.html">Poloviční sprcha - 5 míčků</a></li>
			</ul>
			</li>
			<li><a name="navody"></a><a href="/video/navody/">Video návody na žonglování</a>
			<ul>
			<li><a href="/video/navody/5-ball-mills-mess.html">Mill&#039;s Mess s pěti míčky</a></li>
			<li><a href="/video/navody/balance-juggling.html">Balancování kuželky na bradě</a></li>
			<li><a href="/video/navody/behind-the-head-passing.html">Passing za hlavou</a></li>
			<li><a href="/video/navody/club-passing-variation.html">Passing s pěti kužely</a></li>
			<li><a href="/video/navody/doctor-attack.html">Útok doktora</a></li>
			<li><a href="/video/navody/flourish-tutorial.html">Kytička</a></li>
			<li><a href="/video/navody/otocka.html">Otočka</a></li>
			<li><a href="/video/navody/roundabout-tutorial.html">Kolotoč</a></li>
			<li><a href="/video/navody/russian-balls.html">Ruské míčky</a></li>
			<li><a href="/video/navody/shared-columns.html">Sloupy ve dvou</a></li>
			<li><a href="/video/navody/take-out-combo.html">Přebírání kuželů</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li><a name="vyhledavani"></a><a href="/vyhledavani/">Žonglérův slabikář - vyhledávání</a>
		
		</li>
	</ul>
	</li>

</ul>
