#datum*titulek*odkaz*obrazek*text
2009-12-21*Veselé Vánoce*/vanoce-2009.html*vanoce.png*Na úvodní stránce žonglérova slabikáře najdeš každý týden něco nového. A jako první je tu vánoční přání.
2009-12-28*PF 2010*/pf-2010.html*pf-2010b.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2010-01-04*Žonglování v Ulitě*/ulita/?201001*ulita.cz.png*V neděli se koná první letošní žonglování v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-01-11*Hledání v žonglérově slabikáři*/vyhledavani/*hledani.png*Žonglérův slabikář obsahuje rychlé a přesné <a href="https://zonglovani.info/vyhledavani/" title="Fulltextové prohledávání žonglérova slabikáře.">vyhledávání</a>.
2010-01-18*Žonglování v Ulitě*/ulita/?201003*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-01-25*Zvedání míčku nohou*/micky/kick-up.html*kickup-micky.png*Tento týden se naučíme zvedání míčku nohou. Podceňovaná a přitom klíčová dovednost.
2010-02-01*Bratři v tricku 2*/video/bratri-v-tricku-2.html*bratri2.jpg*Bratři v tricku nelení a jsou tu zas. Adam a Vašek předvádějí <a href="https://zonglovani.info/kuzely/passing/" title="Víc lidí žongluje dohromady.">passing s kužely</a>.
2010-02-04*Žonglování v Ulitě*/ulita/?201005*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-02-08*Australský trik*/kuzely/passing/australsky-trik.html*klokan.png*Nauč se něco od klokanů. Australský trik obsahuje přebírání kuželek, třesení rukou a házení kuželky za zády. 
2010-02-15*Žonglování v Ulitě*/ulita/?201007*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-02-22*Take It Out 3*/video/take-it-out-3.html*take-it-out3.jpg*Video, kde si Lukas Schütte a Christof Buch přebírají kužely.
2010-03-01*Žonglování v Ulitě*/ulita/?201009*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-03-08*Passing s míčky - mills' mess*/micky/passing-mm.html*micky-passingmmb.png*Trik pro dva žongléry a pět míčků.
2010-03-15*Žonglování v Ulitě*/ulita/?201011*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-03-22*Kalendář žonglérských akcí*/kalendar/*kalendar.png*Přehledný seznam míst, kde by správný žonglér neměl chybět. I ty můžeš přidat svojí akci.
2010-03-29*Žonglování s vajíčky*/micky/vajicka.html*vajickaa.png*Jsou šišatá, křehká a nadělají spoustu nepořádku. Ale kdo by odolal? Navíc, za chvíli jsou tu velikonoce.
2010-04-05*Žonglování v Ulitě*/ulita/?201013*ulita.cz.png*Poslední jarní žonglování v domě dětí a mládeže Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-04-12*Soutěž v žonglování*/kalendar/udalost-20100417-20100417-summer-1269243438.html*filicongoivil.jpg*Fličongoivil je soutěž v žonglování (točení). Pořádá DDM Slaný.
2010-04-19*Neta Oren*/video/neta-oren.html*neta-oren-balls.jpg*Neta Oren z Izraele to s míčky opravdu umí. Uvidíš tři až sedm míčků.
2010-04-26*Kam dál*/micky/3/kaskada.html#kam-dal*kam-dal.png*Na konci většiny stránek v žonglérově slabikáři najdeš odkazy na související triky.
2010-05-03*Žonglérské míčky*/micky/druhy.html*pomeranc-nahled.jpg*Pořádný míček je základ úspěchu. Pořiď si proto takové, které se ti líbí a vyhovují.
2010-05-10*Prozkoumej žonglérův slabikář*/mapa-stranek.html*kompas.png*<a href="https://zonglovani.info/mapa-stranek.html" title="Všechny stránky v žonglérově slabikáři.">Mapa stránek</a> obsahuje odkazy na všechny stránky v žonglérově slabikáři.
2010-05-17*rec.juggling*/rec-juggling.html*rec.juggling.s.png*Celosvětová diskusní skupina o žonglování.
2010-05-24*Interrobang*/video/interrobang.html*interrobang.jpg*Aaron DeWitt a Shane Miclon passují s kužely.
2010-05-31*Hvězda*/kuzely/passing/star.html*kuzely-passing-stara.png*Passovací trik pro <strong>5 žonglérů</strong>. Někdy se mu také říká pětiúhelník.
2010-06-07*Oheň a pohyb*/kalendar/udalost-20100705-20100711-pek-1268070475.html*ohen-a-pohyb.jpg*Žonglování, tanec, akrobacie, šerm, bubnování a mnoho dalšího. To všechno tě čeká na semináři Oheň a pohyb.
2010-06-14*Deštník*/micky/4/destnik.html*destnikc.png*Kdo má po ruce 4 míčky, toho ani déšť nepřekvapí.
2010-06-21*EJC 2010*/kalendar/udalost-20100724-20100801-pek-1267957805.html*ejc2010.jpg*Za měsíc začíná evropské setkání žonglérů v Joensuu. Nejvyšší čas sehnat si odvoz do Finska.
2010-06-28*Žonglérská víkendovka*/literatura.html#zv*zonglerska-vikendovka.png*Brožura pro výuku žonglování na víkendových kurzech. Popisuje základy žonglování s míčky a točení s poi.
2010-07-05*Prechac Weaves*/video/prechac-weaves.html*prechac-weaves.jpg*Trochu propletené žonglování.
2010-07-12*Chůdy*/chudy/*cirkusc.png*Diváci milují chůdy. Hlavně proto, že jsou zvědaví kdy chůdař spadne a šeredně si natluče. <a href="https://zonglovani.info/chudy/" title="Návod na výrobu chůd.">Návod na výrobu chůd</a>.
2010-07-19*Aleje 2010*/kalendar/udalost-20100821-20100828-pek-1267957575.html*aleje-logo.jpg*Za měsíc začne 9. mezinárodní žonglérská a divadelní dílna Aleje 2010.
2010-07-26*Roucoulette sauce poisson*/video/roucoulette-sauce-poisson.html*roucoulette-sauce-poisson.jpg*Úžasná manipulace s kužely.
2010-08-02*Výzva pro fotografy*/obrazky/*fotaka.png*Rád uveřejním i tvoje fotografie žonglování. Stačí vědět kde a kdy byly pořízené a <a href="https://zonglovani.info/kontakt.html" title="Stránka s emailem.">napsat</a>. Tvoje fotky pak uvidí hodně lidí, které zajímá žonglování.
2010-08-09*Animace žonglování*/animace/*animace-panacek.png*Žonglérův slabikář nově obsahuje i animace žonglování z programu JuggleAnim.
2010-08-16*Siteswap*/siteswap.html*p4sprchac.png*Jsou to vlastně takové noty pro žonglování. Siteswap vymysleli žongléři, aby s jejich pomocí <strong>našli nové triky</strong>.
2010-08-23*Žonglérská mapa*/mapa/*mapa.png*Mapa s vyznačením měst kde jsou žongléři. Přidat se můžeš tak, že si založíš účet v žonglérově slabikáři.
2010-08-30*Fotky z Ulity*/obrazky/filtr/Ulita*ulita.cz.png*Fotografie z podzimního, zimního a jarního žonglování v Ulitě.
2010-09-06*Neúplná hvězda*/kuzely/passing/prebihani4z11k.html*kuzely-passing-prebihani4z11kc.png*Občas není dostatek žonglérů na úplnou <a href="https://zonglovani.info/kuzely/passing/star.html" title="Trik pro 5 žonglérů.">hvězdu</a> a pak je potřeba trochu běhat.
2010-09-13*Juggling.tv*/juggling-tv.html*juggling.tv.png*Domov žonglérského videa na internetu.
2010-09-20*Bratři v tricku - trénink*/video/bratri-v-tricku-training-day.html*training-day.jpg*Letní trénink bratrů v triku.
2010-09-27*Žonglování v Ulitě*/ulita/?20101003*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-10-04*Fotky z Ulity*/obrazky/ulita-20101003/0000.html*ucho.jpg*Fotky z prvního podzimního žonglování v Ulitě.
2010-10-07*Obrázky na plochu*/obrazky-na-plochu/*kuzelky-na-trave.jpg*Obrázky na plochu počítače s žonglérskou tématikou.
2010-10-11*Žonglování v Ulitě*/ulita/?20101017*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-10-18*Fotky z Ulity*/obrazky/ulita-20101017/0001.html*pass-ulita.jpg*Fotky z druhého podzimního žonglování v Ulitě.
2010-10-21*Helikoptéra*/kuzely/3/helikoptera.html*kuzely-3-helikopterac.png*Trik s kuželkou. Ale pozor, je trochu na hlavu :^)
2010-10-25*Žonglérská videa*/video/stranka7.html*videa.jpg*U videí v žonglérově slabikáři jsou nově obrázkové náhledy.
2010-10-27*Žonglování v Ulitě*/ulita/?20101031*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-01*Fotky z Ulity*/obrazky/ulita-20101031/0000.html*mimina-v-ulite.jpg*Fotky z dalšího nedělního žonglování v Ulitě.
2010-11-04*Výuka žonglování*/lide/dovednost/workshop.html*usx.jpg*Seznam žonglérů a žonglérek kteří tě naučí žonglovat.
2010-11-08*Pražský žonglérský marathon 2*/kalendar/udalost-20101113-20101114-pek-1284723047.html*pzm2.png*Druhý ročník pražského žonglérského marathonu.
2010-11-10*Žonglování v Ulitě*/ulita/?20101114*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-15*Fotky z marathonu I.*/obrazky/prazsky-zonglersky-marathon-2-20101113/0001.html*pzm2.jpg*První část fotek z druhého ročníku pražského žonglérského marathonu.
2010-11-16*Fotky z marathonu II.*/obrazky/prazsky-zonglersky-marathon-2-souteze-a-vystoupeni-20101113/0000.html*pzm2-souteze.jpg*Další fotky z pražského žonglérského marathonu. Soutěže a večerní vystoupení.
2010-11-17*Fotky z Ulity*/obrazky/ulita-20101114/0000.html*nadseny-zongler.jpg*Fotky z nedělního žonglování v Ulitě.
2010-11-18*Žonglování v Ulitě*/ulita/?20101121*ulita.cz.png*Už v neděli se opět žongluje v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-22*Fotky z Ulity*/obrazky/ulita-20101121/0001.html*mlady-zongler.jpg*Fotky z nedělního žonglování v Ulitě.
2010-11-25*Bláznivá žehlička*/video/club2ring.html*club2ring.png*Krátký příběh o tom, co provedla splašená žehlička.
2010-11-29*Žonglování v Ulitě*/ulita/?20101205*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-12-06*RSS agregátor*/rss/*rss.png*Přehled novinek na stránkách o žonglování.
2010-12-09*Všežonglérský slet*/kalendar/udalost-20101212-20101212-pek-1290799311.html#*vsezonglersky-slet.png*Nedělní odpoledne v žižkovské sokolovně plné žonglování, her a workshopů.
2010-12-13*Návody na žonglování*/navody/*navod-tisk.png*Návody na žonglování a výrobu míčků ve formátu PDF. Vhodné pro tisk.
2010-12-20*White balance*/video/white-balance.html*wbt.jpg*Balancování kuželek. Shane Miclon a Aaron DeWitt balancují s kužely.
2010-12-21*Don Texas*/video/don-texas.html*dtt.jpg*Malte a Nils si hrají s míčky.
2010-12-22*Veselé Vánoce*/vanoce-2010.html*vanocni-kometa.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2010-12-27*PF 2011*/pf-2011.html*pf-2011.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2011-01-03*Statistiky*/statistiky.html*podporaa.png*Trocha bilancování uplynulého roku. Podívej se kolik lidí používá žonglérův slabikář a na další statistiky.
2011-01-04*Liquid Crystal*/video/liquid-crystal-live.html*matt-hennem.jpg*Představení Liquid Crystal - Matt Hennem na živo.
2011-01-10*Žonglování v Ulitě*/ulita/?20110116*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-01-17*Fotky z Ulity*/obrazky/ulita-20110116/0000.html*mizu.jpg*Fotky z nedělního žonglování v Ulitě.
2011-01-19*Otáčení kuželky okolo palce*/kuzely/toceni-okolo-palce.html*tocenib.png*Trik který můžeš trénovat i v místnostech s nízkým stropem.
2011-01-24*Žonglování v Ulitě*/ulita/?20110130*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-01-31*Žonglování na ledě*/kalendar/udalost-20110204-20110204-pek-1295125652.html*zongl-led.jpg*Tradiční zimní taškařice cirkusu LeGrando.
2011-02-03*Všežonglérský slet*/kalendar/udalost-20110206-20110206-pek-1295365358.html*vsezonglersky-slet-ii.png*Druhé nedělní žonglování v Žižkovské sokolovně.
2011-02-07*Žonglování v Ulitě*/ulita/?20110213*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-02-14*Fotky z Ulity*/obrazky/ulita-20110213/0000.html*zonglerka-v-modrem.jpg*Fotky z nedělního žonglování v Ulitě.
2011-02-21*Instalace žonglérova slabikáře*/download*download.png*Nainstaluj si žonglérův slabikář do počítače. Zjednodušená verze která jde používat i bez připojení k internetu. 
2011-02-23*Žonglování v Ulitě*/ulita/?20110227*ulita.cz.png*V neděli se opět žongluje v DDM Ulita. Začátek v 16.00. Vezmi svoje žonglovátka a přijď si zaházet.
2011-02-28*Fotky z Ulity*/obrazky/ulita-20110227/#*hula-hop.jpg*Fotky z nedělního žonglování v Ulitě. POZOR! Ulita je opět příští víkend.
2011-03-02*Žonglování v Ulitě*/ulita/?20110306*ulita.cz.png*Už v neděli je další žonglování v Ulitě. Pro širokou veřejnost jsou k zapůjčení míčky, kruhy a kužely. Přijď potrénovat žonglování.
2011-03-07*Fotky z Ulity*/obrazky/ulita-20110306/0000.html*toceni-kruhem.jpg*Fotky z nedělního žonglování v Ulitě.
2011-03-08*Dresdner Jonglierfest*/kalendar/udalost-20110311-20110313-pek-1299016806.html*djf11.jpg*V pátek začíná festival žonglování v Drážďanech.
2011-03-09*Elektronická kniha o žonglování*/download/mobi.html*package-mobi.png*Žonglérův slabikář jako elektronická kniha. Dostupné jsou formáty mobi a epub které zobrazí většina čteček.
2011-03-14*Fotky z Drážďan - sobota*/obrazky/drazdany-20110312/0001.html*drazdany-passing.jpg*Obrázky z festivalu žonglování v Drážďanech.
2011-03-15*Fotky z Drážďan - neděle*/obrazky/drazdany-20110313/0001.html*passing8.jpg*Další obrázky z festivalu žonglování v Drážďanech.
2011-03-16*Žonglování v Ulitě*/ulita/?20110320*ulita.cz.png*Pravidelné nedělní žonglování domě dětí a mládeže Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-03-21*Fotky z Ulity*/obrazky/ulita-20110320/0000.html*zonglerka-z-ulity.jpg*Fotky z nedělního žonglování v Ulitě.
2011-03-28*Žonglování v Ulitě*/ulita/?20110403*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-04-04*Žonglovací neděle*/kalendar/udalost-20110410-20110410-pek-1301381161.html*zonglovaci-nedele.png*Volné žonglování v sále s možností účastnit se soutěže s čímkoliv od 15h.
2011-04-11*Sloupy ve dvou*/kuzely/passing/sloupy.html*kuzely-passing-sloupyd.png*Trik pro dva žongléry se čtyřmi kužely.
2011-04-18*Videa z Drážďan*/video/drazdany-2011/*djf11.jpg*Videa z galashow na festivalu žonglování v Drážďanech.
2011-04-25*Doplňky do prohlížeče*/doplnky-prohlizece.html*browsers.png*Žonglérské doplňky do internetových prohlížečů.
2011-05-02*Videa z PŽM2*/video/pzm2/*pzm2.png*Ohlédnutí za loňským Pražským žonglérským marathonem. Videa z večerní show.
2011-05-09*Sun*/video/sun.html*sun.jpg*Sluníčko, Jirka z Ostravy a diabolo.
2011-05-16*Mikulovské kejklířské klání*/kalendar/udalost-20110520-20110522-pek-1301227300.html*kejkleni.png*Festival plný kejklení, ohnivých show, cirkusových vystoupení a soutěží o ceny.
2011-05-23*Žonglpárty*/kalendar/udalost-20110528-20110528-pek-1299222189.html*zonglparty.jpg*Žonglování na dopravním hřišti na Vypichu.
2011-05-30*Žonglérova chvilka poezie*/kalendar/udalost-20110701-20110710-pek-1300255720.html*chvilka-poezie.png*Dílna pro začínající a mírně pokročilé žongléry. Naučíte se žonglovat s míčky a kužely. Vyzkoušíte poi, diabolo a další žonglérské techniky.
2011-06-06*Ultimate Juggling Battle*/kalendar/udalost-20110618-20110618-niggy-1305068952.html*ujb1.png*Soutěž v žonglování jeden na jednoho. Dvě žonglérské kategorie - míčky a diabolo.
2011-06-07*Den žonglování v Brně*/kalendar/udalost-20110612-20110612-pek-1305308396.html*brno-zongl.png*Oslava mezinárodního dne žonglování v Brně.
2011-06-13*Žonglobalizace*/kalendar/udalost-20110618-20110618-pek-1304627621.html*zonglobalizace.png*Festival žonglování, hudby a tance v Plzni.
2011-06-14*Den žonglování v Ostravě*/kalendar/udalost-20110617-20110618-cozzi-1307695295.html*ostrava-2011.jpg*Oslavy dne žonglování v Ostravě.
2011-06-15*Světový den žonglování*/kalendar/udalost-20110618-20110618-pek-1299136069.html*pece-2011.png*Světový den žonglování v parku na Židovských pecích v Praze.
2011-06-19*3 play in Prague*/video/3-play-in-prague.html*3playprague.jpg*Žonglování se třemi míčky od Play.
2011-06-20*Mistrovství ČR ve fire performance*/kalendar/udalost-20110624-20110624-pek-1304157243.html*mcrfp2011.png*Ad infinitum a PVP team vyhlašují mistrovství ČR v žonglování a točení s ohněm.
2011-06-22*Polná v plamenech*/kalendar/udalost-20110625-20110625-pek-1300568950.html*pvp2011.png*Druhý ročník festivalu ohně a žonglování. Koná se v Polné u Jihlavy.
2011-06-27*Slovenská Úúú Letná Oslava Žonglovania*/kalendar/udalost-20110701-20110703-mizu-1300967085.html*suloz2011.jpg*Voľné stretnutie žonglérov a takých. Akcia je zdarma, každý si platí len ubytovanie v campe.
2011-06-30*Žonglérův slabikář v mobilu*/mobil.html*mobil-xperia-w.s.jpg*Žonglérův slabikář je přizpůsobený prohlížení na mobilních telefonech.
2011-07-04*European Juggling Convention*/kalendar/ejc.html*ejc2011s.png*Evropské setkání žonglérů v Mnichově začíná za měsíc. Nejvyšší čas sehnat si odvoz do Německa.
2011-07-11*Kytička*/video/navody/flourish-tutorial.html*flourish-tutorial.jpg*Video návod jak udělat při žonglování kytičku s kuželem.
2011-07-18*Aleje*/kalendar/udalost-20110820-20110826-pek-1293471692.html*aleje-logo.jpg*Za měsíc začne 10. mezinárodní žonglérská a divadelní dílna Aleje 2011.
2011-07-25*Twitter*/twitter.html*twitter.png*Co si vrabci štěbetají o žonglování? Přes twitter se dozvíš o všech novinkách.
2011-08-01*Rotující čtverce*/kuzely/passing/squares.html*ctverce-r.png*Trik pro čtyři žongléry a dvanáct kuželů. Všichni hází 4 count z pravé ruky.
2011-08-08*Literatura*/literatura.html*encyclopaedia.jpg*Přehled nejlepších knížek o žonglování.
2011-08-15*Obrázky z EJC 2011*/obrazky/filtr/EJC11*ejc2011s.png*Obrázky z European Juggling Convention 2011 v Mnichově.
2011-08-22*What the (beepbeep) do we know?*/video/what-the-beepbeep-do-we-know.html*partnerpoi.jpg*Točení s poi ve více lidech.
2011-08-29*Kaskáda s pěti míčky*/micky/5/kaskada.html*5kaskadac.png*Návod na kaskádu s pěti míčky.
2011-09-05*Mill's Mess s pěti míčky*/video/navody/5-ball-mills-mess.html*5-ball-mills-mess.jpg*Video s návodem na Mill's Mess s pěti míčky.
2011-09-12*A New Ratio*/video/a-new-ratio.html*a-new-ratio.jpg*Emil Lamprecht and Doreen Großmann passují s kužely na střeše.
2011-09-19*Guava over winter break*/video/guava-winter-07-08.html*guava-winter-07-08.jpg*Starší ale pořád dobré video od Salby a Ann.
2011-09-26*Video návody*/video/navod/info.html*video.png*Většinu triků v žonglérově slabikáři doplňuje krátké instruktážní video. Odkazy pro přehrání videa jsou označeny obrázkem kamery.
2011-10-03*Žonglování v Ulitě*/ulita/?20111009*ulita.cz.png*V neděli se koná první letošní podzimní žonglování v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-10-10*Fotky z Ulity*/obrazky/ulita-20111009/#*parova-akrobacie.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem kdo dorazily. Příští Ulita je za tři týdny.
2011-10-14*Otevření žonglérského obchodu*/kalendar/udalost-20111017-20111017-pek-1318013298.html*firelovers.png*Firelovers.com otvírají novou kamennou prodejnu v Praze.
2011-10-18*Žonglování poslepu*/micky/poslepu.html*poslepua.png*Můžeš žonglovat se šátkem nebo kbelíkem přes oči. Případně jednoho z diváků požádat, aby ti zakryl oči rukama.
2011-10-24*Žonglování v Ulitě*/ulita/?20111031*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-10-31*Fotky z Ulity*/obrazky/ulita-20111030/#*poi.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za čtrnáct dní.
2011-11-02*Žonglování okolo člověka*/kuzely/passing/around.html*kuzely-passing-aroundsomebodyb.png*Při žonglérském vystoupení je důležité zapojit diváky.
2011-11-07*Žonglování v Ulitě*/ulita/?20111113*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-11-14*Fotky z Ulity*/obrazky/ulita-20111113/0000.html*parove-zonglovani.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2011-11-16*Pražský žonglérský marathon*/kalendar/udalost-20111118-20111120-pek-1316975377.html*pzm2011.png*Třetí ročník pražského žonglérského marathonu.
2011-11-21*Obrázky kuželů*/kuzely/druhy.html*kuzelka-albatros-s.jpg*Obrázky žonglérských kuželů.
2011-11-28*Žonglování v Ulitě*/ulita/?20111204*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-12-05*Vánoční žonglování*/kalendar/udalost-20111210-20111210-pek-1322138854.html*bratri.jpg*Volné předvánoční žonglování. Bude k dispozici velká tělocvična s ozvučením, žonglovací obchod Žongluj Imrvére a workshopy pro začátečníky.
2011-12-11*Reading Roundabouts*/video/readingroundabouts.html*readingroundabouts.jpg*Passing jako na kolotoči.
2011-12-14*Krabice*/micky/4/krabice.html*micky-4-krabiceb.png*Box se čtyřmi míčky.
2011-12-19*Veselé Vánoce*/vanoce-2011.html*diabolo-sipek.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2011-12-21*Žonglérův slabikář na papíře*/obrazky/zongleruv-slabikar-na-papire-20111218/0000.html*zsp.jpg*Žonglérův slabikář si můžeš jednoduše vytisknout na papír. Ke stažení je PDF soubor o 151 stránkách. Devět z deseti žonglérů doporučuje oboustranný tisk a kroužkovou vazbu.
2011-12-28*PF 2012*/pf-2012.html*snehulacek.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2012-01-02*Passování do všech rukou*/kuzely/passing/all-hands.html*kuzely-passing-allhandsc.png*Obtížnější trik pro dva žongléry a šest kuželů.
2012-01-09*Žonglování v Ulitě*/ulita/?20120115*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-01-16*Fotky z Ulity*/obrazky/ulita-20120115/0004.html*poi-ii.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-01-23*Všežonglérský slet*/kalendar/udalost-20120129-20120129-pek-1325250582.html*vs0112.jpg*Žonglérské sešlost v prostorách TJ Sokol Žižkov.
2012-01-30*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-02-06*Fotky z Ulity*/obrazky/ulita-20120205/0000.html*klara.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-02-13*Blesk*/micky/3/blesk.html*bleskc.png*Blesk je rychlé vyhození míčků tak, že tvé dlaně zůstanou na okamžik prázdné.
2012-02-20*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-02-27*Fotky z Ulity*/obrazky/ulita-20120226/0000.html*3up.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-03-01*Juggling session*/kalendar/udalost-20120304-20120304-pek-1328807281.html*blink.jpg*Žonglování v dočasném klubu Blink.
2012-03-05*Druhy hodů při passování*/kuzely/passing/hody.html*kuzely-passing-hodyg.png*Kužely lze házet mnoha různými způsoby.
2012-03-08*Mezinárodní den žen*/mdz/*mdz.png*Oslavte mezinárodní den žen žonglováním.
2012-03-09*Fina magic*/video/levistick/fina-magic.html*fina-magic.jpg*Kinessis je skupina zabývající se přetvářením reality k obrazu svému a úžasu našemu.
2012-03-12*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-03-19*Simulátory žonglování*/software.html*joepass.png*Počítačové programy, které po zadání triku v zobrazí animaci. Vhodné při učení nových triků.
2012-03-26*Anglicko-český žonglérský slovníček*/aczslovnicek.html*slovnik.jpg*Několik slovíček, které se často vyskytují v anglicky psaných textech o žonglování.
2012-04-01*Žonglování na olympiádu*/olympiada/*oh.png*Petice za zařazení žonglování mezi olympijské sporty.
2012-04-02*Rybičky*/kuzely/3/rybicky.html*rybickab.png*Obtížný způsob házení kuželů. Anglicky označovaný flat.
2012-04-09*Košický kužel*/kalendar/udalost-20120413-20120415-pek-1328720895.html*kk12.png*Festival žonglování v Košicích.
2012-04-16*3 count*/kuzely/passing/3count.html*kuzely-passing-3counta.png*Každý 3. hod je pass. Jako valčík, na tři doby.
2012-04-23*Poloviční sprcha*/micky/4/sprcha-polovicni.html*p4sprchac.png*Poloviční sprcha se čtyřmi míčky.
2012-04-30*Překulení kuželky přes hlavu*/kuzely/headroll.html*headrollc.png*Trik známý též pod anglickým názvem headroll.
2012-05-07*Jen Slaw Juggling Promo*/video/jen-slaw.html*jen-slaw.jpg*Ukázka z vystoupení Jennyfer Slaw.
2012-05-14*Žonglpárty*/kalendar/udalost-20120519-20120519-pek-1321009065.html*zonglparty.png*Žonglování na dopravním hřišti na Vypichu.
2012-05-21*Žonglobalizace*/kalendar/udalost-20120525-20120526-esteladefuego-1334069981.html*zonglobalizace12.jpg*Dvoudenní multižánrový festival, který se zaměřuje na cirkusové umění, kvalitní hudbu a další umělecky příbuzné obory.
2012-05-27*Blind passes*/video/etc/4-count-blind-passes.html*blind-passes.jpg*Návod na házení poslepu při passování s kužely.
2012-05-28*Cirk-uff*/kalendar/udalost-20120531-20120603-pek-1334989292.html*cirkuff.png*Poslední květnový čtvrtek zahájí v dopoledních hodinách belgičtí žongléři druhý ročník mezinárodního festivalu nového cirkusu Cirk-uff 2012.
2012-06-04*Ohnivé kužely*/kuzely/ohen.html*kuzely-firea.png*Základy žonglování s ohněm.
2012-06-11*Konstrukce kuželu*/kuzely/konstrukce.html*kuzel-konstrukce-s.png*Jak vypadá kužel uvnitř.
2012-06-12*Světový den žonglování*/kalendar/sdz12.html*wjd12.png*O víkendu se koná světový den žonglování. Žonglovat můžeš na spoustě míst.
2012-06-18*Výroba kuželů*/kuzely/vyroba.html*kuzely-vyrobae.png*Kužely levně, snadno a rychle.
2012-06-25*European Juggling Convention*/kalendar/ejc.html*ejc-luk.jpg*Evropské setkání žonglérů v Lublini začíná za měsíc. Nejvyšší čas sehnat si odvoz do Polska.
2012-07-02*Aleje*/kalendar/udalost-20120825-20120831-pek-1333022216.html*aleje-logo.jpg*Za měsíc začne 11. mezinárodní žonglérská a divadelní dílna Aleje 2012.
2012-07-09*Prohození kruhu pod nohou*/kruhy/3/noha.html*kruhy-3-nohaa.png*Jednoduchý a velmi efektní trik s kruhy.
2012-07-16*Sbírání spadlých míčků*/micky/sbirani.html*micky-sbirania.png*Když ti spadne míček, nepřestávej žonglovat.
2012-07-23*Obíhání*/kuzely/passing/runarounds.html*kuzely-runaroundsa.s.png*Runarounds - trik pro dva žongléry a tři kužely.
2012-07-30*See saw*/micky/3/seesaw.html*seesawb.png*Krabice se třemi míčky.
2012-08-01*Tribo fuego*/kalendar/udalost-20120808-20120808-pek-1343370681.html*tf-10let.jpg*10. výročí ohnivé skupiny Tribo Fuego.
2012-08-09*Nad hlavou*/micky/3/nadhlavou.html*nadhlavoua.png*Žonglování s míčky a rukama nad hlavou.
2012-08-13*Základy poi*/kalendar/udalost-20120816-20120816-pek-1344783230.html*zaklady-poi.png*Workshop základů točení s poi ve Stromovce.
2012-08-17*Horoskop žonglování*/horoskop/*horoskop.png*Horoskop pro žonglérky a žongléry. Každý den ti poradí co je nejlepší trénovat.
2012-08-20*Žonglérův slabikář pro Android*/g/android.app*android-juggling.png*Žonglérův slabikář je dostupný v obchodě Google Play. Učebnice žonglování zdarma do každého mobilu s Androidem.
2012-08-27*Flaming nights*/kalendar/udalost-20120831-20120902-pek-1328721694.html*fn12.png*První ročník největšího hudebně-žonglérského open air festivalu v Česko-Slovensku.
2012-09-03*1 count*/kuzely/passing/1count.html*kuzely-passing-1counta.png*Rychlé passování s kužely - ultimates.
2012-09-10*Dva kužely v jedné ruce*/kuzely/grip.html*kuzely-grip-normal.s.png*Existují dva způsoby jak držet kužely před prvním výhozem.
2012-09-17*Čtyři a sedm*/video/etc/elgringos.html*elgringos.jpg*Passing se čtyřmi a sedmi kužely ve finském Espoo.
2012-09-24*Odražení míčku kolenem*/micky/3/koleno.html*kolenob.png*Snadný a velmi efektní trik. K jeho provedení jsou potřeba skákavé míčky.
2012-10-01*Juggling Documentation*/video/etc/juggling-documentation.html*jd.jpg*Video z tréninku s kužely - hlavně balancování.
2012-10-08*501*/micky/2/501.html*501b.png*Cvičení se dvěma míčky. Může posloužit i jako trénink na kaskádu s pěti míčky.
2012-10-15*Midtown Greenway*/video/etc/midtown-greenway.html*midtown-greenway.jpg*Nick Laffey žongluje s kužely.
2012-10-22*Tenis*/micky/4/tenis.html*micky-4-tenisc.png*Velmi obtížný trik se čtyřmi míčky.
2012-10-29*Pražský žonglérský marathon*/kalendar/udalost-20121102-20121104-pek-1347737642.html*pzm2012.png*Čtvrtý ročník pražského žonglérského marathonu.
2012-11-05*Fotky z PŽM 4*/obrazky/prazsky-zonglersky-marathon-20121103/0000.html*pzm4f.jpg*Fotografie ze čtvrtého ročníku pražského žonglérského marathonu.
2012-11-12*Řada*/kuzely/passing/line.html*line-promo.png*Line - trik pro tři žongléry a devět kuželů.
2012-11-19*Rozhovor s FireshowJBC*/lide/rozhovor/fireshowjbc.html*fjbc.jpg*Rozhovor s ohnivou skupinou FireshowJBC.
2012-11-26*Míček z tenisáku*/micky/vyroba-tenisak.html*levny-tenisak.s.jpg*Rychlý návod, jak vyrobit míček na žonglování z tenisáku a nafukovacích balónků.
2012-12-03*Visual Juggling Promo*/video/etc/vjpromo.html*vjpromo.jpg*Upoutávka na žonglérské video Visual Juggling.
2012-12-10*Flow*/video/levistick/flow.html*flow.jpg*Josefína ze skupiny Kinessis na pláži u moře.
2012-12-17*Kříž*/micky/4/kriz.html*4krizc.png*Jak název napovídá, budeš tentokrát míčky házet křížem.
2012-12-20*Veselé Vánoce*/vanoce-2012.html*micky-ve-snehu.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2012-12-27*PF 2013*/pf-2013.html*diabolo-ve-snehu.s.jpg*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2013-01-02*Passování s pivem*/kuzely/passing/pivo.html*bv.jpg*Trik pro tři žongléry s šesti kužely a lahví piva. Postupně si všichni tři házíte kuželky a předáváte láhev piva.
2013-01-07*Brno juggling convention*/kalendar/udalost-20130111-20130113-pek-1351105142.html*bjc01.png*První ročník Brno Juggling Convention.
2013-01-14*Préchac with my friends*/video/etc/prechac-wmf.html*prechac-wmf.jpg*Žonglování s míčky ve více lidech.
2013-01-21*Pes a kužel*/obrazky-na-plochu/pes-a-kuzel.html*don-s-kuzelkou.jpg*Malý černý pes a bílý kužel Henrys Pirruete. Tapeta na plochu počítače s žonglérskou tématikou.
2013-01-28*Sloupy II*/micky/4/sloupy-ii.html*4sloupyiib.png*Těžší varianta sloupů se čtyřmi míčky.
2013-02-04*Žonglování na ledě*/kalendar/udalost-20130208-20130208-pek-1353529655.html*zongl-led.jpg*Tradiční zimní taškařice cirkusu LeGrando.
2013-02-10*La Pequeña Rosa*/video/etc/pequena-rosa.html*pequena-rosa.jpg*Světový rekord v balancování míčku na hlavě a současném točení s hula-hop kruhy.
2013-02-11*Woko vol.2*/kalendar/udalost-20130217-20130217-pek-1359924238.html*woko2.png*Druhá žonglérská dílna v klubu Woko. Zve FireshowJBC.
2013-02-14*Svátek svatého Valentýna*/valentyn/*mdz.png*Dnes je svátek všech zamilovaných. Ideální čas pro žonglování v páru.
2013-02-15*Give Me Your Tricks*/video/etc/gmyt-ejc2013-1.html*gmyt-ejc2013-1.jpg*První ze čtyř upoutávek na EJC 2013. Už se těšíte?
2013-02-18*Sobotní trénink*/kalendar/udalost-20130223-20130223-pek-1360768310.html*f.png*Sobotní trénink žonglování v Praze. Zkušení lektoři, půjčovna žonglovátek a dobrá hudba.
2013-02-24*Diabolo u moře*/obrazky-na-plochu/bolo-more.html*bolo-more.jpg*Červené diabolo Henrys Cirkus na břehu středozemního moře. Tapeta na plochu počítače s žonglérskou tématikou.
2013-02-25*Víkend plný žonglování*/kalendar/udalost-20130302-20130303-pek-1361288677.html*vpz2.jpg*Už druhý víkend plný žonglování.
2013-03-04*Šest míčků*/micky/6/*micky-6-fontanaa.png*Základní trik se šesti míčky.
2013-03-08*Mezinárodní den žen*/mdz/*mdz.png*Jaro je plné dívčích svátků. Oslavte mezinárodní den žen žonglováním.
2013-03-09*Lorgnejus*/video/etc/lorgnejus.html*lorgnejus.jpg*Hrátky s míčky, kužely a světlem.
2013-03-11*Žonglérské vizitky*/download/vizitky.html*package-vizitky.png*Vizitky žonglérova slabikáře. Tiskněte a rozšiřujte :-)
2013-03-18*Animace siteswapů*/animace/siteswap/*siteswapb.png*Animované ztvárnění siteswapů s míčky.
2013-03-25*Chytání pod rukou*/video/navody/underarm-catches-tutorial.html*underarm-catches-tutorial.jpg*Video návod na chytání míčků pod rukou od Meagan Nouisové.
2013-04-01*Žonglování na olympiádu*/olympiada/*oh.png*Petice za zařazení žonglování mezi olympijské sporty.
2013-04-02*Woko vol.3*/kalendar/udalost-20130407-20130407-martinfabera-1363457064.html*woko3.png*Třetí žonglérská dílna v klubu Woko. Zve FireshowJBC.
2013-04-08*D-Clubs*/video/d-clubs.html*d-clubs.jpg*Flor Luludy a Jacopo Candeloro žonglují s kužely.
2013-04-15*D-Clubs 2*/video/d-clubs2.html*d-clubs2.jpg*Žonglování v jedné italské domácnosti.
2013-04-22*Dvojitá krabice*/micky/3/dvojita-krabice.html*micky-3-doubleboxc.png*Trik známý také pod anglickým názvem - double box.
2013-04-29*Dominik Grohmann*/video/tip/dominik-grohmann.html*dgj.jpg*Dominik Grohmann žongluje s kužely.
2013-05-06*Sekání*/kuzely/3/sekani.html*kuzely-3-sekania.png*Chops s kužely.
2013-05-13*Žonglpárty*/kalendar/udalost-20130518-20130518-pek-1365876912.html*zonglparty.png*4. ročník festivalu žonglování a volnočasových aktivit.
2013-05-20*Slip on*/video/etc/slipon.html*slipon.jpg*Passování s kužely v Kyotu, Japonsko.
2013-05-27*Aleje 2013*/kalendar/udalost-20130824-20130830-pek-1367140489.html*aleje-logo.jpg*12. mezinárodní žonglérská a divadelní dílna. Počet míst je omezen. Přihlaš se co nejdřív.
2013-06-03*Žonglobalizace*/kalendar/udalost-20130607-20130609-esteladefuego-1362080475.html*zonglobalizace13.jpg*Mezinárodní multižánrový festival hudby, nového cirkusu a divadla.
2013-06-10*Fair Play Vol. 3*/kalendar/udalost-20130615-20130615-pek-1365877234.html*frystak13.jpg*Mezinárodní setkání netradičních sportů a umění.
2013-06-12*Den žonglování v Brně*/kalendar/udalost-20130616-20130616-pek-1370519414.html*brno13.png*Dvanáctý ročník dne žonglování v Brně. Pestrobarevné míčky ve vzduchu, rotující kužely, točící se diabola, svištící tyče, ale také točící se gramofony, cvakající fotoaparáty, exhibice, soutěže, fireshow, sound system, a desítky účinkujících. 
2013-06-17*European Juggling Convention*/kalendar/udalost-20130727-20130803-pek-1357415255.html*ejc2013.png*Evropské setkání žonglérů v Toulouse začíná za měsíc. Nejvyšší čas sehnat si odvoz do Francie.
2013-06-24*Polná v plamenech*/kalendar/udalost-20130628-20130630-pek-1371123449.html*polna13.jpg*Čtvrtý ročník festivalu ohňových umění.
2013-07-01*Slovenská Už zas umelecká Letná Oslava Žonglovania*/kalendar/udalost-20130705-20130707-mizu-1366498343.html*suloz13.jpg*Voľná stanovačka/stretávka žonglérov a iných podivínov bez akýchkoľvek záväzkov, poplatkov či programu.
2013-07-08*Žongléři z Brna*/lide/misto/brno.html*brnoznak.png*Seznam žonglérů z Brna.
2013-07-15*Otevřený žonglérův slabikář*/opensource.html*octocat.png*Zdrojové soubory žonglérova slabikáře jsou volně dostupné.
2013-07-22*la Galerie*/video/tip/la-galerie.html*la-galerie.jpg*Marie Le Corre manipuluje s klobouky v galerii.
2013-07-29*Robot*/micky/3/robot.html*micky-3-robota.png*Míčky nebudou opisovat obloučky jako obvykle. Naopak, cílem tohoto triku je míčky házet a přesunovat rovně.
2013-08-05*Workshop poi a žonglování*/kalendar/udalost-20130811-20130811-pek-1374781742.html*wspoi.png* Workshop poi a žonglování od fireshow.cz. Místo konání park Libosad v Jičíně.
2013-08-12*EJC 2013*/obrazky/ejc-20130801/*ejc13.jpg*Fotky z EJC 2013 od Luka Burrage.
2013-08-15*Přehrada art fest*/kalendar/udalost-20130817-20130818-zongler4-1373789715.html*paf2013.jpg*Festival na Jablonecké přehradě. Můžete se těšit na velký výběr workshopů, soutěží a večerní light a fireshow.
2013-08-19*Roztočení diabola*/diabolo/roztoceni-diabola.html*roztocenia.png*Jak snadno a rychle roztočit diabolo.
2013-08-26*Flaming Nights*/kalendar/udalost-20130830-20130831-pek-1354134372.html*fn13.png*Druhý ročník ohnivého festivalu Flaming Nights. Program pro žongléry bude probíhat už od čtvrtečního odpoledne - 29. 8. 2013.
2013-09-02*Odražení míčku čelem*/micky/3/celo.html*celob.png*Jednoduchý a velmi efektní trik. K jeho provedení jsou potřeba skákavé míčky.
2013-09-09*More or less juggling*/video/more-or-less.html*more-or-less.jpg*Více nebo méně žonglování.
2013-09-16*Berlin juggling convention 2013*/obrazky/bjc-20130606/*bjc13.jpg*Obrázky z Berlin juggling convention 2013.
2013-09-23*Ultimate Juggling Battle 3*/kalendar/udalost-20130928-20130928-ujs-1379857038.html*ujb3.png*Skupina Ultimate Juggling Squad každoročně pořádá žonglérskou soutěž.
2013-09-30*8 Hours 8 Hats*/video/tip/8hats.html*8hats.jpg*Bri a Mumu s osmi klobouky.
2013-10-07*Handshake Tutorial*/video/navody/handshake.html*handshake.jpg*Anglický návod na australský trik.
2013-10-14*Workshop poi a žonglování*/kalendar/udalost-20131020-20131020-pek-1381692825.html*wspoi.png* Workshop poi a žonglování od fireshow.cz. Místo konání K-klub v Jičíně.
2013-10-21*Liquid Underground*/video/tip/liquid-underground.html*lu.jpg*Matt Hennem v Londýnském metru.
2013-10-28*Les 3 tetes de con*/video/tip/les-tetes-de-con.html*ltdc.jpg*A teď něco s kloubouky.
2013-11-04*Pes a míček*/obrazky-na-plochu/pes-a-micek.html*don-s-mickem.jpg*Malý černý pes a žlutý míček. Tapeta na plochu počítače s žonglérskou tématikou.
2013-11-11*Pass self*/kuzely/passing/ps.html*kuzely-passing-psa.png*Trik pro dva žongléry se šesti kužely.
2013-11-18*Poloviční sprcha*/micky/3/sprcha-polovicni.html*psprchab.png*Trik poloviční sprcha se třemi míčky.
2013-11-25*Pražský žonglérský marathon*/kalendar/udalost-20131129-20131201-pek-1380821206.html*pzm13s.jpg*Pátý ročník pražského žonglérského marathonu.
2013-12-02*2 v 1 tenis*/micky/3/tenis-2v1.html*2v1tenisb.png*Trik se třemi míčky.
2013-12-09*Plechové žonglování*/kalendar/udalost-20131215-20131215-pek-1385146013.html*plech-zongl.png*Žonglérské odpoledne v Plechárně. K žonglování budou hrát ostřílení djs.
2013-12-16*The Black Sheep*/video/tip/the-black-sheep.html*the-black-sheep.jpg*Robin Spinelli v dvanáctiminutovém filmu o žonglování s diabolem.
2013-12-23*Veselé Vánoce*/vanoce-2013.html*kapr-kuzel.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2013-12-30*PF 2014*/pf-2014.html*rum-kuzel.s.jpg*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2014-01-06*Dust in the Chain*/video/tip/dust-in-the-chain.html*dust-in-the-chain.jpg*Trocha akrobatické cyklistiky v podání Yohanna Trepaniera.
2014-01-13*Brno juggling convention*/kalendar/udalost-20140117-20140119-pek-1389338710.html*bjc02.png*Druhý ročník Brno Juggling Convention.
2014-01-20*Unicycle*/video/tip/unicycle.html*uni-slack.jpg*S jednokolkou na slack-lině.
2014-01-27*Juggling Around Iceland*/video/tip/juggling-around-iceland.html*juggling-around-iceland.jpg*Trocha žonglování na Isladu.
2014-02-03*Aerial Emery*/video/hulahop/aerial-emery.html*aerial-emery.jpg*Točení s obručemi v podání Aerial Emery.
2014-02-10*Žonglování na ledě*/kalendar/udalost-20140214-20140214-pek-1391417681.html*zongl-led14.png*Tradiční zimní taškařice cirkusu LeGrando.
2014-02-17*Pass pass self*/kuzely/passing/pps.html*kuzely-passing-ppsa.png*Trik pro dva žongléry a šest kuželů.
2014-02-24*Kometa*/micky/3/kometa.html*micky-3-kometaa.png*Zavaž míček do šátku a máš kometu.
2014-03-03*Motion cocktail*/video/tip/motion-cocktail.html*motion-cocktail.jpg*Vojta Žák a Šimon Borna trénují vystoupení Motion cocktail.
2014-03-10*Orangutan*/micky/3/orangutan.html*orangutana.png*Tento trik sice není až tak žonglování, ale publikum zaručeně pobaví.
2014-03-17*Flaka a Daniela*/video/tip/flaka-daniela-juggling.html*fdj.jpg*Žonglérky Cinthia a Daniela.
2014-03-24*Had*/micky/3/had.html*hadd.png*Míčky létají za sebou jako had.
2014-03-31*Spot the Drop Trailer*/video/tip/spot-the-drop-trailer.html*spot-the-drop.jpg*Trailer k vystoupení Spot the Drop.
2014-04-07*Sicily vacation*/video/etc/sicily-vacation.html*sicily-vacation.jpg*Daniela Paličková s míčky na Sicílii.
2014-04-14*Chopped Dolby*/video/tip/chopped-dolby.html*chopped-dolby.jpg*Trochu komplikovanější passing s kužely.
2014-04-21*Odkládání kuželky na bradu*/kuzely/3/brada.html*bradab.png*Trik, při kterém jedna ruka kuželky hází a druhá je odkládá na bradu.
2014-04-28*55550*/micky/4/55550.html*55550c.png*Při 55550 házíš míčky stejně jako při kaskádě s pěti míčky. Jenom je těch míčků o jeden míň.
2014-05-05*Jeff Lutkus a Wes Peden*/video/jeff-wes.html*jeff-wes.jpg*Video z roku 2006.
2014-05-12*Passing s kužely*/lide/dovednost/kuzely_passing.html*druhyc.png*Seznam žonglérů a žonglérek, kteří umí passovat s kužely.
2014-05-19*Tornádo*/animace/yo-yo-tornado.html*tornado.png*Animace triku se třemi míčky.
2014-05-26*Australan*/video/navod/kuzely-passing-australsky-trik.html*australan.jpg*Nauč se něco od klokanů. Australský trik obsahuje přebírání kuželek, třesení rukou a házení kuželky za zády.
2014-06-02*Kolotoč*/video/navody/roundabout-tutorial.html*roundabout-tutorial.jpg*Návod na kolotoč s kužely.
2014-06-09*Fair Play 2014*/kalendar/udalost-20140614-20140614-rodo1991-1390379637.html*fp4.jpg*Mezinárodní workshopový festival netradičních sportů a umění v jednom čase na jednom místě.
2014-06-15*Den žonglování*/kalendar/udalost-20140615-20140615-pek-1401883971.html*dzvb14.png*13. ročník dne žonglování v Brně.
2014-06-16*Žonglpárty*/kalendar/udalost-20140621-20140621-pek-1401883344.html*zonglparty.png*4. ročník festivalu žonglování a volnočasových aktivit.
2014-06-23*European Juggling Convention*/kalendar/ejc.html*ejc2014.png*Evropské setkání žonglérů v Millstreet začíná za měsíc. Nejvyšší čas sehnat si odvoz do Irska.
2014-06-30*Aleje 2014*/kalendar/udalost-20140823-20140829-pek-1397330013.html*aleje-logo.jpg*13. mezinárodní žonglérská a divadelní dílna. Počet míst je omezen. Přihlaš se co nejdřív.
2014-07-07*Conctabong*/video/metlili/conctabong.html*conctabong.jpg*Kombinace kontaktního Žonglování a skákacích míčků ve dvou.
2014-07-17*ISBN*/isbn.html*slovnik.jpg*Žonglérův slabikář má ISBN.
2014-07-21*Jeden mezi dvěma*/micky/3/1mezi2.html*sloupyc.png*Jeden mezi dvěma je vlastně rozšíření sloupů. Jeden míček se proplétá nad a pod dvěma zbývajícími.
2014-07-28*Házení horem*/kuzely/3/hazenihorem.html*kuzely-3-horema.png*První kužel házíš z pravé ruky. Ruka je při hodu upažená do boku. Kužel ti letí nad hlavou.
2014-08-04*Druhy žonglování*/druhy-zonglovani.html*druhya.png*Základní přehled způsobů žonglování. Nejedná se o úplný nebo přesný seznam. Jde jen o naznačení, jak můžeš žonglovat. S čím vším můžeš žonglovat se dozvíš v přehledu žonglérských pomůcek.
2014-08-11*Flaming Nights*/kalendar/udalost-20140815-20140816-pek-1407603798.html*fn14.jpg*Žonglérsko - hudební open air festival.
2014-08-18*Výroba kruhů*/kruhy/vyroba.html*kruhy-vyrobaa.png*K výrobě budeš potřebovat kartonovou krabici, lepicí pásku a nůžky. Vyrobit jeden kruh trvá asi 15 minut.
2014-08-25*Jeden okolo dvou*/micky/3/1okolo2.html*sloupyn.png*Jeden okolo dvou je vlastně rozšíření sloupů. Dva míčky vyhazuješ rovně nahoru a třetí házíš kolem nich.
2014-09-01*Mistrovství ČR v žonglování*/kalendar/udalost-20140905-20140907-pek-1407604370.html*mcr1.png*Přijďte si pořádně zažonglovat do Rosic u Brna.
2014-09-08*Zkřížené ruce*/micky/3/zkrizene-ruce.html*rzkaskadaa.png*Žonglovat se dá i se zkříženýma rukama. Nejlépe se na to hodí reverzní kaskáda.
2014-09-15*Jak začít žonglovat s kruhy*/kruhy/jak-zacit.html*kruhy-zacateka.png*Kruh je třeba při vyhození roztočit, aby letěl rovně.
2014-09-22*Míček z balónků*/micky/vyroba-balonky.html*balonky-na-vyrobu-micku.s.jpg*Nejjednodušší je vyrobit míček na žonglování z nafukovacích balónků.
2014-09-29*Sprcha*/micky/4/sprcha.html*4sprchaa.png*Princip je stejný jako se třemi míčky. Je ale potřeba větší rychlost. Prvně se mi tento trik povedl až poté, co jsem začal trénovat kaskádu s pěti míčky. Dobrým tréninkem na tento trik je poloviční sprcha.
2014-10-06*Oj - oj*/micky/3/ojoj.html*ojoja.png*Známé též jako australské jo-jo.
2014-10-13*Multiplex*/micky/3/multiplex.html*micky-3-multiplexta.png*Vyhození několika míčků z jedné ruky - to je multiplex.
2014-10-20*Pleasure Station Day*/kalendar/udalost-20141025-20141025-pek-1413658780.html*psd14.jpg*Již 5. ročník Pleasure Station Day proběhne nově ve větších prostorech Papírna Plzeň.
2014-10-27*Trojúhelník*/kuzely/passing/trojuhelnik.html*kuzely-passing-trojuhelnika.png*Jednoduchý trik pro tři žongléry a devět kuželů.
2014-11-03*Žonglování na síti*/odkazy.html*www.png*Odkazy na stránky věnované žonglování.
2014-11-10*Délka provázku*/diabolo/delka-provazku.html*provazeka.png*Správná délka provázku je ta, která ti vyhovuje.
2014-11-17*Pražský žonglérský marathon*/kalendar/udalost-20141121-20141123-pek-1413622702.html*pzm14s.jpg*Šestý ročník pražského žonglérského marathonu.
2014-11-24*Jedení jablka*/micky/3/jablko.html*jablkoa.png*Při žonglování s jablky můžeš průběžně ukusovat. Normální míček místo do pusy odložíš třeba pod bradu.
2014-12-01*Orbit*/micky/3/orbit.html*micky-3-orbita.png*Orbit, někdy též nazývaný obtoč.
2014-12-08*Nůžky*/kuzely/3/nuzky.html*kuzely-nuzkya.png*Překřížením dvou kuželů získáš "nůžky", do kterých můžeš chytit třetí kužel.
2014-12-15*4 count*/kuzely/passing/4count.html*kuzely-passing-4count-rytmus.png*Základní způsob passování pro 2 žongléry a 6 kuželů. Každý 4. hod je pass. Házíš:
2014-12-22*Veselé Vánoce*/vanoce-2014.html*kometa-kuzel.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2014-12-29*Sloupy*/micky/3/sloupy.html*sloupya.png*Sloupy s míčky jsou velmi rozmanitý trik. Toto je jeho základní provedení. Než ho začneš zkoušet, hodí se umět 2 v 1.
2015-01-05*Neviditelný míček*/micky/3/neviditelny.html*micky-3-neviditelnya.png*Neviditelný míček nahrazuje obyčejný míček - hlavně když ti spadne. Získáš čas k sebrání míčku a nemusíš přestat žonglovat.
2015-01-12*Zrychlená dvojka*/kuzely/passing/zrychlena-dvojka.html*kuzely-passing-zrychlenadvojkaa.png*Trik pro ozvláštnění 2 count nebo 4 count.
2015-01-19*Mýty a omyly*/myty-omyly.html*mytya.png*Typická zpráva okurkové sezony.
2015-01-26*423*/kuzely/3/423.html*423a.png*Název triku značí jednotlivé hody zapsané pomocí siteswap.
2015-02-02*Jo - jo*/micky/3/jojo.html*jojoa.png*Snadný a velmi hezký trik.
2015-02-09*Žonglování na ledě*/kalendar/udalost-20150213-20150213-pek-1422565035.html*zongl-led15.png*Tradiční zimní taškařice cirkusu LeGrando.
2015-02-16*Trénink*/trenink.html*trenink-navoda.png*Žonglovat se nenaučíš nějakým kouzlem nebo protože máš talent, ale tréninkem. Prostě to zkoušíš tak dlouho až se ti to povede.
2015-02-23*3 + 2*/micky/5/64.html*64a.png*Na první pohled snadné, avšak velmi obtížné. Pravá a levá ruka žonglují v různém rytmu.
2015-03-02*Mezinárodní den žen*/mdz/*mdz.png*Oslavte mezinárodní den žen žonglováním.
2015-03-09*Hození kuželu pod nohou*/kuzely/3/podnohou.html*kuzely-3-nohaa.png*Jednoduchý trik vhodný i pro začátečníky.
2015-03-16*Reverzní kaskáda široká*/micky/3/kaskada-reverzni-siroka.html*srkaskadaa.png*Široká reverzní kaskáda vychází z reverzní kaskády.
2015-03-23*Boston circle*/kuzely/passing/bostoncircle.html*kuzely-passing-boston4h.png*Trik, při kterém passuje každý s každým. Dokonce i sám se sebou. Známý též pod názvem hodiny.
2015-03-30*Osmička*/micky/3/osmicka.html*micky-3-osmickaa.png*Levou rukou žongluj 2 v 1.
2015-04-01*Žonglování na olympiádu*/olympiada/*oh.png*Petice za zařazení žonglování mezi olympijské sporty.
2015-04-02*Kaskáda*/kuzely/3/kaskada.html*kuzely-3-kaskadaa.png*Kaskáda je nejjednodušší způsob žonglování se třemi kužely.
2015-04-06*Zachycení míčku za krk*/micky/3/krk.html*krka.png*Jako třešničku na dortu můžeš na konci svého vystoupení předvést zachycení míčku za krk.
2015-04-13*Pravidla passování*/kuzely/passing/pravidla.html*pravidlaa.png*Při žonglování s více lidmi si užiješ spoustu legrace. Než začneš, je dobré znát následující pravidla.
2015-04-20*Pass self self pass self pass pass self*/kuzely/passing/psspspps.html*kuzely-passing-psspspps-rytmus.png*Trik pro dva žongléry a šest kuželů. Nejtěžší na něm je zapamatovat si název.
2015-04-27*Kroužek žonglování v Hradci Králové*/kalendar/udalost-20150430-20150430-argosovo-1429716425.html*oops.png*Nauč se žonglovat se skupinou Oops Hradec Králové - míčky kužely, (partner) poi, talíře, flowersticky, jednokolka, slackline a nejen to.
2015-05-01*Fontána*/micky/4/fontana.html*fontanaa.png*Při fontáně provádí každá ruka samostatně 2 v 1. Na obrázku to může vypadat obtížně. Naštěstí je to jenom zdání a naučit se fontánu není problém.
2015-05-04*Sloupy*/micky/4/sloupy.html*4sloupya.png*Existuje víc variant provedení sloupů se čtyřmi míčky. Asi nejsnadnější je vyhazovat míčky jako při fontáně.
2015-05-11*Hodiny*/micky/3/hodiny.html*micky-3-hodinya.png*První a druhý míček vyhoď najednou z pravé ruky.
2015-05-18*Další informace o žonglování*/ostatni.html*zacatecnik.png*Základní pojmy v žonglování.
2015-05-25*Falešné sloupy*/micky/3/sloupy-falesne.html*fsloupya.png*Začni jako při normálních sloupech. První míček rovně nahoru.
2015-06-01*Žonglobalizace*/kalendar/udalost-20150606-20150606-pek-1421523958.html*zonglobalizace15.png*Pátý ročník festivalu nového cirkusu v Plzni.
2015-06-08*Mezinárodní den žonglování*/kalendar/udalost-20150614-20150614-pek-1432671771.html*dzvb15.png*Oslava mezinárodního dne žonglování.
2015-06-15*Aleje 2015*/kalendar/udalost-20150815-20150821-pek-1430386701.html*aleje-logo.jpg*14. mezinárodní žonglérská a divadelní dílna. Počet míst je omezen. Přihlaš se co nejdřív.
2015-06-22*Polná v plamenech*/kalendar/udalost-20150627-20150627-pek-1421827020.html*polna15.jpg*Šestý ročník festivalu ohňových umění.
2015-06-29*European Juggling Convention*/kalendar/ejc.html*ejc2015.png*Evropské setkání žonglérů v Brunecku začíná za měsíc. Nejvyšší čas sehnat si odvoz do Itálie.
2015-07-06*Žonglérské pexeso*/pexeso/*zonglerske-pexeso.s.jpg*Supertěžké žonglérské pexeso.
2015-07-13*Chrámové okno*/micky/3/okno.html*oknoa.png*Při tomto triku míčky létají vysokým úzkým obloukem, který připomíná obrys chrámového okna.
2015-07-20*441*/micky/3/441.html*441a.png*Pěkný trik, ale dostat se do rytmu chvíli trvá.
2015-07-27*Větrný mlýn*/micky/3/mlyn.html*mlyna.png*Míčky opisují stejnou dráhu jako při sprše, ale nepřesunují se z jedné ruky do druhé rychlým vodorovným hodem. Místo toho křížíš ruce a vyhazuješ míčky jen z jedné strany.
2015-08-03*Rotující Y*/kuzely/passing/rypsilon.html*kuzely-passing-rypsilona.png*Obtížnější trik pro 4 žongléry a 12 kuželů.
2015-08-10*Hození za zády*/kuzely/3/zazady.html*kuzely-3-zadaa.png*Kužely nemusíš házet jenom před sebe. Velmi pěkné je občas prohodit kužel za zády.
2015-08-17*Mills' mess*/micky/3/mm.html*mma.png*Mills' mess vynalezl Steve Mills okolo roku 1973. Mess je anglicky nepořádek. Celý trik může na první pohled působit dost složitě.
2015-08-24*Rotace kuželu*/kuzely/rotace.html*kuzely-rotacea.png*Základní způsoby házení kuželu.
2015-08-31*Žonglování klasické i flow*/kalendar/udalost-20150903-20150903-grohy-1440430234.html*dgs.jpg*Zažijte radost z žonglování, naučte se klasické i moderní techniky a poznejte nové lidi.
2015-09-07*Prohození míčku za zády*/micky/2/zada.html*2v1zadaa.png*V pravé ruce házej 2 v 1. První míček vyhoď o trochu výš.
2015-09-14*Tenis*/micky/3/tenis.html*tenisa.png*Tenis je kombinace kaskády s reverzní kaskádou. První míček je pořád nad druhým i třetím míčkem. Létá nad nimi jako tenisový míček nad sítí. Proto se taky celý trik jmenuje tenis.
2015-09-21*2 v 1*/kruhy/2/2v1.html*kruhy-2-2v1a.png*Žonglování se dvěma kruhy v jedné ruce není těžké. Nauč se to pravou i levou rukou a už vlastně umíš žonglovat čtyřmi kruhy.
2015-09-28*Orbit II*/micky/3/orbit2.html*micky-3-orbit2ta.png*Z levé ruky vyhoď najednou první a druhý míček. Současně vyráží i pravá ruka.
2015-10-05*Prohození míčku za zády*/micky/3/zada.html*zadaa.png*Prohození míčku za zády je velmi podobné prohození míčku pod nohou.
2015-10-12*Zip*/kuzely/passing/zip.html*kuzely-passing-zipa.png*Trik pro libovolný počet žonglérů. Každý bude potřebovat tři kužely.
2015-10-19*Poloviční sprcha*/micky/5/sprcha-polovicni.html*5psprchaa.png*Když zvládneš kaskádu s pěti míčky, poloviční sprcha s pěti míčky ti nebude dělat problém.
2015-10-26*Reverzní kaskáda*/micky/5/kaskada-reverzni.html*5rkaskadaa.png*Rozdíl mezi normální a reverzní kaskádou s pěti míčky je pouze v dráze, po které létají míčky. Při reverzní kaskádě házíš míčky vnějškem.
2015-11-02*Prohození míčku pod nohou*/micky/3/noha.html*nohaa.png*Jednoduchý a velmi efektní trik.
2015-11-03*Trénink žonglování*/kalendar/udalost-20151105-20151105-argosovo-1446224386.html*oops-bw.png*Veřejný trénink žonglování skupiny Oops Hradec Králové.
2015-11-06*Roztoč fest*/kalendar/udalost-20151107-20151107-pek-1444243897.html*roztocfest-vol3.jpg*Mezinárodní festival nového cirkusu, žonglování a ohnivých umění.
2015-11-09*Dvojité jo-jo*/micky/3/dvojite-jojo.html*micky-3-djojoa.png*První a druhý míček tvoří jo-jo.
2015-11-16*Jeden a půl otočky*/kuzely/3/jeden-a-pul-otocky.html*jeden-a-pula.png*Obtížnější trik se třemi kužely.
2015-11-23*Prohození míčku pod nohou*/micky/2/noha.html*2v1nohaa.png*V pravé ruce prováděj 2 v 1. První míček vyhoď o trochu výš.
2015-11-30*Čáp*/micky/3/cap.html*capa.png*Při tomto triku stojíš jen na jedné noze jako čáp. Nejedná se o nic jiného než o opakované prohození míčku pod nohou.
2015-12-07*Pass pod nohou*/kuzely/passing/podnohou.html*passpodnohoua.png*Kuželku při passování můžeš hodit pod nohou. Nejjednodušší je při passování pravou rukou házet pod pravou nohou.
2015-12-14*2 v 1*/micky/2/2v1.html*2v1a.png*2 v 1 je základní trik se dvěma míčky. Nauč se ho pravou i levou rukou a už vlastně umíš žonglovat čtyřmi míčky.
2015-12-21*Veselé Vánoce*/vanoce-2015.html*snowman.png*Veselé vánoční svátky. Ať vám to lítá :^)
2015-12-28*PF 2016*/pf-2016.html*champagne.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2016-01-04*Cirkusové disciplíny*/cirkusove-discipliny.html*cirkusa.png*Dovednosti, které nemají s žonglováním mnoho společného. Ale z nějakého důvodu je provozuje podobný druh lidí jako žonglování.
2016-01-11*Nabíjení*/kuzely/passing/feeds.html*kuzely-passing-feedsa.png*Feeds - základní trik pro tři žongléry a devět kuželů.
2016-01-18*Jeden nad dvěma*/micky/3/1nad2.html*tenissloupya.png*Kombinace sloupů s tenisem. Jeden míček létá pořád nad dvěma ostatními.
2016-01-25*Žonglérské náčiní*/nacini.html*nacinia.png*Žonglovat můžeš se spoustou věcí. A mnoha různými způsoby.
2016-02-01*Vyhození do výšky*/diabolo/vyhozeni-do-vysky.html*diabolo-vyhozenia.png*Roztáhni ruce s hůlkami do stran.
2016-02-08*Brno juggling convention*/kalendar/udalost-20160212-20160214-pek-1444244758.html*bjc02.png*Mezinárodní nekonvenční festival s přátelskou atmosférou.
2016-02-14*Svátek svatého Valentýna*/valentyn/*mdz.png*Svátek všech zamilovaných je ideální čas pro žonglování v páru.
2016-02-15*Žirafa*/micky/3/zirafa.html*sochaa.png*Žirafa je vlastně poloviční sprcha s jednou rukou nahoře. Jiný název pro tento trik je socha svobody.
2016-02-22*Balancování kuželu*/kuzely/balanc.html*kuzely-balanca.png*S kužely se nemusí jenom házet. Můžeš je balancovat na bradě, nose, špičce boty, ...
2016-02-29*Sprcha*/micky/3/sprcha.html*sprchaa.png*Sprcha je asi nejznámější způsob žonglování. Není ale vůbec snadné se ji naučit. Zkus se nejprve naučit poloviční sprchu.
2016-03-07*Balancování míčku*/micky/balancovani.html*balanca.png*Použij pevný kulatý míček.
2016-03-14*Neobvyklý začátek kaskády*/micky/3/neobvykly-zacatek.html*zacateka.png*Začít kaskádu můžeš i tou rukou, ve které máš jenom jeden míček.
2016-03-21*3 v 1*/micky/3/3v1.html*micky-3-3v1a.png*3 v 1 je podobné 2 v 1. Vyžaduje ovšem větší rychlost, přesnost a hlavně trpělivost.
2016-03-28*Reverzní kaskáda*/micky/3/kaskada-reverzni.html*rkaskadaa.png*Reverzní kaskáda je velmi podobná normální kaskádě.
2016-04-04*Boston mess*/micky/3/boston-mess.html*micky-3-bma.png*Míčky házíš rovně nahoru jako při sloupech. Ruce se kříží jako při Mills' mess.
2016-04-11*Klokan*/micky/3/klokan.html*klokana.png*Snadný a velmi efektní trik. K jeho provedení je potřeba mít na sobě volnější tričko.
2016-04-18*40303*/micky/2/40303.html*40303a.png*Jednoduché cvičení se dvěma míčky.
2016-04-25*Socha svobody*/micky/3/socha.html*sochaa.png*Socha svobody je vlastně poloviční sprcha s jednou rukou nahoře. Jiný název pro tento trik je žirafa.
2016-05-02*Obloučky*/micky/3/oblouky.html*obloukya.png*Každý míček má vlastní dráhu, která se nekříží s ostatními.
2016-05-09*Kaskáda (multiplex)*/micky/5/kaskada-multiplex.html*5kaskadamultia.png*Kaskáda s pěti míčky je obtížný trik. Nezbývá tedy nic jiného, než si ji trochu usnadnit. Stačí vyhazovat dva míčky najednou.
2016-05-16*Falešné Mills' mess*/micky/3/mm-falesne.html*micky-3-mm-falesnea.png*Popsat tento trik je skoro stejně těžké jako se ho naučit. Takže hurá do toho!
2016-05-23*Výměny ve čtvercích*/kuzely/passing/vymeny.html*vymenya.png*Trik pro čtyři žongléry s dvanácti kužely.
2016-05-30*Jak začít žonglovat s míčky*/micky/jak-zacit.html*starta.png*Míčky jsou nejjednodušší náčiní. Snadno se hážou i chytají.
2016-06-06*Výroba míčků na žonglování*/micky/vyroba.html*micek-z-balonku-3.s.jpg*S trochou šikovnosti lze vyrobit míčky pro žonglování doma na koleně.
2016-06-13*Synchronní fontána*/micky/4/fontana-synchronni.html*sfontanaa.png*Synchronní fontána je mírnou obměnou klasické fontány.
2016-06-20*
2016-06-27*
2016-07-04*
2016-07-11*
2016-07-18*
2016-07-25*
2016-08-01*
2016-08-08*
2016-08-15*
2016-08-22*
2016-08-29*
2016-09-05*
2016-09-12*
# vim: set nonumber nowrap:
