#datum*titulek*odkaz*obrazek*text
2009-12-21*Veselé vánoce*/vanoce-2009.html*vanoce.png*Na úvodní stránce žonglérova slabikáře najdeš každý týden něco nového. A jako první je tu vánoční přání.
2009-12-28*PF 2010*/pf-2010.html*pf-2010b.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2010-01-04*Žonglování v Ulitě*/ulita/?201001*ulita.cz.png*V neděli se koná první letošní žonglování v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-01-11*Hledání v žonglérově slabikáři*/vyhledavani/*hledani.png*Žonglérův slabikář obsahuje rychlé a přesné <a href="http://zonglovani.info/vyhledavani/" title="Fulltextové prohledávání žonglérova slabikáře.">vyhledávání</a>.
2010-01-18*Žonglování v Ulitě*/ulita/?201003*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-01-25*Zvedání míčku nohou*/micky/kick-up.html*kickup-micky.png*Tento týden se naučíme zvedání míčku nohou. Podceňovaná a přitom klíčová dovednost.
2010-02-01*Bratři v tricku 2*/video/bratri-v-tricku-2.html*bratri2.jpg*Bratři v tricku nelení a jsou tu zas. Adam a Vašek předvádějí <a href="http://zonglovani.info/kuzely/passing/" title="Víc lidí žongluje dohromady.">passing s kužely</a>.
2010-02-04*Žonglování v Ulitě*/ulita/?201005*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-02-08*Australský trik*/kuzely/passing/australsky-trik.html*klokan.png*Nauč se něco od klokanů. Australský trik obsahuje přebírání kuželek, třesení rukou a házení kuželky za zády. 
2010-02-15*Žonglování v Ulitě*/ulita/?201007*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-02-22*Take It Out 3*/video/take-it-out-3.html*take-it-out3.jpg*Video, kde si Lukas Schütte a Christof Buch přebírají kužely.
2010-03-01*Žonglování v Ulitě*/ulita/?201009*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-03-08*Passing s míčky - mills' mess*/micky/passing-mm.html*micky-passingmmb.png*Trik pro dva žongléry a pět míčků.
2010-03-15*Žonglování v Ulitě*/ulita/?201011*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-03-22*Kalendář žonglérských akcí*/kalendar/*kalendar.png*Přehledný seznam míst, kde by správný žonglér neměl chybět. I ty můžeš přidat svojí akci.
2010-03-29*Žonglování s vajíčky*/micky/vajicka.html*vajickaa.png*Jsou šišatá, křehká a nadělají spoustu nepořádku. Ale kdo by odolal? Navíc, za chvíli jsou tu velikonoce.
2010-04-05*Žonglování v Ulitě*/ulita/?201013*ulita.cz.png*Poslední jarní žonglování v domě dětí a mládeže Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-04-12*Soutěž v žonglování*/kalendar/udalost-20100417-20100417-summer-1269243438.html*filicongoivil.jpg*Fličongoivil je soutěž v žonglování (točení). Pořádá DDM Slaný.
2010-04-19*Neta Oren*/video/neta-oren.html*neta-oren-balls.jpg*Neta Oren z Izraele to s míčky opravdu umí. Uvidíš tři až sedm míčků.
2010-04-26*Kam dál*/micky/3/kaskada.html#kam-dal*kam-dal.png*Na konci většiny stránek v žonglérově slabikáři najdeš odkazy na související triky.
2010-05-03*Žonglérské míčky*/micky/druhy.html*pomeranc-nahled.jpg*Pořádný míček je základ úspěchu. Pořiď si proto takové, které se ti líbí a vyhovují.
2010-05-10*Prozkoumej žonglérův slabikář*/mapa-stranek.html*kompas.png*<a href="http://zonglovani.info/mapa-stranek.html" title="Všechny stránky v žonglérově slabikáři.">Mapa stránek</a> obsahuje odkazy na všechny stránky v žonglérově slabikáři.
2010-05-17*rec.juggling*/rec-juggling.html*rec.juggling.s.png*Celosvětová diskusní skupina o žonglování.
2010-05-24*Interrobang*/video/interrobang.html*interrobang.jpg*Aaron DeWitt a Shane Miclon passují s kužely.
2010-05-31*Hvězda*/kuzely/passing/star.html*kuzely-passing-stara.png*Passovací trik pro <strong>5 žonglérů</strong>. Někdy se mu také říká pětiúhelník.
2010-06-07*Oheň a pohyb*/kalendar/udalost-20100705-20100711-pek-1268070475.html*ohen-a-pohyb.jpg*Žonglování, tanec, akrobacie, šerm, bubnování a mnoho dalšího. To všechno tě čeká na semináři Oheň a pohyb.
2010-06-14*Deštník*/micky/4/destnik.html*destnikc.png*Kdo má po ruce 4 míčky, toho ani déšť nepřekvapí.
2010-06-21*EJC 2010*/kalendar/udalost-20100724-20100801-pek-1267957805.html*ejc2010.jpg*Za měsíc začíná evropské setkání žonglérů v Joensuu. Nejvyšší čas sehnat si odvoz do Finska.
2010-06-28*Žonglérská víkendovka*/literatura.html#zv*zonglerska-vikendovka.png*Brožura pro výuku žonglování na víkendových kurzech. Popisuje základy žonglování s míčky a točení s poi.
2010-07-05*Prechac Weaves*/video/prechac-weaves.html*prechac-weaves.jpg*Trochu propletené žonglování.
2010-07-12*Chůdy*/chudy/*cirkusc.png*Diváci milují chůdy. Hlavně proto, že jsou zvědaví kdy chůdař spadne a šeredně si natluče. <a href="http://zonglovani.info/chudy/" title="Návod na výrobu chůd.">Návod na výrobu chůd</a>.
2010-07-19*Aleje 2010*/kalendar/udalost-20100821-20100828-pek-1267957575.html*aleje-logo.jpg*Za měsíc začne 9. mezinárodní žonglérská a divadelní dílna Aleje 2010.
2010-07-26*Roucoulette sauce poisson*/video/roucoulette-sauce-poisson.html*roucoulette-sauce-poisson.jpg*Úžasná manipulace s kužely.
2010-08-02*Výzva pro fotografy*/obrazky/*fotaka.png*Rád uveřejním i tvoje fotografie žonglování. Stačí vědět kde a kdy byly pořízené a <a href="http://zonglovani.info/kontakt.html" title="Stránka s emailem.">napsat</a>. Tvoje fotky pak uvidí hodně lidí, které zajímá žonglování.
2010-08-09*Animace žonglování*/animace/*animace-panacek.png*Žonglérův slabikář nově obsahuje i animace žonglování z programu JuggleAnim.
2010-08-16*Siteswap*/siteswap.html*p4sprchac.png*Jsou to vlastně takové noty pro žonglování. Siteswap vymysleli žongléři, aby s jejich pomocí <strong>našli nové triky</strong>.
2010-08-23*Žonglérská mapa*/mapa/*mapa.png*Mapa s vyznačením měst kde jsou žongléři. Přidat se můžeš tak, že si založíš účet v žonglérově slabikáři.
2010-08-30*Fotky z Ulity*/obrazky/filtr/Ulita*ulita.cz.png*Fotografie z podzimního, zimního a jarního žonglování v Ulitě.
2010-09-06*Neúplná hvězda*/kuzely/passing/prebihani4z11k.html*kuzely-passing-prebihani4z11kc.png*Občas není dostatek žonglérů na úplnou <a href="http://zonglovani.info/kuzely/passing/star.html" title="Trik pro 5 žonglérů.">hvězdu</a> a pak je potřeba trochu běhat.
2010-09-13*Juggling.tv*/juggling-tv.html*juggling.tv.png*Domov žonglérského videa na internetu.
2010-09-20*Bratři v tricku - trénink*/video/bratri-v-tricku-training-day.html*training-day.jpg*Letní trénink bratrů v triku.
2010-09-27*Žonglování v Ulitě*/ulita/?20101003*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-10-04*Fotky z Ulity*/obrazky/ulita-20101003/0000.html*ucho.jpg*Fotky z prvního podzimního žonglování v Ulitě.
2010-10-07*Obrázky na plochu*/obrazky-na-plochu/*kuzelky-na-trave.jpg*Obrázky na plochu počítače s žonglérskou tématikou.
2010-10-11*Žonglování v Ulitě*/ulita/?20101017*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-10-18*Fotky z Ulity*/obrazky/ulita-20101017/0001.html*pass-ulita.jpg*Fotky z druhého podzimního žonglování v Ulitě.
2010-10-21*Helikoptéra*/kuzely/3/helikoptera.html*kuzely-3-helikopterac.png*Trik s kuželkou. Ale pozor, je trochu na hlavu :^)
2010-10-25*Žonglérská videa*/video/stranka7.html*videa.jpg*U videí v žonglérově slabikáři jsou nově obrázkové náhledy.
2010-10-27*Žonglování v Ulitě*/ulita/?20101031*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-01*Fotky z Ulity*/obrazky/ulita-20101031/0000.html*mimina-v-ulite.jpg*Fotky z dalšího nedělního žonglování v Ulitě.
2010-11-04*Výuka žonglování*/lide/dovednost/workshop.html*usx.jpg*Seznam žonglérů a žonglérek kteří tě naučí žonglovat.
2010-11-08*Pražský žonglérský marathon 2*/kalendar/udalost-20101113-20101114-pek-1284723047.html*pzm2.png*Druhý ročník pražského žonglérského marathonu.
2010-11-10*Žonglování v Ulitě*/ulita/?20101114*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-15*Fotky z marathonu I.*/obrazky/prazsky-zonglersky-marathon-2-20101113/0001.html*pzm2.jpg*První část fotek z druhého ročníku pražského žonglérského marathonu.
2010-11-16*Fotky z marathonu II.*/obrazky/prazsky-zonglersky-marathon-2-souteze-a-vystoupeni-20101113/0000.html*pzm2-souteze.jpg*Další fotky z pražského žonglérského marathonu. Soutěže a večerní vystoupení.
2010-11-17*Fotky z Ulity*/obrazky/ulita-20101114/0000.html*nadseny-zongler.jpg*Fotky z nedělního žonglování v Ulitě.
2010-11-18*Žonglování v Ulitě*/ulita/?20101121*ulita.cz.png*Už v neděli se opět žongluje v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-11-22*Fotky z Ulity*/obrazky/ulita-20101121/0001.html*mlady-zongler.jpg*Fotky z nedělního žonglování v Ulitě.
2010-11-25*Bláznivá žehlička*/video/club2ring.html*club2ring.png*Krátký příběh o tom, co provedla splašená žehlička.
2010-11-29*Žonglování v Ulitě*/ulita/?20101205*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2010-12-06*RSS agregátor*/rss/*rss.png*Přehled novinek na stránkách o žonglování.
2010-12-09*Všežonglérský slet*/kalendar/udalost-20101212-20101212-pek-1290799311.html#*vsezonglersky-slet.png*Nedělní odpoledne v žižkovské sokolovně plné žonglování, her a workshopů.
2010-12-13*Návody na žonglování*/navody/*navod-tisk.png*Návody na žonglování a výrobu míčků ve formátu PDF. Vhodné pro tisk.
2010-12-20*White balance*/video/white-balance.html*wbt.jpg*Balancování kuželek. Shane Miclon a Aaron DeWitt balancují s kužely.
2010-12-21*Don Texas*/video/don-texas.html*dtt.jpg*Malte a Nils si hrají s míčky.
2010-12-22*Veselé vánoce*/vanoce-2010.html*vanocni-kometa.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2010-12-27*PF 2011*/pf-2011.html*pf-2011.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2011-01-03*Statistiky*/statistiky.html*podporaa.png*Trocha bilancování uplynulého roku. Podívej se kolik lidí používá žonglérův slabikář a na další statistiky.
2011-01-04*Liquid Crystal*/video/liquid-crystal-live.html*matt-hennem.jpg*Představení Liquid Crystal - Matt Hennem na živo.
2011-01-10*Žonglování v Ulitě*/ulita/?20110116*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-01-17*Fotky z Ulity*/obrazky/ulita-20110116/0000.html*mizu.jpg*Fotky z nedělního žonglování v Ulitě.
2011-01-19*Otáčení kuželky okolo palce*/kuzely/toceni-okolo-palce.html*tocenib.png*Trik který můžeš trénovat i v místnostech s nízkým stropem.
2011-01-24*Žonglování v Ulitě*/ulita/?20110130*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-01-31*Žonglování na ledě*/kalendar/udalost-20110204-20110204-pek-1295125652.html#*zongl-led.jpg*Tradiční zimní taškařice cirkusu LeGrando.
2011-02-03*Všežonglérský slet*/kalendar/udalost-20110206-20110206-pek-1295365358.html#*vsezonglersky-slet-ii.png*Druhé nedělní žonglování v Žižkovské sokolovně.
2011-02-07*Žonglování v Ulitě*/ulita/?20110213*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-02-14*Fotky z Ulity*/obrazky/ulita-20110213/0000.html*zonglerka-v-modrem.jpg*Fotky z nedělního žonglování v Ulitě.
2011-02-21*Instalace žonglérova slabikáře*/download*download.png*Nainstaluj si žonglérův slabikář do počítače. Zjednodušená verze která jde používat i bez připojení k internetu. 
2011-02-23*Žonglování v Ulitě*/ulita/?20110227*ulita.cz.png*V neděli se opět žongluje v DDM Ulita. Začátek v 16.00. Vezmi svoje žonglovátka a přijď si zaházet.
2011-02-28*Fotky z Ulity*/obrazky/ulita-20110227/#*hula-hop.jpg*Fotky z nedělního žonglování v Ulitě. POZOR! Ulita je opět příští víkend.
2011-03-02*Žonglování v Ulitě*/ulita/?20110306*ulita.cz.png*Už v neděli je další žonglování v Ulitě. Pro širokou veřejnost jsou k zapůjčení míčky, kruhy a kužely. Přijď potrénovat žonglování.
2011-03-07*Fotky z Ulity*/obrazky/ulita-20110306/0000.html*toceni-kruhem.jpg*Fotky z nedělního žonglování v Ulitě.
2011-03-08*Dresdner Jonglierfest*/kalendar/udalost-20110311-20110313-pek-1299016806.html*djf11.jpg*V pátek začíná festival žonglování v Drážďanech.
2011-03-09*Elektronická kniha o žonglování*/download/mobi.html*package-mobi.png*Žonglérův slabikář jako elektronická kniha. Dostupné jsou formáty mobi a epub které zobrazí většina čteček.
2011-03-14*Fotky z Drážďan - sobota*/obrazky/drazdany-20110312/0001.html*drazdany-passing.jpg*Obrázky z festivalu žonglování v Drážďanech.
2011-03-15*Fotky z Drážďan - neděle*/obrazky/drazdany-20110313/0001.html*passing8.jpg*Další obrázky z festivalu žonglování v Drážďanech.
2011-03-16*Žonglování v Ulitě*/ulita/?20110320*ulita.cz.png*Pravidelné nedělní žonglování domě dětí a mládeže Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-03-21*Fotky z Ulity*/obrazky/ulita-20110320/0000.html*zonglerka-z-ulity.jpg*Fotky z nedělního žonglování v Ulitě.
2011-03-28*Žonglování v Ulitě*/ulita/?20110403*ulita.cz.png*V domě dětí a mládeže Ulita se pravidelně žongluje. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-04-04*Žonglovací neděle*/kalendar/udalost-20110410-20110410-pek-1301381161.html*zonglovaci-nedele.png*Volné žonglování v sále s možností účastnit se soutěže s čímkoliv od 15h.
2011-04-11*Sloupy ve dvou*/kuzely/passing/sloupy.html*kuzely-passing-sloupyd.png*Trik pro dva žongléry se čtyřmi kužely.
2011-04-18*Videa z Drážďan*/video/drazdany-2011/*djf11.jpg*Videa z galashow na festivalu žonglování v Drážďanech.
2011-04-25*Doplňky do prohlížeče*/doplnky-prohlizece.html*browsers.png*Žonglérské doplňky do internetových prohlížečů.
2011-05-02*Videa z PŽM2*/video/pzm2/*pzm2.png*Ohlédnutí za loňským Pražským žonglérským marathonem. Videa z večerní show.
2011-05-09*Sun*/video/sun.html*sun.jpg*Sluníčko, Jirka z Ostravy a diabolo.
2011-05-16*Mikulovské kejklířské klání*/kalendar/udalost-20110520-20110522-pek-1301227300.html*kejkleni.png*Festival plný kejklení, ohnivých show, cirkusových vystoupení a soutěží o ceny.
2011-05-23*Žonglpárty*/kalendar/udalost-20110528-20110528-pek-1299222189.html*zonglparty.jpg*Žonglování na dopravním hřišti na Vypichu.
2011-05-30*Žonglérova chvilka poezie*/kalendar/udalost-20110701-20110710-pek-1300255720.html*chvilka-poezie.png*Dílna pro začínající a mírně pokročilé žongléry. Naučíte se žonglovat s míčky a kužely. Vyzkoušíte poi, diabolo a další žonglérské techniky.
2011-06-06*Ultimate Juggling Battle*/kalendar/udalost-20110618-20110618-niggy-1305068952.html*ujb1.png*Soutěž v žonglování jeden na jednoho. Dvě žonglérské kategorie - míčky a diabolo.
2011-06-07*Den žonglování v Brně*/kalendar/udalost-20110612-20110612-pek-1305308396.html*brno-zongl.png*Oslava mezinárodního dne žonglování v Brně.
2011-06-13*Žonglobalizace*/kalendar/udalost-20110618-20110618-pek-1304627621.html*zonglobalizace.png*Festival žonglování, hudby a tance v Plzni.
2011-06-14*Den žonglování v Ostravě*/kalendar/udalost-20110617-20110618-cozzi-1307695295.html*ostrava-2011.jpg*Oslavy dne žonglování v Ostravě.
2011-06-15*Světový den žonglování*/kalendar/udalost-20110618-20110618-pek-1299136069.html*pece-2011.png*Světový den žonglování v parku na Židovských pecích v Praze.
2011-06-19*3 play in Prague*/video/3-play-in-prague.html*3playprague.jpg*Žonglování se třemi míčky od Play.
2011-06-20*Mistrovství ČR ve fire performance*/kalendar/udalost-20110624-20110624-pek-1304157243.html*mcrfp2011.png*Ad infinitum a PVP team vyhlašují mistrovství ČR v žonglování a točení s ohněm.
2011-06-22*Polná v plamenech*/kalendar/udalost-20110625-20110625-pek-1300568950.html*pvp2011.png*Druhý ročník festivalu ohně a žonglování. Koná se v Polné u Jihlavy.
2011-06-27*Slovenská Úúú Letná Oslava Žonglovania*/kalendar/udalost-20110701-20110703-mizu-1300967085.html*suloz2011.jpg*Voľné stretnutie žonglérov a takých. Akcia je zdarma, každý si platí len ubytovanie v campe.
2011-06-30*Žonglérův slabikář v mobilu*/mobil.html*mobil-xperia-w.s.jpg*Žonglérův slabikář je přizpůsobený prohlížení na mobilních telefonech.
2011-07-04*European Juggling Convention*/kalendar/ejc.html*ejc2011s.png*Evropské setkání žonglérů v Mnichově začíná za měsíc. Nejvyšší čas sehnat si odvoz do Německa.
2011-07-11*Kytička*/video/navody/flourish-tutorial.html*flourish-tutorial.jpg*Video návod jak udělat při žonglování kytičku s kuželem.
2011-07-18*Aleje*/kalendar/udalost-20110820-20110826-pek-1293471692.html*aleje-logo.jpg*Za měsíc začne 10. mezinárodní žonglérská a divadelní dílna Aleje 2011.
2011-07-25*Twitter*/twitter.html*twitter.png*Co si vrabci štěbetají o žonglování? Přes twitter se dozvíš o všech novinkách.
2011-08-01*Rotující čtverce*/kuzely/passing/squares.html*ctverce-r.png*Trik pro čtyři žongléry a dvanáct kuželů. Všichni hází 4 count z pravé ruky.
2011-08-08*Literatura*/literatura.html*encyclopaedia.jpg*Přehled nejlepších knížek o žonglování.
2011-08-15*Obrázky z EJC 2011*/obrazky/filtr/EJC11*ejc2011s.png*Obrázky z European Juggling Convention 2011 v Mnichově.
2011-08-22*What the (beepbeep) do we know?*/video/what-the-beepbeep-do-we-know.html*partnerpoi.jpg*Točení s poi ve více lidech.
2011-08-29*Kaskáda s pěti míčky*/micky/5/kaskada.html*5kaskadac.png*Návod na kaskádu s pěti míčky.
2011-09-05*Mill's Mess s pěti míčky*/video/navody/5-ball-mills-mess.html*5-ball-mills-mess.jpg*Video s návodem na Mill's Mess s pěti míčky.
2011-09-12*A New Ratio*/video/a-new-ratio.html*a-new-ratio.jpg*Emil Lamprecht and Doreen Großmann passují s kužely na střeše.
2011-09-19*Guava over winter break*/video/guava-winter-07-08.html*guava-winter-07-08.jpg*Starší ale pořád dobré video od Salby a Ann.
2011-09-26*Video návody*/video/navod/info.html*video.png*Většinu triků v žonglérově slabikáři doplňuje krátké instruktážní video. Odkazy pro přehrání videa jsou označeny obrázkem kamery.
2011-10-03*Žonglování v Ulitě*/ulita/?20111009*ulita.cz.png*V neděli se koná první letošní podzimní žonglování v Ulitě. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-10-10*Fotky z Ulity*/obrazky/ulita-20111009/#*parova-akrobacie.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem kdo dorazily. Příští Ulita je za tři týdny.
2011-10-14*Otevření žonglérského obchodu*/kalendar/udalost-20111017-20111017-pek-1318013298.html*firelovers.png*Firelovers.com otvírají novou kamennou prodejnu v Praze.
2011-10-18*Žonglování poslepu*/micky/poslepu.html*poslepua.png*Můžeš žonglovat se šátkem nebo kbelíkem přes oči. Případně jednoho z diváků požádat, aby ti zakryl oči rukama.
2011-10-24*Žonglování v Ulitě*/ulita/?20111031*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-10-31*Fotky z Ulity*/obrazky/ulita-20111030/#*poi.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za čtrnáct dní.
2011-11-02*Žonglování okolo člověka*/kuzely/passing/around.html*kuzely-passing-aroundsomebodyb.png*Při žonglérském vystoupení je důležité zapojit diváky.
2011-11-07*Žonglování v Ulitě*/ulita/?20111113*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-11-14*Fotky z Ulity*/obrazky/ulita-20111113/0000.html*parove-zonglovani.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2011-11-16*Pražský žonglérský marathon*/kalendar/udalost-20111118-20111120-pek-1316975377.html*pzm2011.png*Třetí ročník pražského žonglérského marathonu.
2011-11-21*Obrázky kuželů*/kuzely/druhy.html*kuzelka-albatros-s.jpg*Obrázky žonglérských kuželů.
2011-11-28*Žonglování v Ulitě*/ulita/?20111204*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2011-12-05*Vánoční žonglování*/kalendar/udalost-20111210-20111210-pek-1322138854.html*bratri.jpg*Volné předvánoční žonglování. Bude k dispozici velká tělocvična s ozvučením, žonglovací obchod Žongluj Imrvére a workshopy pro začátečníky.
2011-12-11*Reading Roundabouts*/video/readingroundabouts.html*readingroundabouts.jpg*Passing jako na kolotoči.
2011-12-14*Krabice*/micky/4/krabice.html*micky-4-krabiceb.png*Box se čtyřmi míčky.
2011-12-19*Veselé vánoce*/vanoce-2011.html*diabolo-sipek.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2011-12-21*Žonglérův slabikář na papíře*/obrazky/zongleruv-slabikar-na-papire-20111218/0000.html*zsp.jpg*Žonglérův slabikář si můžeš jednoduše vytisknout na papír. Ke stažení je PDF soubor o 151 stránkách. Devět z deseti žonglérů doporučuje oboustranný tisk a kroužkovou vazbu.
2011-12-28*PF 2012*/pf-2012.html*snehulacek.png*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2012-01-02*Passování do všech rukou*/kuzely/passing/all-hands.html*kuzely-passing-allhandsc.png*Obtížnější trik pro dva žongléry a šest kuželů.
2012-01-09*Žonglování v Ulitě*/ulita/?20120115*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-01-16*Fotky z Ulity*/obrazky/ulita-20120115/0004.html*poi-ii.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-01-23*Všežonglérský slet*/kalendar/udalost-20120129-20120129-pek-1325250582.html*vs0112.jpg*Žonglérské sešlost v prostorách TJ Sokol Žižkov.
2012-01-30*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-02-06*Fotky z Ulity*/obrazky/ulita-20120205/0000.html*klara.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-02-13*Blesk*/micky/3/blesk.html*bleskc.png*Blesk je rychlé vyhození míčků tak, že tvé dlaně zůstanou na okamžik prázdné.
2012-02-20*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-02-27*Fotky z Ulity*/obrazky/ulita-20120226/0000.html*3up.jpg*Fotky z nedělního žonglování v Ulitě. Díky všem, kdo dorazili. Příští Ulita je za tři týdny.
2012-03-01*Juggling session*/kalendar/udalost-20120304-20120304-pek-1328807281.html*blink.jpg*Žonglování v dočasném klubu Blink.
2012-03-05*Druhy hodů při passování*/kuzely/passing/hody.html*kuzely-passing-hodyg.png*Kužely lze házet mnoha různými způsoby.
2012-03-08*Mezinárodní den žen*/mdz/*mdz.png*Oslavte mezinárodní den žen žonglováním.
2012-03-09*Fina magic*/video/levistick/fina-magic.html*fina-magic.jpg*Kinessis je skupina zabývající se přetvářením reality k obrazu svému a úžasu našemu.
2012-03-12*Žonglování v Ulitě*/ulita/?20120205*ulita.cz.png*Pravidelné nedělní žonglování v DDM Ulita. Přijít mohou začínající i zkušení žongléři a žonglérky.
2012-03-19*Simulátory žonglování*/software.html*joepass.png*Počítačové programy, které po zadání triku v zobrazí animaci. Vhodné při učení nových triků.
2012-03-26*Anglicko-český žonglérský slovníček*/aczslovnicek.html*slovnik.jpg*Několik slovíček, které se často vyskytují v anglicky psaných textech o žonglování.
2012-04-01*Žonglování na olympiádu*/olympiada/*oh.png*Petice za zařazení žonglování mezi olympijské sporty. 
2012-04-02*Rybičky*/kuzely/3/rybicky.html*rybickab.png*Obtížný způsob házení kuželů. Anglicky označovaný flat.
2012-04-09*Košický kužel*/kalendar/udalost-20120413-20120415-pek-1328720895.html*kk12.png*Festival žonglování v Košicích.
2012-04-16*3 count*/kuzely/passing/3count.html*kuzely-passing-3counta.png*Každý 3. hod je pass. Jako valčík, na tři doby.
2012-04-23*Poloviční sprcha*/micky/4/sprcha-polovicni.html*p4sprchac.png*Poloviční sprcha se čtyřmi míčky.
2012-04-30*Překulení kuželky přes hlavu*/kuzely/headroll.html*headrollc.png*Trik známý též pod anglickým názvem headroll.
2012-05-07*Jen Slaw Juggling Promo*/video/jen-slaw.html*jen-slaw.jpg*Ukázka z vystoupení Jennyfer Slaw.
2012-05-14*Žonglpárty*/kalendar/udalost-20120519-20120519-pek-1321009065.html*zonglparty.png*Žonglování na dopravním hřišti na Vypichu.
2012-05-21*Žonglobalizace*/kalendar/udalost-20120525-20120526-esteladefuego-1334069981.html*zonglobalizace12.jpg*Dvoudenní multižánrový festival, který se zaměřuje na cirkusové umění, kvalitní hudbu a další umělecky příbuzné obory.
2012-05-27*Blind passes*/video/etc/4-count-blind-passes.html*blind-passes.jpg*Návod na házení poslepu při passování s kužely.
2012-05-28*Cirk-uff*/kalendar/udalost-20120531-20120603-pek-1334989292.html*cirkuff.png*Poslední květnový čtvrtek zahájí v dopoledních hodinách belgičtí žongléři druhý ročník mezinárodního festivalu nového cirkusu Cirk-uff 2012.
2012-06-04*Ohnivé kužely*/kuzely/ohen.html*kuzely-firea.png*Základy žonglování s ohněm.
2012-06-11*Konstrukce kuželu*/kuzely/konstrukce.html*kuzel-konstrukce-s.png*Jak vypadá kužel uvnitř.
2012-06-12*Světový den žonglování*/kalendar/sdz12.html*wjd12.png*O víkendu se koná světový den žonglování. Žonglovat můžeš na spoustě míst.
2012-06-18*Výroba kuželů*/kuzely/vyroba.html*kuzely-vyrobae.png*Kužely levně, snadno a rychle.
2012-06-25*European Juggling Convention*/kalendar/ejc.html*ejc-luk.jpg*Evropské setkání žonglérů v Lublini začíná za měsíc. Nejvyšší čas sehnat si odvoz do Polska.
2012-07-02*Aleje*/kalendar/udalost-20120825-20120831-pek-1333022216.html*aleje-logo.jpg*Za měsíc začne 11. mezinárodní žonglérská a divadelní dílna Aleje 2012.
2012-07-09*Prohození kruhu pod nohou*/kruhy/3/noha.html*kruhy-3-nohaa.png*Jednoduchý a velmi efektní trik s kruhy.
2012-07-16*Sbírání spadlých míčků*/micky/sbirani.html*micky-sbirania.png*Když ti spadne míček, nepřestávej žonglovat.
2012-07-23*Obíhání*/kuzely/passing/runarounds.html*kuzely-runaroundsa.s.png*Runarounds - trik pro dva žongléry a tři kužely.
2012-07-30*See saw*/micky/3/seesaw.html*seesawb.png*Krabice se třemi míčky.
2012-08-01*Tribo fuego*/kalendar/udalost-20120808-20120808-pek-1343370681.html*tf-10let.jpg*10. výročí ohnivé skupiny Tribo Fuego.
2012-08-09*Nad hlavou*/micky/3/nadhlavou.html*nadhlavoua.png*Žonglování s míčky a rukama nad hlavou.
2012-08-13*Základy poi*/kalendar/udalost-20120816-20120816-pek-1344783230.html*zaklady-poi.png*Workshop základů točení s poi ve Stromovce.
2012-08-17*Horoskop žonglování*/horoskop/*horoskop.png*Horoskop pro žonglérky a žongléry. Každý den ti poradí co je nejlepší trénovat.
2012-08-20*Žonglérův slabikář pro Android*/g/android.app*android-juggling.png*Žonglérův slabikář je dostupný v obchodě Google Play. Učebnice žonglování zdarma do každého mobilu s Androidem.
2012-08-27*Flaming nights*/kalendar/udalost-20120831-20120902-pek-1328721694.html*fn12.png*První ročník největšího hudebně-žonglérského open air festivalu v Česko-Slovensku.
2012-09-03*1 count*/kuzely/passing/1count.html*kuzely-passing-1counta.png*Rychlé passování s kužely - ultimates.
2012-09-10*Dva kužely v jedné ruce*/kuzely/grip.html*kuzely-grip-normal.s.png*Existují dva způsoby jak držet kužely před prvním výhozem.
2012-09-17*Čtyři a sedm*/video/etc/elgringos.html*elgringos.jpg*Passing se čtyřmi a sedmi kužely ve finském Espoo.
2012-09-24*Odražení míčku kolenem*/micky/3/koleno.html*kolenob.png*Snadný a velmi efektní trik. K jeho provedení jsou potřeba skákavé míčky.
2012-10-01*Juggling Documentation*/video/etc/juggling-documentation.html*jd.jpg*Video z tréninku s kužely - hlavně balancování.
2012-10-08*501*/micky/2/501.html*501b.png*Cvičení se dvěma míčky. Může posloužit i jako trénink na kaskádu s pěti míčky.
2012-10-15*Midtown Greenway*/video/etc/midtown-greenway.html*midtown-greenway.jpg*Nick Laffey žongluje s kužely.
2012-10-22*Tenis*/micky/4/tenis.html*micky-4-tenisc.png*Velmi obtížný trik se čtyřmi míčky.
2012-10-29*Pražský žonglérský marathon*/kalendar/udalost-20121102-20121104-pek-1347737642.html*pzm2012.png*Čtvrtý ročník pražského žonglérského marathonu.
2012-11-05*Fotky z PŽM 4*/obrazky/prazsky-zonglersky-marathon-20121103/0000.html*pzm4f.jpg*Fotografie ze čtvrtého ročníku pražského žonglérského marathonu.
2012-11-12*Řada*/kuzely/passing/line.html*line-promo.png*Line - trik pro tři žongléry a devět kuželů.
2012-11-19*Rozhovor s FireshowJBC*/lide/rozhovor/fireshowjbc.html*fjbc.jpg*Rozhovor s ohnivou skupinou FireshowJBC.
2012-11-26*Míček z tenisáku*/micky/vyroba-tenisak.html*levny-tenisak.s.jpg*Rychlý návod, jak vyrobit míček na žonglování z tenisáku a nafukovacích balónků.
2012-12-03*Visual Juggling Promo*/video/etc/vjpromo.html*vjpromo.jpg*Upoutávka na žonglérské video Visual Juggling.
2012-12-10*Flow*/video/levistick/flow.html*flow.jpg*Josefína ze skupiny Kinessis na pláži u moře.
2012-12-17*Kříž*/micky/4/kriz.html*4krizc.png*Jak název napovídá, budeš tentokrát míčky házet křížem.
2012-12-20*Veselé vánoce*/vanoce-2012.html*micky-ve-snehu.s.jpg*Veselé vánoční svátky. Ať vám to lítá :^)
2012-12-27*PF 2013*/pf-2013.html*diabolo-ve-snehu.s.jpg*Hodně štěstí a zdraví v novém roce. Ať vám to lítá :^)
2013-01-02*Passování s pivem*/kuzely/passing/pivo.html*bv.jpg*Trik pro tři žongléry s šesti kužely a lahví piva. Postupně si všichni tři házíte kuželky a předáváte láhev piva.
2013-01-07*Brno juggling convention*/kalendar/udalost-20130111-20130113-pek-1351105142.html*bjc01.png*První ročník Brno Juggling Convention.
2013-01-14*Préchac with my friends*/video/etc/prechac-wmf.html*prechac-wmf.jpg*Žonglování s míčky ve více lidech.
2013-01-21*Pes a kužel*/obrazky-na-plochu/pes-a-kuzel.html*don-s-kuzelkou.jpg*Malý černý pes a bílý kužel Henrys Pirruete. Tapeta na plochu počítače s žonglérskou tématikou.
2013-01-28*Sloupy II*/micky/4/sloupy-ii.html*4sloupyiib.png*Těžší varianta sloupů se čtyřmi míčky.
2013-02-04*Žonglování na ledě*/kalendar/udalost-20130208-20130208-pek-1353529655.html*zongl-led.jpg*Tradiční zimní taškařice cirkusu LeGrando.
2013-02-10*La Pequeña Rosa*/video/etc/pequena-rosa.html*pequena-rosa.jpg*Světový rekord v balancování míčku na hlavě a současném točení s hula-hop kruhy.
2013-02-11*Woko vol.2*/kalendar/udalost-20130217-20130217-pek-1359924238.html*woko2.png*Druhá žonglérská dílna v klubu Woko. Zve FireshowJBC.
2013-02-18*
2013-02-25*
2013-03-04*
2013-03-11*
2013-03-18*
2013-03-25*
2013-04-01*
2013-04-08*
2013-04-15*
2013-04-22*
2013-04-29*
2013-05-06*
2013-05-13*
2013-05-20*
2013-05-27*
2013-06-03*
2013-06-10*
2013-06-17*
2013-06-24*
2013-07-01*
2013-07-08*
2013-07-15*
2013-07-22*
2013-07-29*
2013-08-05*
2013-08-12*
2013-08-19*
2013-08-26*
2013-09-02*
2013-09-09*
2013-09-16*
2013-09-23*
2013-09-30*
2013-10-07*
2013-10-14*
2013-10-21*
2013-10-28*
2013-11-04*
2013-11-11*
2013-11-18*
2013-11-25*
2013-12-02*
2013-12-09*
2013-12-16*
2013-12-23*
2013-12-30*
# vim: set nonumber nowrap:
