addicted*http://www.youtube.com/watch?v=tEfjFw1RHh0*Addicted*Volnì dostupné <a href="http://www.circuspla.net/addicted/addicted.avi" class="external">DVD o ¾onglování</a>.
shake-that*http://www.circuspla.net/addicted/shakethat.avi*Shake That*Upoutávka na pøedstavení ¾onglujících barmanù <a href="http://www.shakethat.be/" class="external">shakethat.be</a>. Nebo snad míchajících ¾onglérù?
stepz*http://www.youtube.com/watch?v=8yOKiqKzkM0*Stepz*Ètyøi ¾ongléøi z Øíma.
catch-this*http://www.passingzone.com/htmdoc/video/passing%20zone%20reel%20large.wmv*Catch This*Pøedstavení dua <a href="http://www.passingzone.com" class="external">The Passing Zone</a>.
4000000-extreme-juggling*http://www.youtube.com/watch?v=ZrrVsH5QEeM*4,000,000% Extreme Juggling*Alan a Thom <a href="/zonglovani/kuzely/passing/" title="Více o passingu.">passují</a> s ku¾ely. Video z tréninku který se uskuteènil 5. dubna 2008.
guava-winter-07-08*http://www.youtube.com/watch?v=08-Cv2JPGkSEwY*Guava over winter break 07-08*®onglérky Selby a Anna na zimních prázdninách.
jen-slaw*http://www.youtube.com/watch?v=jkviK6yV1f0*Jen Slaw Juggling Promo*Ukázka z vystoupení Jennyfer Slaw.
laurent-phil*http://www.youtube.com/watch?v=bVfX26KIOFs*Laurent et Phil, juggling passing demo*Ukázka umìní dvou francouzských ¾onglérù.
joe-hague*http://www.youtube.com/watch?v=OJsAMXxtDWQ*Joe Hague Fatboy Slim Juggling Video*Procházka Brightnem s ku¾ely.
juggling-extravaganza*http://www.youtube.com/watch?v=xn95eFgzsYU*Juggling Extravaganza*Passování Bekah Smith a Tio Duermeiera.
jeremy-perkins-jeremy-fein*http://www.youtube.com/watch?v=MLbMHQnUvbY*Jeremy Perkins and Jeremy Fein Promo 2008*Ukázky z vystoupení.
all-day-baby*http://www.youtube.com/watch?v=2CDpBgljPaA*All Day Baby!*Dal¹í video z produkce J&J.
vova-olga*http://www.youtube.com/watch?v=b4RAx9BWc-w*Vova and Olga Galchenko 7+ Club Team passing WJF*Sourozenci Vova a Olga Galchenko na soutì¾i WJF (World Juggling Federation).
giraffe-theory*http://www.youtube.com/watch?v=xaf4Ee9WCdA*Giraffe Theory Juggling Glow Clubs*Nejen ¾onglování se svítícími ku¾ely. Uvidíte i jak <a href="/zonglovani/kuzely/passing/pickup.html" title="Zvednutí spadlého ku¾elu">zvednout spadlou ku¾elku</a>.
passing-st-louis*http://www.youtube.com/watch?v=pXs2cjlHZng*Passing Fancy at St. Louis Jugglefest 2007*Záznam vystoupení na festivalu v St. Louis.
jonglage-macabre*http://www.youtube.com/watch?v=hMtzQhzOvIw*Jonglage Macabre*Záznam ¾onglérského pøedstavení. Passing ve tøech.
hocus-pocus*http://www.youtube.com/watch?v=0h51lXT6tNk*Hocus Pocus*Pøedstavení z "Festival du nez rouge".
les-bebes*http://www.youtube.com/watch?v=exsEDu0cgw8*Les Bébés*Dva komici z Francie.
jeff-wes*http://www.jugglethis.net/filemgmt/singlefile.php?lid=526*Jeff Lutkus & Wes Peden*Video z roku 2006.
prechac-weaves*http://www.juggling.tv/vaults/video/PrechacWeaves.mov*Prechac Weaves*Propletené ¾onglování.
