<?php
$dovednosti_link=array();
#$dovednosti_link['show']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['workshop']=array('text'=>'Jak se naučit žonglovat','url'=>'/micky/jak-zacit.html','img'=>'zonglovania.png');
$dovednosti_link['manufactory']=array('text'=>'Jak vyrobit míčky','url'=>'/micky/vyroba-tenisak.html','img'=>'plneni-micku.s.jpg');
#$dovednosti_link['shop']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['micky']=array('text'=>'Druhy míčků','url'=>'/micky/druhy.html','img'=>'sity-nahled.jpg');
$dovednosti_link['micky_passing']=array('text'=>"Mills' mess ve dvou",'url'=>'/micky/passing-mm.html','img'=>'mmps.png');
#$dovednosti_link['bounce']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['kruhy']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['kruhy_passing']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['kuzely']=array('text'=>'Druhy kuželů','url'=>'/kuzely/druhy.html','img'=>'kuzelka-classic-dekor-s.jpg');
#$dovednosti_link['kuzely_passing']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['kuzely_ohen']=array('text'=>'Jak házet ohnivé kužely','url'=>'/kuzely/ohen.html','img'=>'kuzely-firea.png');
$dovednosti_link['diabolo']=array('text'=>'Diabolo','url'=>'/diabolo/','img'=>'nacinif.png');
$dovednosti_link['jojo']=array('text'=>'','url'=>'','img'=>'nacinii.png');
$dovednosti_link['kontakt']=array('text'=>'','url'=>'','img'=>'druhyb.png');
$dovednosti_link['devilstick']=array('text'=>'','url'=>'','img'=>'nacinig.png');
$dovednosti_link['flowerstick']=array('text'=>'','url'=>'','img'=>'nacinih.png');
$dovednosti_link['poi']=array('text'=>'','url'=>'','img'=>'nacinik.png');
#$dovednosti_link['poi_ohen']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['tyc']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['tyc_ohen']=array('text'=>'Zapálená tyč','url'=>'','img'=>'nacinij.png');
#$dovednosti_link['plivani']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['cygarbox']=array('text'=>'','url'=>'','img'=>'nacinio.png');
$dovednosti_link['jednokolka']=array('text'=>'','url'=>'','img'=>'cirkusb.png');
$dovednosti_link['boty']=array('text'=>'','url'=>'','img'=>'cirkusd.png');
$dovednosti_link['hulahop']=array('text'=>'','url'=>'','img'=>'cirkusf.png');
#$dovednosti_link['vejir']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['lano']=array('text'=>'','url'=>'','img'=>'');
$dovednosti_link['chudy']=array('text'=>'Jak vyrobit chůdy','url'=>'/chudy/','img'=>'cirkusc.png');
$dovednosti_link['hrazda']=array('text'=>'','url'=>'','img'=>'cirkuse.png');
$dovednosti_link['rolabola']=array('text'=>'','url'=>'','img'=>'cirkusg.png');
#$dovednosti_link['talir']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['balonky']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['pantomima']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['klaun']=array('text'=>'','url'=>'','img'=>'');
#$dovednosti_link['mic']=array('text'=>'','url'=>'','img'=>'');
