<?php

$dovednosti = array();
$dovednosti['show'] = array('nazev' => 'Veřejné vystupování', 'umi' => 'veřejně vystupovat', 'hodnoty' => array('n', 'a'));
$dovednosti['workshop'] = array('nazev' => 'Výuka žonglování', 'umi' => 'naučit žonglování', 'hodnoty' => array('n', 'a'));
$dovednosti['manufactory'] = array('nazev' => 'Výroba žonglérských hraček', 'umi' => 'výrábět žonglérské hračky', 'hodnoty' => array('n', 'a'));
$dovednosti['shop'] = array('nazev' => 'Prodej věcí na žonglování', 'umi' => 'prodávat věci na žonglování', 'hodnoty' => array('n', 'a'));
$dovednosti['micky'] = array('nazev' => 'Míčky', 'umi' => 'žonglovat s míčky', 'hodnoty' => array('n', 1, 2, 3, 4, 5, 6, 7, 8, 9));
$dovednosti['micky_passing'] = array('nazev' => 'Passing s míčky', 'umi' => 'passovat s míčky', 'hodnoty' => array('n', 'a'));
$dovednosti['bounce'] = array('nazev' => 'Skákací míčky', 'umi' => 'žonglovat se skákacími míčky', 'hodnoty' => array('n', 1, 2, 3, 4, 5, 6, 7, 8, 9));
$dovednosti['kruhy'] = array('nazev' => 'Kruhy', 'umi' => 'žonglovat s kruhy', 'hodnoty' => array('n', 1, 2, 3, 4, 5, 6, 7, 8));
$dovednosti['kruhy_passing'] = array('nazev' => 'Passing s kruhy', 'umi' => 'passovat s kruhy', 'hodnoty' => array('n', 'a'));
$dovednosti['kuzely'] = array('nazev' => 'Kužely', 'umi' => 'žonglovat s kužely', 'hodnoty' => array('n', 1, 2, 3, 4, 5, 6, 7));
$dovednosti['kuzely_passing'] = array('nazev' => 'Passing s kužely', 'umi' => 'passovat s kužely', 'hodnoty' => array('n', 'a'));
$dovednosti['kuzely_ohen'] = array('nazev' => 'Ohnivé kužely', 'umi' => 's ohnivými kužely', 'hodnoty' => array('n', 1, 2, 3, 4, 5, 6, 7));
$dovednosti['diabolo'] = array('nazev' => 'Diabolo', 'umi' => 's diabolem', 'hodnoty' => array('n', 1, 2, 3, 4));
$dovednosti['jojo'] = array('nazev' => 'Jo-jo', 'umi' => 's jojem', 'hodnoty' => array('n', 1, 2));
$dovednosti['kontakt'] = array('nazev' => 'Kontaktní žonglování', 'umi' => 'kontaktní žonglování', 'hodnoty' => array('n', 1, 2, 3, 4, 5));
$dovednosti['devilstick'] = array('nazev' => 'Devilstick', 'umi' => 'ovládat devilstick', 'hodnoty' => array('n', 1, 2));
$dovednosti['flowerstick'] = array('nazev' => 'Flowerstick', 'umi' => 'ovládat flowerstick', 'hodnoty' => array('n', 1, 2));
$dovednosti['poi'] = array('nazev' => 'Poi', 'umi' => 'točit s poi', 'hodnoty' => array('n', 1, 2, 3, 4));
$dovednosti['poi_ohen'] = array('nazev' => 'Zapálené poi', 'umi' => 'točit se zapálenými poi', 'hodnoty' => array('n', 1, 2, 3, 4));
$dovednosti['tyc'] = array('nazev' => 'Manipulace s tyčí', 'umi' => 'točit s tyčí', 'hodnoty' => array('n', 1, 2, 3, 4));
$dovednosti['tyc_ohen'] = array('nazev' => 'Manipulace se zapálenou tyčí', 'umi' => 'točit se zapálenou tyčí', 'hodnoty' => array('n', 1, 2, 3, 4));
$dovednosti['plivani'] = array('nazev' => 'Plivání ohně', 'umi' => 'plivat oheň', 'hodnoty' => array('n', 'a'));
$dovednosti['cygarbox'] = array('nazev' => 'Cigar boxy', 'umi' => 'cigar boxy', 'hodnoty' => array('n', 1, 2, 3, 4, 5));
$dovednosti['jednokolka'] = array('nazev' => 'Jednokolka', 'umi' => 'na jednokolce', 'hodnoty' => array('n', 'a'));
$dovednosti['boty'] = array('nazev' => 'Skákací boty', 'umi' => 'hopsat v sedmimílových botech', 'hodnoty' => array('n', 'a'));
$dovednosti['hulahop'] = array('nazev' => 'Hula hop kruh', 'umi' => 'točit s hula hop kruhem', 'hodnoty' => array('n', 1, 2, 3, 4, 5));
$dovednosti['vejir'] = array('nazev' => 'Ohnivé vějíře', 'umi' => 'mávat ohnivým vějířem', 'hodnoty' => array('n', 1, 2));
$dovednosti['lano'] = array('nazev' => 'Chůze po laně', 'umi' => 'chodit po laně', 'hodnoty' => array('n', 'a'));
$dovednosti['chudy'] = array('nazev' => 'Chůdy', 'umi' => 'chodit na chůdách', 'hodnoty' => array('n', 'a'));
$dovednosti['hrazda'] = array('nazev' => 'Visutá hrazda', 'umi' => 'viset na visuté hrazdě', 'hodnoty' => array('n', 'a'));
$dovednosti['rolabola'] = array('nazev' => 'Rola bola', 'umi' => 'udržet rovnováhu na rola bola', 'hodnoty' => array('n', 'a'));
$dovednosti['talir'] = array('nazev' => 'Točení talířem na tyčce', 'umi' => 'točit talířem na tyčce', 'hodnoty' => array('n', 'a'));
$dovednosti['balonky'] = array('nazev' => 'Zvířátka z nafukovacích balónků', 'umi' => 'vyrábět zvířátka z nafukovacích balónků', 'hodnoty' => array('n', 'a'));
$dovednosti['pantomima'] = array('nazev' => 'Pantomima', 'umi' => 'pantomimu', 'hodnoty' => array('n', 'a'));
$dovednosti['klaun'] = array('nazev' => 'Klauniáda', 'umi' => 'klauniádu', 'hodnoty' => array('n', 'a'));
$dovednosti['mic'] = array('nazev' => 'Balancování na míči', 'umi' => 'balancovat na míči', 'hodnoty' => array('n', 'a'));
