<?php
$pusobiste=array();
$pusobiste['cela-cr']=array('nazev'=>'Celá ČR','odkud'=>'z celé ČR','kde'=>'v celé ČR');
$pusobiste['cechy']=array('nazev'=>'Čechy','odkud'=>'z Čech','kde'=>'v Čechách');
$pusobiste['morava']=array('nazev'=>'Morava','odkud'=>'z Moravy','kde'=>'na Moravě');
$pusobiste['slezko']=array('nazev'=>'Slezko','odkud'=>'ze Slezka','kde'=>'na Slezku');
$pusobiste['slovensko']=array('nazev'=>'Slovensko','odkud'=>'ze Slovenska','kde'=>'na Slovensku');
$pusobiste['benesov']=array('nazev'=>'Benešov','odkud'=>'z Benešova','kde'=>'v Benešově');
$pusobiste['beroun']=array('nazev'=>'Beroun','odkud'=>'z Berouna','kde'=>'v Berouně');
$pusobiste['blansko']=array('nazev'=>'Blansko','odkud'=>'z Blanska','kde'=>'v Blansku');
$pusobiste['brno']=array('nazev'=>'Brno','odkud'=>'z Brna','kde'=>'v Brně');
$pusobiste['bruntal']=array('nazev'=>'Bruntál','odkud'=>'z Bruntálu','kde'=>'v Bruntále');
$pusobiste['breclav']=array('nazev'=>'Břeclav','odkud'=>'z Břeclavi','kde'=>'v Břeclavi');
$pusobiste['ceska-lipa']=array('nazev'=>'Česká Lípa','odkud'=>'z České Lípy','kde'=>'v Česká Lípě');
$pusobiste['ceske-budejovice']=array('nazev'=>'České Budějovice','odkud'=>'z Českých Budějovic','kde'=>'v Českých Budějovicích');
$pusobiste['cesky-krumlov']=array('nazev'=>'Český Krumlov','odkud'=>'z Českého Krumlova','kde'=>'v Českém Krumlově');
$pusobiste['decin']=array('nazev'=>'Děčín','odkud'=>'z Děčína','kde'=>'v Děčíně');
$pusobiste['domazlice']=array('nazev'=>'Domažlice','odkud'=>'z Domažlic','kde'=>'v Domažlicích');
$pusobiste['frydek-mistek']=array('nazev'=>'Frýdek-Místek','odkud'=>'z Frýdku-Místeku','kde'=>'ve Frýdeku-Místku');
$pusobiste['havlickuv-brod']=array('nazev'=>'Havlíčkův Brod','odkud'=>'z Havlíčkova Brodu','kde'=>'v Havlíčkůvě Brodě');
$pusobiste['hodonin']=array('nazev'=>'Hodonín','odkud'=>'z Hodonína','kde'=>'v Hodoníně');
$pusobiste['hradec-kralove']=array('nazev'=>'Hradec Králové','odkud'=>'z Hradce Králové','kde'=>'v Hradeci Králové');
$pusobiste['cheb']=array('nazev'=>'Cheb','odkud'=>'z Chebu','kde'=>'v Chebu');
$pusobiste['chomutov']=array('nazev'=>'Chomutov','odkud'=>'z Chomutova','kde'=>'v Chomutově');
$pusobiste['chrudim']=array('nazev'=>'Chrudim','odkud'=>'z Chrudimi','kde'=>'v Chrudimi');
$pusobiste['jablonec-nad-nisou']=array('nazev'=>'Jablonec nad Nisou','odkud'=>'z Jablonce nad Nisou','kde'=>'v Jabloneci nad Nisou');
$pusobiste['jesenik']=array('nazev'=>'Jeseník','odkud'=>'z Jeseníku','kde'=>'v Jeseníku');
$pusobiste['jicin']=array('nazev'=>'Jičín','odkud'=>'z Jičína','kde'=>'v Jičíně');
$pusobiste['jihlava']=array('nazev'=>'Jihlava','odkud'=>'z Jihlavy','kde'=>'v Jihlavaě');
$pusobiste['jindrichuv-hradec']=array('nazev'=>'Jindřichův Hradec','odkud'=>'z Jindřichova Hradce','kde'=>'v Jindřichově Hradeci');
$pusobiste['karlovy-vary']=array('nazev'=>'Karlovy Vary','odkud'=>'z Karlových Varů','kde'=>'v Karlových Varech');
$pusobiste['karvina']=array('nazev'=>'Karviná','odkud'=>'z Karviné','kde'=>'v Karviné');
$pusobiste['kladno']=array('nazev'=>'Kladno','odkud'=>'z Kladna','kde'=>'v Kladně');
$pusobiste['klatovy']=array('nazev'=>'Klatovy','odkud'=>'z Klatov','kde'=>'v Klatovech');
$pusobiste['kolin']=array('nazev'=>'Kolín','odkud'=>'z Kolína','kde'=>'v Kolíně');
$pusobiste['kromeriz']=array('nazev'=>'Kroměříž','odkud'=>'z Kroměříže','kde'=>'v Kroměříži');
$pusobiste['kutna-hora']=array('nazev'=>'Kutná Hora','odkud'=>'z Kutné Hory','kde'=>'v Kutné Hoře');
$pusobiste['liberec']=array('nazev'=>'Liberec','odkud'=>'z Liberece','kde'=>'v Libereci');
$pusobiste['litomerice']=array('nazev'=>'Litoměřice','odkud'=>'z Litoměřic','kde'=>'v Litoměřicích');
$pusobiste['louny']=array('nazev'=>'Louny','odkud'=>'z Loun','kde'=>'v Lounech');
$pusobiste['melnik']=array('nazev'=>'Mělník','odkud'=>'z Mělníka','kde'=>'v Mělníce');
$pusobiste['mlada-boleslav']=array('nazev'=>'Mladá Boleslav','odkud'=>'z Mladé Boleslavi','kde'=>'v Mladé Boleslavi');
$pusobiste['most']=array('nazev'=>'Most','odkud'=>'z Mostu','kde'=>'v Mostě');
$pusobiste['nachod']=array('nazev'=>'Náchod','odkud'=>'z Náchoda','kde'=>'v Náchodě');
$pusobiste['novy-jicin']=array('nazev'=>'Nový Jičín','odkud'=>'z Nového Jičína','kde'=>'v Novém Jičíně');
$pusobiste['nymburk']=array('nazev'=>'Nymburk','odkud'=>'z Nymburka','kde'=>'v Nymburku');
$pusobiste['olomouc']=array('nazev'=>'Olomouc','odkud'=>'z Olomouce','kde'=>'v Olomouci');
$pusobiste['opava']=array('nazev'=>'Opava','odkud'=>'z Opavy','kde'=>'v Opavě');
$pusobiste['ostrava']=array('nazev'=>'Ostrava','odkud'=>'z Ostravy','kde'=>'v Ostravě');
$pusobiste['pardubice']=array('nazev'=>'Pardubice','odkud'=>'z Pardubic','kde'=>'v Pardubicích');
$pusobiste['pelhrimov']=array('nazev'=>'Pelhřimov','odkud'=>'z Pelhřimova','kde'=>'v Pelhřimově');
$pusobiste['pisek']=array('nazev'=>'Písek','odkud'=>'z Písku','kde'=>'v Písku');
$pusobiste['plzen']=array('nazev'=>'Plzeň','odkud'=>'z Plzně','kde'=>'v Plzňi');
$pusobiste['praha']=array('nazev'=>'Praha','odkud'=>'z Prahy','kde'=>'v Praze');
$pusobiste['prachatice']=array('nazev'=>'Prachatice','odkud'=>'z Prachatic','kde'=>'v Prachaticích');
$pusobiste['prostejov']=array('nazev'=>'Prostějov','odkud'=>'z Prostějova','kde'=>'v Prostějově');
$pusobiste['prerov']=array('nazev'=>'Přerov','odkud'=>'z Přerova','kde'=>'v Přerově');
$pusobiste['pribram']=array('nazev'=>'Příbram','odkud'=>'z Příbrami','kde'=>'v Příbrami');
$pusobiste['rakovnik']=array('nazev'=>'Rakovník','odkud'=>'z Rakovníka','kde'=>'v Rakovníku');
$pusobiste['rokycany']=array('nazev'=>'Rokycany','odkud'=>'z Rokycan','kde'=>'v Rokycanech');
$pusobiste['rychnov-nad-kneznou']=array('nazev'=>'Rychnov nad Kněžnou','odkud'=>'z Rychnova nad Kněžnou','kde'=>'v Rychnově nad Kněžnou');
$pusobiste['semily']=array('nazev'=>'Semily','odkud'=>'z Semil','kde'=>'v Semilech');
$pusobiste['sokolov']=array('nazev'=>'Sokolov','odkud'=>'ze Sokolov','kde'=>'v Sokolově');
$pusobiste['strakonice']=array('nazev'=>'Strakonice','odkud'=>'ze Strakonic','kde'=>'ve Strakonicích');
$pusobiste['svitavy']=array('nazev'=>'Svitavy','odkud'=>'ze Svitav','kde'=>'ve Svitavech');
$pusobiste['sumperk']=array('nazev'=>'Šumperk','odkud'=>'z Šumperka','kde'=>'v Šumperku');
$pusobiste['tabor']=array('nazev'=>'Tábor','odkud'=>'z Tábora','kde'=>'v Táboře');
$pusobiste['tachov']=array('nazev'=>'Tachov','odkud'=>'z Tachova','kde'=>'v Tachově');
$pusobiste['teplice']=array('nazev'=>'Teplice','odkud'=>'z Teplic','kde'=>'v Teplicích');
$pusobiste['trutnov']=array('nazev'=>'Trutnov','odkud'=>'z Trutnova','kde'=>'v Trutnově');
$pusobiste['trebic']=array('nazev'=>'Třebíč','odkud'=>'z Třebíče','kde'=>'v Třebíči');
$pusobiste['uherske-hradiste']=array('nazev'=>'Uherské Hradiště','odkud'=>'z Uherského Hradiště','kde'=>'v Uherském Hradišti');
$pusobiste['usti-nad-labem']=array('nazev'=>'Ústí nad Labem','odkud'=>'z Ústí nad Labem','kde'=>'v Ústí nad Labem');
$pusobiste['usti-nad-orlici']=array('nazev'=>'Ústí nad Orlicí','odkud'=>'z Ústí nad Orlicí','kde'=>'v Ústí nad Orlicí');
$pusobiste['vsetin']=array('nazev'=>'Vsetín','odkud'=>'ze Vsetína','kde'=>'ve Vsetíně');
$pusobiste['vyskov']=array('nazev'=>'Vyškov','odkud'=>'z Vyškova','kde'=>'ve Vyškově');
$pusobiste['zlin']=array('nazev'=>'Zlín','odkud'=>'ze Zlína','kde'=>'ve Zlíně');
$pusobiste['znojmo']=array('nazev'=>'Znojmo','odkud'=>'ze Znojma','kde'=>'ve Znojmě');
$pusobiste['zdar-nad-sazavou']=array('nazev'=>'Žďár nad Sázavou','odkud'=>'ze Žďáru nad Sázavou','kde'=>'ve Žďáru nad Sázavou');
?>
