<?php
$pusobiste=array();
$pusobiste['cela-cr']=array('nazev'=>'Celá ČR');
$pusobiste['cechy']=array('nazev'=>'Čechy');
$pusobiste['morava']=array('nazev'=>'Morava');
$pusobiste['slezko']=array('nazev'=>'Slezko');
$pusobiste['slovensko']=array('nazev'=>'Slovenská republika');
$pusobiste['benesov']=array('nazev'=>'Benešov');
$pusobiste['beroun']=array('nazev'=>'Beroun');
$pusobiste['blansko']=array('nazev'=>'Blansko');
$pusobiste['brno']=array('nazev'=>'Brno');
$pusobiste['bruntal']=array('nazev'=>'Bruntál');
$pusobiste['breclav']=array('nazev'=>'Břeclav');
$pusobiste['ceska-lipa']=array('nazev'=>'Česká Lípa');
$pusobiste['ceske-budejovice']=array('nazev'=>'České Budějovice');
$pusobiste['cesky-krumlov']=array('nazev'=>'Český Krumlov');
$pusobiste['decin']=array('nazev'=>'Děčín');
$pusobiste['domazlice']=array('nazev'=>'Domažlice');
$pusobiste['frydek-mistek']=array('nazev'=>'Frýdek-Místek');
$pusobiste['havlickuv-brod']=array('nazev'=>'Havlíčkův Brod');
$pusobiste['hodonin']=array('nazev'=>'Hodonín');
$pusobiste['hradec-kralove']=array('nazev'=>'Hradec Králové');
$pusobiste['cheb']=array('nazev'=>'Cheb');
$pusobiste['chomutov']=array('nazev'=>'Chomutov');
$pusobiste['chrudim']=array('nazev'=>'Chrudim');
$pusobiste['jablonec-nad-nisou']=array('nazev'=>'Jablonec nad Nisou');
$pusobiste['jesenik']=array('nazev'=>'Jeseník');
$pusobiste['jicin']=array('nazev'=>'Jičín');
$pusobiste['jihlava']=array('nazev'=>'Jihlava');
$pusobiste['jindrichuv-hradec']=array('nazev'=>'Jindřichův Hradec');
$pusobiste['karlovy-vary']=array('nazev'=>'Karlovy Vary');
$pusobiste['karvina']=array('nazev'=>'Karviná');
$pusobiste['kladno']=array('nazev'=>'Kladno');
$pusobiste['klatovy']=array('nazev'=>'Klatovy');
$pusobiste['kolin']=array('nazev'=>'Kolín');
$pusobiste['kromeriz']=array('nazev'=>'Kroměříž');
$pusobiste['kutna-hora']=array('nazev'=>'Kutná Hora');
$pusobiste['liberec']=array('nazev'=>'Liberec');
$pusobiste['litomerice']=array('nazev'=>'Litoměřice');
$pusobiste['louny']=array('nazev'=>'Louny');
$pusobiste['melnik']=array('nazev'=>'Mělník');
$pusobiste['mlada-boleslav']=array('nazev'=>'Mladá Boleslav');
$pusobiste['most']=array('nazev'=>'Most');
$pusobiste['nachod']=array('nazev'=>'Náchod');
$pusobiste['novy-jicin']=array('nazev'=>'Nový Jičín');
$pusobiste['nymburk']=array('nazev'=>'Nymburk');
$pusobiste['olomouc']=array('nazev'=>'Olomouc');
$pusobiste['opava']=array('nazev'=>'Opava');
$pusobiste['ostrava']=array('nazev'=>'Ostrava');
$pusobiste['pardubice']=array('nazev'=>'Pardubice');
$pusobiste['pelhrimov']=array('nazev'=>'Pelhřimov');
$pusobiste['pisek']=array('nazev'=>'Písek');
$pusobiste['plzen']=array('nazev'=>'Plzeň');
$pusobiste['praha']=array('nazev'=>'Praha');
$pusobiste['prachatice']=array('nazev'=>'Prachatice');
$pusobiste['prostejov']=array('nazev'=>'Prostějov');
$pusobiste['prerov']=array('nazev'=>'Přerov');
$pusobiste['pribram']=array('nazev'=>'Příbram');
$pusobiste['rakovnik']=array('nazev'=>'Rakovník');
$pusobiste['rokycany']=array('nazev'=>'Rokycany');
$pusobiste['rychnov-nad-kneznou']=array('nazev'=>'Rychnov nad Kněžnou');
$pusobiste['semily']=array('nazev'=>'Semily');
$pusobiste['sokolov']=array('nazev'=>'Sokolov');
$pusobiste['strakonice']=array('nazev'=>'Strakonice');
$pusobiste['svitavy']=array('nazev'=>'Svitavy');
$pusobiste['sumperk']=array('nazev'=>'Šumperk');
$pusobiste['tabor']=array('nazev'=>'Tábor');
$pusobiste['tachov']=array('nazev'=>'Tachov');
$pusobiste['teplice']=array('nazev'=>'Teplice');
$pusobiste['trutnov']=array('nazev'=>'Trutnov');
$pusobiste['trebic']=array('nazev'=>'Třebíč');
$pusobiste['uherske-hradiste']=array('nazev'=>'Uherské Hradiště');
$pusobiste['usti-nad-labem']=array('nazev'=>'Ústí nad Labem');
$pusobiste['usti-nad-orlici']=array('nazev'=>'Ústí nad Orlicí');
$pusobiste['vsetin']=array('nazev'=>'Vsetín');
$pusobiste['vyskov']=array('nazev'=>'Vyškov');
$pusobiste['zlin']=array('nazev'=>'Zlín');
$pusobiste['znojmo']=array('nazev'=>'Znojmo');
$pusobiste['zdar-nad-sazavou']=array('nazev'=>'Žďár nad Sázavou');
?>
