<?php

$zverokruh=array(
'beran'=>array(
						'popis'=>'Beran','od_mesic'=>'3','od_den'=>'21','do_mesic'=>'4','do_den'=>'20'),
'byk'=>array(
						'popis'=>'Býk','od_mesic'=>'4','od_den'=>'21','do_mesic'=>'5','do_den'=>'20'),
'blizenci'=>array(
						'popis'=>'Blí¾enci','od_mesic'=>'5','od_den'=>'21','do_mesic'=>'6','do_den'=>'21'),
'rak'=>array(
						'popis'=>'Rak','od_mesic'=>'6','od_den'=>'22','do_mesic'=>'7','do_den'=>'22'),
'lev'=>array(
						'popis'=>'Lev','od_mesic'=>'7','od_den'=>'23','do_mesic'=>'8','do_den'=>'23'),
'panna'=>array(
						'popis'=>'Panna','od_mesic'=>'8','od_den'=>'24','do_mesic'=>'9','do_den'=>'23'),
'vahy'=>array(
						'popis'=>'Váhy','od_mesic'=>'9','od_den'=>'24','do_mesic'=>'10','do_den'=>'23'),
'stir'=>array(
						'popis'=>'©tír','od_mesic'=>'10','od_den'=>'24','do_mesic'=>'11','do_den'=>'22'),
'strelec'=>array(
						'popis'=>'Støelec','od_mesic'=>'11','od_den'=>'23','do_mesic'=>'12','do_den'=>'21'),
'kozoroh'=>array(
						'popis'=>'Kozoroh','od_mesic'=>'12','od_den'=>'22','do_mesic'=>'1','do_den'=>'20'),
'vodnar'=>array(
						'popis'=>'Vodnáø','od_mesic'=>'1','od_den'=>'21','do_mesic'=>'2','do_den'=>'19'),
'ryby'=>array(
						'popis'=>'Ryby','od_mesic'=>'2','od_den'=>'20','do_mesic'=>'3','do_den'=>'20')
);



$vety=array();

$vety[0]=array(
array('èeká vás','buïte pøipraveni na','oèekávejte','mù¾e pøijít'),
array('hodnì','málo','trochu','poskrovnu','velmi mnoho','malièko'),
array('<a href="/kuzely/passing/" title="¾onglování ve více lidech">passingu</a>','zábavy','odpoèinku','spánku','radosti','smutku','<a href="/micky/4/destnik.html" title="">de¹tníkù</a>','<a href="/micky/4/krabice.html" title="">krabic s pøekvapením</a>','<a href="/micky/4/kriz.html" title="">køí¾ù</a>','<a href="/micky/4/sprcha.html" title="">horkou sprchu</a>','<a href="/micky/4/tenis.html" title="">tenis</a>'),
array('a <a href="/micky/3/kaskada-reverzni.html" title="">reverzní kaskády</a>','a <a href="/micky/3/robot.html" title="">robotù</a>','a <a href="/micky/3/seesaw.html" title="">see saw</a>','a <a href="/micky/3/sloupy.html" title="">sloupù</a>','a <a href="/micky/3/socha.html" title="">soch svobody</a>','a <a href="/micky/3/sprcha.html" title="">studenou sprchu</a>','a <a href="/micky/3/tenis.html" title="">tenis</a>','a <a href="/micky/3/mlyn.html" title="">vìtrný mlýn</a>','a <a href="/micky/3/krk.html" title="">zachycení míèku za krk</a>','a <a href="/micky/3/zkrizene-ruce.html" title="">zkøí¾ení rukou</a>','a <a href="/micky/3/zirafa.html" title="">¾irafa</a>','')
);

$vety[1]=array(
array('buïte','zkuste být','mìli by jste být','vyzkou¹ejte být','nezkou¹ejte být','nebuïte'),
array('opatrní','odvá¾ní','rozumní','uvá¾liví','obezøetní','upøímní','rázní','neoblomní','rozhodní','pøemý¹livý'),
array('pøi konzumaci alkoholu','pøi sportu','v soukromí','v zamìstnání','pøi navazování nových známostí','v tom co dìláte i øíkáte')
);

$vety[2]=array(
array('pøichází','nastává','budete mít','pro¾ijete','èekejte','oèekávejte','je'),
array('vcelku','èásteènì','velmi',''),
array('pøíhodné','vhodné','nevhodné','pøíznivé','nepøíznivé','prùmìrné'),
array('období','údobí','èasové období'),
array('pro'),
array('trénink <a href="/micky/5/kaskada.html" title="Obtí¾ný trik s pìti míèky.">kaskády</a>','lásku a flirt','výmìnu názorù','<a href="/kuzely/passing/" title="¾onglování ve více lidech">passing</a>','dovolenou','pozitivní my¹lení')
);

$vety[3]=array(
array('','nacvièenou','vrozenou','neobvyklou','obvyklou','rutinní','neoèekávanou','oèekávanou'),
array('bystrost','empatii','odolnost','rychlost','galantnost','náklonnost k opaènému pohlaví'),
array('proká¾í','naleznou','v sobì objeví','v sobì naleznou'),
array('pøedev¹ím','hlavnì','dokonce i','nejenom','i','také',''),
array('dìti','dospívající','mu¾i','¾eny','dívky','sourozenci','dùchodci','dùchodkynì','dìvèata','uèitelky','zdravotní sestry','lékaøi','øidièi','prodavaèky','man¾elky','milenky','vdovy','osamìlí lidé','pekaøi','vedoucí pracovníci','studenti')
);

$vety[4]=array(
array('vá¹','dominantní','osudový',''),
array('Merkur','Uran','Jupiter','Pluto','Saturn','Mars','Neptun','<a href="/kuzely/passing/4count.html" title="snadné">4 count</a>','<a href="/kuzely/passing/3count.html" title="snadné">valèík</a>','<a href="/kuzely/passing/2count.html" title="snadné">2 count</a>','<a href="/kuzely/passing/australsky-trik.html" title="snadné">australský trik</a>'),
array('se'),
array('tentokrát spojí','pøíznivì míjí','pozitivnì ovlivòuje','negativnì ovlivòuje'),
array('s'),
array('lunou,','Venu¹í,','Phobosem,','krátery na mìsíci,','kosmickým záøením,'),
array('to naznaèuje','to znaèí','to napovídá','to dává tu¹it'),
array('v prùbìhu','bìhem'),
array('dne¹ka','zítøka','následujícího týdne','nadcházejícího období'),
array('pøíchod'),
array('èehosi','nìèeho'),
array('neèekaného','neobvyklého','nepravdìpodobného','záva¾ného','úsmìvného','k pousmání','pozitivního','radostného')
);

$vety[5]=array(
array('nebojte se','odhodlejte se'),
array('nadchnout pro','prozkoumat','objevit','projevit','oprá¹it','provìøit'),
array('dlouho','dlouhodobì','náhodnì','vytrvale','pøechodnì','stále',''),
array('odpírané','slibované','sdílené','omezené'),
array('vá¹nì','city','vzpomínky','zá¾itky','nápady')
);

$vety[6]=array(
array('ráno','dopoledne','veèer','brzy ráno','po obìdì','v noci','odpoledne','celý den','po probuzení','je¹tì chvíli','po jídle','pøed jídlem','náhle','pozvolnì','krátkodobì','za svítání','za soumraku','po návratu ze zamìstnání','po pøíchodu do zamìstnání','obèas','dnes','zítra'),
array('se budete cítit','se nebudete cítit'),
array('dobøe','vesele','smutnì','opu¹tìnì','rozmaøile','velmi dobøe','¹patnì','jako v cizí kù¾i','sebejistì','podivnì','vyrovnanì','unavenì','jako na pou¹ti')
);

$vety[7]=array(
array('sna¾te','pokuste','nesna¾te','nepokou¹ejte'),
array('se'),
array('mít','o','dosáhnout'),
array('klid','nadhled'),
array('a'),
array('du¹evní','vnitøní','celkovou'),
array('pohodu','vyrovnanost')
);


$vety[8]=array(
array('snadno','rychle','dlouhodobì','pomalu','nenápadnì','nápadnì','krátkodobì'),
array('se'),
array('vám'),
array('zvy¹uje','sni¾uje','kolísá'),
array('hladina','podíl','koncentrace'),
array('adrenalinu','cukru','cholesterolu','endorfinù','tuku'),
array('v krvi','v tìle','')
);



$vety[9]=array(
array('neopustí'),
array('vás'),
array('humor','zdraví','vtip','pøízeò okolí'),
array('a','ani'),
array('¹tìstí','dobrá nálada','veselá mysl')
);

?>
