<?php

$zverokruh=array(
'beran'=>array(
						'popis'=>'Beran','od_mesic'=>'3','od_den'=>'21','do_mesic'=>'4','do_den'=>'20'),
'byk'=>array(
						'popis'=>'Býk','od_mesic'=>'4','od_den'=>'21','do_mesic'=>'5','do_den'=>'20'),
'blizenci'=>array(
						'popis'=>'Blíženci','od_mesic'=>'5','od_den'=>'21','do_mesic'=>'6','do_den'=>'21'),
'rak'=>array(
						'popis'=>'Rak','od_mesic'=>'6','od_den'=>'22','do_mesic'=>'7','do_den'=>'22'),
'lev'=>array(
						'popis'=>'Lev','od_mesic'=>'7','od_den'=>'23','do_mesic'=>'8','do_den'=>'23'),
'panna'=>array(
						'popis'=>'Panna','od_mesic'=>'8','od_den'=>'24','do_mesic'=>'9','do_den'=>'23'),
'vahy'=>array(
						'popis'=>'Váhy','od_mesic'=>'9','od_den'=>'24','do_mesic'=>'10','do_den'=>'23'),
'stir'=>array(
						'popis'=>'Štír','od_mesic'=>'10','od_den'=>'24','do_mesic'=>'11','do_den'=>'22'),
'strelec'=>array(
						'popis'=>'Střelec','od_mesic'=>'11','od_den'=>'23','do_mesic'=>'12','do_den'=>'21'),
'kozoroh'=>array(
						'popis'=>'Kozoroh','od_mesic'=>'12','od_den'=>'22','do_mesic'=>'1','do_den'=>'20'),
'vodnar'=>array(
						'popis'=>'Vodnář','od_mesic'=>'1','od_den'=>'21','do_mesic'=>'2','do_den'=>'19'),
'ryby'=>array(
						'popis'=>'Ryby','od_mesic'=>'2','od_den'=>'20','do_mesic'=>'3','do_den'=>'20')
);



$vety=array();

$vety[0]=array(
array('čeká vás','buďte připraveni na','očekávejte','může přijít'),
array('hodně','málo','trochu','poskrovnu','velmi mnoho','maličko'),
array('<a href="/kuzely/passing/" title="žonglování ve více lidech">passingu</a>','zábavy','odpočinku','spánku','radosti','smutku','<a href="/micky/4/destnik.html" title="">deštníků</a>','<a href="/micky/4/krabice.html" title="">krabic s překvapením</a>','<a href="/micky/4/kriz.html" title="">křížů</a>','<a href="/micky/4/sprcha.html" title="">horkou sprchu</a>','<a href="/micky/4/tenis.html" title="">tenis</a>'),
array('a <a href="/micky/3/kaskada-reverzni.html" title="">reverzní kaskády</a>','a <a href="/micky/3/robot.html" title="">robotů</a>','a <a href="/micky/3/seesaw.html" title="">see saw</a>','a <a href="/micky/3/sloupy.html" title="">sloupů</a>','a <a href="/micky/3/socha.html" title="">soch svobody</a>','a <a href="/micky/3/sprcha.html" title="">studenou sprchu</a>','a <a href="/micky/3/tenis.html" title="">tenis</a>','a <a href="/micky/3/mlyn.html" title="">větrný mlýn</a>','a <a href="/micky/3/krk.html" title="">zachycení míčku za krk</a>','a <a href="/micky/3/zkrizene-ruce.html" title="">zkřížení rukou</a>','a <a href="/micky/3/zirafa.html" title="">žirafa</a>','')
);

$vety[1]=array(
array('buďte','zkuste být','měli by jste být','vyzkoušejte být','nezkoušejte být','nebuďte'),
array('opatrní','odvážní','rozumní','uvážliví','obezřetní','upřímní','rázní','neoblomní','rozhodní','přemýšlivý'),
array('při konzumaci alkoholu','při sportu','v soukromí','v zaměstnání','při navazování nových známostí','v tom co děláte i říkáte')
);

$vety[2]=array(
array('přichází','nastává','budete mít','prožijete','čekejte','očekávejte','je'),
array('vcelku','částečně','velmi',''),
array('příhodné','vhodné','nevhodné','příznivé','nepříznivé','průměrné'),
array('období','údobí','časové období'),
array('pro'),
array('trénink <a href="/micky/5/kaskada.html" title="Obtížný trik s pěti míčky.">kaskády</a>','lásku a flirt','výměnu názorů','<a href="/kuzely/passing/" title="žonglování ve více lidech">passing</a>','dovolenou','pozitivní myšlení')
);

$vety[3]=array(
array('','nacvičenou','vrozenou','neobvyklou','obvyklou','rutinní','neočekávanou','očekávanou'),
array('bystrost','empatii','odolnost','rychlost','galantnost','náklonnost k opačnému pohlaví'),
array('prokáží','naleznou','v sobě objeví','v sobě naleznou'),
array('především','hlavně','dokonce i','nejenom','i','také',''),
array('děti','dospívající','muži','ženy','dívky','sourozenci','důchodci','důchodkyně','děvčata','učitelky','zdravotní sestry','lékaři','řidiči','prodavačky','manželky','milenky','vdovy','osamělí lidé','pekaři','vedoucí pracovníci','studenti')
);

$vety[4]=array(
array('váš','dominantní','osudový',''),
array('Merkur','Uran','Jupiter','Pluto','Saturn','Mars','Neptun','<a href="/kuzely/passing/4count.html" title="snadné">4 count</a>','<a href="/kuzely/passing/3count.html" title="snadné">valčík</a>','<a href="/kuzely/passing/2count.html" title="snadné">2 count</a>','<a href="/kuzely/passing/australsky-trik.html" title="snadné">australský trik</a>'),
array('se'),
array('tentokrát spojí','příznivě míjí','pozitivně ovlivňuje','negativně ovlivňuje'),
array('s'),
array('lunou,','Venuší,','Phobosem,','krátery na měsíci,','kosmickým zářením,'),
array('to naznačuje','to značí','to napovídá','to dává tušit'),
array('v průběhu','během'),
array('dneška','zítřka','následujícího týdne','nadcházejícího období'),
array('příchod'),
array('čehosi','něčeho'),
array('nečekaného','neobvyklého','nepravděpodobného','závažného','úsměvného','k pousmání','pozitivního','radostného')
);

$vety[5]=array(
array('nebojte se','odhodlejte se'),
array('nadchnout pro','prozkoumat','objevit','projevit','oprášit','prověřit'),
array('dlouho','dlouhodobě','náhodně','vytrvale','přechodně','stále',''),
array('odpírané','slibované','sdílené','omezené'),
array('vášně','city','vzpomínky','zážitky','nápady')
);

$vety[6]=array(
array('ráno','dopoledne','večer','brzy ráno','po obědě','v noci','odpoledne','celý den','po probuzení','ještě chvíli','po jídle','před jídlem','náhle','pozvolně','krátkodobě','za svítání','za soumraku','po návratu ze zaměstnání','po příchodu do zaměstnání','občas','dnes','zítra'),
array('se budete cítit','se nebudete cítit'),
array('dobře','vesele','smutně','opuštěně','rozmařile','velmi dobře','špatně','jako v cizí kůži','sebejistě','podivně','vyrovnaně','unaveně','jako na poušti')
);

$vety[7]=array(
array('snažte','pokuste','nesnažte','nepokoušejte'),
array('se'),
array('mít','o','dosáhnout'),
array('klid','nadhled'),
array('a'),
array('duševní','vnitřní','celkovou'),
array('pohodu','vyrovnanost')
);


$vety[8]=array(
array('snadno','rychle','dlouhodobě','pomalu','nenápadně','nápadně','krátkodobě'),
array('se'),
array('vám'),
array('zvyšuje','snižuje','kolísá'),
array('hladina','podíl','koncentrace'),
array('adrenalinu','cukru','cholesterolu','endorfinů','tuku'),
array('v krvi','v těle','')
);



$vety[9]=array(
array('neopustí'),
array('vás'),
array('humor','zdraví','vtip','přízeň okolí'),
array('a','ani'),
array('štěstí','dobrá nálada','veselá mysl')
);

?>
